### ISSUE TITLE
md-input label not moving of input after model change

### ISSUE THREAD

**Issue by icehaunter** [marcosmoura/vue-material#100]
Looks like a bug similar to #69 but my md-input is only in md-input-container (basically just like in the docs). I have a button to fill my input with predefined value, and after I set it, input's value updates, but corresponding label still overlays it, not moving up.

**Comment by marcosmoura** [comment]
Which version are you using?

**Comment by marcosmoura** [comment]
Sorry. I could confirm that. Will be fixed in the next fix version. Thanks!
