### ISSUE TITLE
docs input foucs placeholder display error

### ISSUE THREAD

**Issue by stevieyu** [marcosmoura/vue-material#101]
![kapture 2016-11-21 at 13 17 20](https://cloud.githubusercontent.com/assets/8325201/20471469/ffc74726-afec-11e6-8a06-4f04e9eac047.gif)
https://marcosmoura.github.io/vue-material/#/components/input

**Comment by marcosmoura** [comment]
Oops! I'm publishing now a new release to fix this regression. Thanks again for the gif and sorry about this problem.
