### ISSUE TITLE
"Stuck" tooltips in v0.3.3

### ISSUE THREAD

**Issue by Stabzs** [marcosmoura/vue-material#103]
When numerous elements in close proximity (for instance, a repeated list of 10 elements) have tooltips on them and you quickly move up and down the elements, the tooltips occasionally get stuck and do not automatically dismiss.

This issue is not present in v0.3.1 and only appeared when upgrading to v0.3.3.

**Comment by marcosmoura** [comment]
Oh. I coundn't reproduce that. Can you give me a codepen example?

**Comment by Stabzs** [comment]
So sorry, I absolutely should have included an example.  http://codepen.io/anon/pen/BQWmrQ

In this case, I've noticed it within a tabs component tab when there are a number of elements, in Chrome.  Just move your mouse back and forth over the letters with tooltips.  Eventually one will get stuck.  It feels like an interrupted animation.  The issue does not occur with v0.3.1.

**Comment by marcosmoura** [comment]
(sorry about the delay to answer)
Oh. I see. This is a bad bug. And don't have a good workaround for now. I will fix that ASAP. Thanks a lot for the Codepen.
