### ISSUE TITLE
Support themeing with hex values

### ISSUE THREAD

**Issue by RemeJuan** [marcosmoura/vue-material#105]
Is it possible to setup the theme using hex values, when I try it throws an A200 error

**Comment by Stabzs** [comment]
Not currently. See https://github.com/marcosmoura/vue-material/issues/39

**Comment by marcosmoura** [comment]
Like @Stabzs said this is not possible yet. It will be improved.

**Comment by MaxZiebell** [comment]
Please do!

**Comment by MaximilianLloyd** [comment]
In desperate need of this right now
