### ISSUE TITLE
Getting CSS to work with vue-cli

### ISSUE THREAD

**Issue by madasebrof** [marcosmoura/vue-material#11]
For the README.md

1. add

import 'vue-material/dist/vue-material.css'

to main.js

2. use

var VueMaterial = require('vue-material')
not
import VueMaterial from 'vue-material'

in main.js

to use with vue-cli (vue init webpack)

ps looks awesome!

**Comment by marcosmoura** [comment]
Oh yeah. You're right. I think that the documentation wasn't clear enough. I will update this ASAP.
Thank you!

**Comment by jeffstahlin** [comment]
@madasebrof you are a lifesaver. am new to Vue.js and could not figure out why the CSS was only partially working, I had not seen the part about adding the import to the css file. Was about to give up there.

I am currently using ```import VueMaterial from 'vue-material'``` and it seems to work just fine. Could you please explain why using require is the preferred method?

**Comment by marcosmoura** [comment]
Both examples will work:
``` javascript
import Vue from 'vue'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'
import App from './App'

Vue.use(VueMaterial);

Vue.material.theme.register('default', {
  primary: 'blue'
})
```
Or
``` javascript
import Vue from 'vue'
import VueMaterial from 'vue-material'
import 'vue-material/dist/components/mdCore/index.css'
import 'vue-material/dist/components/mdButton/index.css'
import App from './App'

Vue.use(VueMaterial.mdCore)
Vue.use(VueMaterial.mdButton)

Vue.material.theme.register('default', {
  primary: 'blue'
})
```
You should have a task runner like Webpack with css-loader and babel configured, like on vue-cli.
I will update the documentation with this notes. I think that this will clarify.

**Comment by madasebrof** [comment]
For some weird reason, I am having a hard time with the ES6 import syntax. Running node 5.5.0 on Linux. It seems to work for the normal Vue modules, but not for third party stuff. Need to do some more digging. Again, using 'vue init webpack your_project_name' defaults. I've noticed a bunch of other folks on the web seem to be having similar issues. Could be issue with named exports format, but if it works for y'all...

**Comment by marcosmoura** [comment]
@madasebrof What do you mean by "Vue modules"? Like Vue Router? Have you ever tried to update to node? I'm running with node 6 here and everything is fine with the default configuration and with the most updated version of of vue-cli

**Comment by madasebrof** [comment]
Sweet. Will update to Node 6.
