### ISSUE TITLE
Reporting a bug Tab width - v0.3.3

### ISSUE THREAD

**Issue by smizon** [marcosmoura/vue-material#110]
Hello 

Currently having issues with my tabs, and have identified the cause. When i use firebug to disable the width attribute, everything works great.

```
.md-tabs .md-tabs-wrapper {
    width: 9999em; 
}
```

**Comment by marcosmoura** [comment]
Hi @smizon. Can you give me some screenshot to see the problem? Or put some code on Codepen?

**Comment by smizon** [comment]
Hello @marcosmoura , 

Sorry about that, First image show the issue with the width and location, which hides the content.
Second image shows removing the width fixes this 

_Image with the **Issue:**_

![screen shot 2016-11-25 at 00 43 44](https://cloud.githubusercontent.com/assets/2208078/20611760/555a3136-b2a8-11e6-92a7-8c00ba1e5d1c.png)


_Image with **Issue Gone:**_
![screen shot 2016-11-25 at 00 39 55](https://cloud.githubusercontent.com/assets/2208078/20611743/f8b792de-b2a7-11e6-8cf0-4697412ed84b.png)

**Comment by marcosmoura** [comment]
Well. I didn't get it. Do you have md-tabs in one side and another content on the other side?
Like 2 columns? And the md-tabs is affecting you content on the right side?
Or you tried to apply another CSS in order to change the tabs to be displayed on the right side of the navigation?

**Comment by smizon** [comment]
I have applied a global CSS rule without 'scoped' enabled. Seems to be working now.
 
> .md-tabs .md-tabs-wrapper{
>     width: 100% !important;
>   }
