### ISSUE TITLE
How to make layouts? here? 

### ISSUE THREAD

**Issue by DevEclipse** [marcosmoura/vue-material#111]
Im using the card component but on the documentation there are no layouts available and dialogs wil lthis be implemented? or is there a layout control but not documented?

**Comment by marcosmoura** [comment]
What do you mean by layout? Like a CSS Grid System (with rows and columns)?

**Comment by DevEclipse** [comment]
yeap

**Comment by marcosmoura** [comment]
Duplicated #78 #93 #37 #35
