### ISSUE TITLE
(in promise) TypeError: Cannot read property 'removeEventListener' of undefined(…)

### ISSUE THREAD

**Issue by DevEclipse** [marcosmoura/vue-material#112]
that error always emit in side nav with this code

 ```
 <div>
    <header>
      
    
    <md-toolbar>


      <h2 class="md-title" style="flex: auto">Hello {{currentUser.username}}</h2>

      <md-avatar >
  <img src="//placeimg.com/64/64/people/2" alt="People">
</md-avatar>
    <md-button @click="toggleUserSideNav">
      Dashboard
    </md-button>
    </md-toolbar>
    </header>
    <md-sidenav class="md-right" ref="userSidenav" >
        <md-toolbar class="md-large">
    <div class="md-toolbar-container">
      <h3 class="md-title">Your Dashboard</h3>
    </div>
  </md-toolbar>
    <md-list>
  <md-list-item>
    <md-icon>move_to_inbox</md-icon> <router-link tag="span" :to="{ name: 'news'}">News</router-link>
  </md-list-item>
  <md-list-item>
    <md-icon>move_to_inbox</md-icon> <router-link tag="span" :to="{ name: 'info'}">Info</router-link>
  </md-list-item>

  <md-list-item>
    <md-icon>send</md-icon> <span>Edit Account</span>
  </md-list-item>

  <md-list-item @click="$root.signOut">
    <md-icon>error</md-icon> <span>Log Out</span>
  </md-list-item>
  </md-list>
    </md-sidenav>
    <main>
      <router-view :current_user="currentUser"></router-view>
    </main>
  </div>
```

vue methods:

```
    methods: {
      toggleUserSideNav() {
        this.$refs.userSidenav.toggle();
      },
    }
```

![image](https://cloud.githubusercontent.com/assets/19868205/20615303/691082aa-b313-11e6-9aca-97396926b6b1.png)

please repro this

**Comment by DevEclipse** [comment]
the problem was the mb button its removing a listener that is not defined

**Comment by marcosmoura** [comment]
I see. Change the click function on your button and list item to ```click.native```. This works for you?

**Comment by DevEclipse** [comment]
it works its seems that the md button with a tooltop made it

**Comment by marcosmoura** [comment]
Ok. Cool! :D
I will close this. If something wrong come up please let me know!

**Comment by nishantha-kumara** [comment]
@marcosmoura I have same problem in Vue Material. getting error this
`<div v-if="isLogged">
<md-menu md-direction="bottom left" >
                                <md-button md-menu-trigger >Bottom Left</md-button>
                                <md-menu-content>
                                    <md-menu-item>My Item 1</md-menu-item>
                                    <md-menu-item>My Item 2</md-menu-item>
                                    <md-menu-item>My Item 4</md-menu-item>
                                </md-menu-content>
                            </md-menu>
</div>`

can you send the example code?
