### ISSUE TITLE
error message if md-sort-by is not set

### ISSUE THREAD

**Issue by Cabbaggio** [marcosmoura/vue-material#114]
Error Message: Uncaught (in promise) TypeError: Cannot read property 'removeEventListener' of undefined

http://codepen.io/anon/pen/mOMbwB

**Comment by marcosmoura** [comment]
Oh. That's bad. I think the ```<md-table-head>``` is having a problem with the ```md-ink-ripple``` component. I will take a deep look. Sorry about that.
