### ISSUE TITLE
How can I clear SelectedRows in a table?

### ISSUE THREAD

**Issue by Cabbaggio** [marcosmoura/vue-material#116]
After i deleted the selected rows in a table, the rows within the component are still selected.
Is there a way to clear the selected rows inside the table component?
 
Short example:
http://codepen.io/anon/pen/pNrebr

And i have annother question. Is there a reason why you return the selected rows as an object instead of an array?

**Comment by marcosmoura** [comment]
I will take a look at this too. Sorry about that. This component demands more tests.
Yeah. I had to convert the Array into an Object for performance reasons. I will expose a method to receive this as an Array again.

**Comment by rkirmizi** [comment]
Is there any solution or improvement about that?

**Comment by marcosmoura** [comment]
Not yet. I will prioritize that.

**Comment by Birssan** [comment]
Having the same problem.
I tried to get my hands dirty and fix the problem in the Table/TableRow components, first there the `data` attribute in the Table component is not correctly updated when removing a row.

In mdTableRow.vue

```
mdItem(newValue, oldValue) {
    this.parentTable.data[this.index] = this.mdItem;
}
```

Should be 

```
mdItem(newValue, oldValue) {
    this.parentTable.data[this.index - 1] = this.mdItem;
}
```

From what I saw, when you delete a row from the table, that's always the last mdTableRow element which is removed after Vue updated all the rows below the one you deleted.
So basically when you delete a row, the `mdItem` is changed for every row below the deleted one and is changed in the `data` table thanks to the watcher.
I added a `beforeDestroy` in mdTableRow component to remove the last element from `data` like this.

```
beforeDestroy() {
    this.parentTable.data.pop(); // delete last element (after mdItem is updated)
}
```

These two modifications allow the `data` attribute to be up to date when deleting rows.
Now the issue regarding selection clearing is still not resolved on my part...

Using an object of object to handle selected rows makes it harder to resolve I think... As the `data`attribute changes its indexes once it changes, the `selectedRows` on the other hand always keep the old indexes which means, you have to update `selectedRows` on each deletion, so far I haven't been able to make it work correctly, It works when you delete one row at a time, but for multiple rows , no luck...

**Comment by flybayer** [comment]
> After i deleted the selected rows in a table, the rows within the component are still selected.
Is there a way to clear the selected rows inside the table component?

I'm having this exact problem with 0.7.1. Can this issue be re-opened?

**Comment by SarahZhao806** [comment]
I have the same issue. onRowSelection prop in the Table component will keep previous value instead of being renewed after re-rendering the Table.

**Comment by superbogy** [comment]
same problem exist 0.7.1, hope to fix this bug~~

**Comment by weinr0ck** [comment]
Is this bug slated to be fixed in 0.8.1 now since 1.0 beta is in progress?

**Comment by VdustR** [comment]
Selected rows could be cleared via `:md-selected-value.sync="selected"`, `this.selected = []` in `1.0.0-beta-8`

**Comment by VdustR** [comment]
`<md-table :md-selected-value.sync="selected">`

here is an example: https://codepen.io/VdustR/pen/wyoQKx

**Comment by ueharajohji** [comment]
Thanks 

I'm trying to implement a pagination function with 2.5.3 and the problem is whenever I update the
model , the table gets updated with the newly fetched model but the md-table component still has the previous data so when I check the "select all" box it gets the previous data + the data in page 2 which makes the selected variable contain page 1 and page 2 data. Do you have any suggestions on how to deal with this?
