### ISSUE TITLE
require('vue-material/dist/vue-material.css') not working with browserify

### ISSUE THREAD

**Issue by sombriks** [marcosmoura/vue-material#120]
At the official docs it shows how to import the css definitions into the app

it however seems to work just for webpack

if the setup uses browserify, this approach will lead to error.

i've made this repo which samples the problem at this specific commit:
https://github.com/sombriks/simple-vue-material-setup/tree/8cba6cfc9ab4486b653457bf0926845ba1c1e20d

right now i'm looking for ways to make it work and one approach is to use browserify-css, which can be seen at this specific commit:
https://github.com/sombriks/simple-vue-material-setup/tree/f333eb70e18e69fcd20b38473508c704f62aae5e

instead of direct requiring the vue css, browserify-css demands me to provide an "entry point".

anyone else have better options for browserify simpler setups?

**Comment by marcosmoura** [comment]
Well. Browserify *do not* support require of .css in Javascript files.
Instead of require you can have a <style> with the Vue Material file.
Like this:
``` vue
// app.vue
<style src="path/to/vue-material.css"></style>

<style> ... </style>

<template> ... </template>

<script> ... </script>
``

I hope this fix works for you.
Thank you!
