### ISSUE TITLE
set selected in MdSelect

### ISSUE THREAD

**Issue by tridcatij** [marcosmoura/vue-material#122]
First of all thank you for your incredible project!

It's not clear to me how to set default value for the select list. How to make 'LIKE' a default value in the example below?
```javascript
operators: {
equal: "=",
greater_than: ">",
greater_than_or_equal_to: ">=",
in: "IN",
less_than: "<",
less_than_or_equal_to: "<=",
like: "LIKE",
not_equal: "<>",
}
```
```html
<md-select>
    <md-option v-for="operator in operators" :value="operator" >
        {{ operator }}
    </md-option>
</md-select>
```

Thank you!

**Comment by marcosmoura** [comment]
The correct code for this problem is:
``` vue
<md-select v-model="myModel">
    <md-option v-for="(key, operator) in operators" :value="key">{{ operator }}</md-option>
</md-select>
```

``` javascript
{
  data: () => {
    return {
      myModel: 'like'
    };
  }
}
```

This is not a Vue Material behaviour, but a Vue.js way to repeat items.
Thanks.

**Comment by demonodojo** [comment]
I have used the following code:
`<md-select name="province" id="province" :value="province" >
                  <md-option v-for="province in provinces" :value="province.id" >{{province.name}}</md-option>
                </md-select>`
And similar code with basic components:
`<select name="province" id="province" :value="province" >
                  <option v-for="province in provinces" :value="province.id" >{{province.name}}</option>
                </select>`
The first one does not select the province value while the second does it.
province is in data and provinces come from an apollo query

**Comment by hitautodestruct** [comment]
@marcosmoura in the example you gave the `v-for="(key, operator) in ..` is flipped it should be `v-for="(operator, key) in ..` as per [the docs](https://vuejs.org/v2/api/#v-for). Kind of confusing that it's value:key and not key:value.
