### ISSUE TITLE
<md-select> Input field for filtering (space key prevented)

### ISSUE THREAD

**Issue by bolerodan** [marcosmoura/vue-material#123]
First, love the work you are doing here, I use it in one of my projects, I come from Angular Material so all of this is extremely familiar to me and soon I hope to contribute to your work.

I tried implementing a search filter field that sits above the menu items in the select component. Similiar to Angular Materials structure. It works great, except that md-menu-content prevents the space key as an action, causing me not being able to press the space bar in the input field.

I'm trying to think of ways to get around this. Another named slot that will put stuff outside of md-menu-content perhaps?

Right now I can live with it in my project, but I'm curious as to a way you would like this implemented or a thought for the future.

Thanks a lot!

**Comment by marcosmoura** [comment]
Thanks for the words.
Yeah. The ```<md-select>``` are intended to use the 'space' key event to confirm the selection. I have plans to implement the select header with a search behaviour. There is no workaround for now, sorry about that.

**Comment by marcosmoura** [comment]
I will close this issue for now and reopen when I start to develop this improvement. Thanks!
