### ISSUE TITLE
Why do u can render a Object in v-for [mdTabs].

### ISSUE THREAD

**Issue by ChenZerong** [marcosmoura/vue-material#126]
I recently started learning vue, I tried to component of the time, I found no way to use v-for the rendering of an Object data, I found your mdTabs components can be done, this is amazing, I checked the information and Read the source code are not the result, I would like to ask about ~

file: src/mdTabs/mdTabs.vue
![image](https://cloud.githubusercontent.com/assets/16299018/20752694/98cd46da-b73d-11e6-860a-ee543480e0d2.png)
![image](https://cloud.githubusercontent.com/assets/16299018/20752700/9fa3c5ba-b73d-11e6-9749-0126d428f3d0.png)
![image](https://cloud.githubusercontent.com/assets/16299018/20752705/a9773658-b73d-11e6-9612-4b2439cf982d.png)

i try something like function:registerTab,  first time it's empty, after the children render, the Object data will be fill,  but it can't work. Q _Q

**Comment by marcosmoura** [comment]
I didn't understand what you're asking. Do you want to create a component aside vue-material? Or do you want to implement mdTabs dynamically with an object as a source?

**Comment by ChenZerong** [comment]
@marcosmoura  yeah, i want to implement mdTabs dynamically with an object as a source.

**Comment by marcosmoura** [comment]
You can have something like that:
``` vue
<md-tabs>
  <md-tab v-for="tab in tabs" :md-label="tab.label">
    {{ tab.content }}
  </md-tab>
</md-tabs>
```

``` javascript
tabs: [
  {
    label: 'Phone',
    content: 'Totam dolorum temporibus cumque nulla praesentium, aliquam earum quas rerum ab blanditiis provident.'
  },
  {
    label: 'Favorites',
    content: 'Maiores consequuntur magnam, error possimus, non qui sed modi iusto sunt.'
  },
  {
    label: 'Near me',
    content: 'Tempore dignissimos veniam iure minus, quidem, est tenetur mollitia similique aspernatur velit.'
  }
]
```

Please let me know if this works for you.
Thanks.

**Comment by ChenZerong** [comment]
thanks~ it can work for me.
![image](https://cloud.githubusercontent.com/assets/16299018/20778994/9e4b2270-b7ac-11e6-878b-71525fe171dd.png)

But I read your source code, I would like to know is that in my component, how can I let my components like you, let an empty Object after adding the content update view, like your components.

![image](https://cloud.githubusercontent.com/assets/16299018/20779062/0fc9cae6-b7ad-11e6-8afa-6d5fed7a0dd1.png)
your object can work v-for after tab's data adding.


![image](https://cloud.githubusercontent.com/assets/16299018/20779142/7b6dc59a-b7ad-11e6-8852-c0d3b770d55e.png)
my components also adding data in second time. but my button can't be rendered. 😢

**Comment by marcosmoura** [comment]
Well. This is pretty much Vue.js logic here. There is no additional secret to make this object for being rendered. Please notice that this do not have any relation with Vue Material.
This object below will work exactly like the last example that I gave to you.
``` javascript
tabs: {
  phone: {
    label: 'Phone',
    content: 'Totam dolorum temporibus cumque nulla praesentium, aliquam earum quas rerum ab blanditiis provident.'
  },
  favorites: {
    label: 'Favorites',
    content: 'Maiores consequuntur magnam, error possimus, non qui sed modi iusto sunt.'
  },
  near_me: {
    label: 'Near me',
    content: 'Tempore dignissimos veniam iure minus, quidem, est tenetur mollitia similique aspernatur velit.'
  }
}
```

Please let me know if this works for you.
Thanks.

**Comment by ChenZerong** [comment]
i try it, your last example can work for me. maybe my code have some unknow error, i think it by myself . thank you very much, vue-material is great! 👍
