### ISSUE TITLE
Md table errors

### ISSUE THREAD

**Issue by eskrano** [marcosmoura/vue-material#127]
see #88 but not works for me and i have error. Use vuex + vue-router + vue2 . When i turnoff vuex everything works.

**Comment by marcosmoura** [comment]
Can you give me some examples? Please read the [issue](https://raw.githubusercontent.com/marcosmoura/vue-material/master/.github/ISSUE_TEMPLATE.md) template.

**Comment by marcosmoura** [comment]
@eskrano ping

**Comment by eskrano** [comment]
@marcosmoura i dont have example in this time. Delete the project. But i use base tables example (1st in docs)

**Comment by marcosmoura** [comment]
Well. I see. It lacks some informations, so I will close this issue. If something related to vuex come up I will reopen/reference this issue. Thanks.
