### ISSUE TITLE
Md-menu : whiteframe

### ISSUE THREAD

**Issue by throrin19** [marcosmoura/vue-material#129]
Hi,
I have a question about md-menu and md-whiteframe, it's possible to create a menu with a whiteframe ?

In the google guideline, menu are elevated and, in this case, menu must have a shadow. Actually, I can't find the possibility to add whiteframe on your md-menu component.

Thanks

**Comment by marcosmoura** [comment]
But menus have a shadow. With a 2dp thin. Are you testing in which browser?

**Comment by throrin19** [comment]
In your site and in my project, menu an select have no shadow. I test this on chrome linux 51.0.2704.106

**Comment by marcosmoura** [comment]
Oh. That's strange. I will take a look at this in this particular version of Chrome.

**Comment by throrin19** [comment]
I have the problem with Chrome OSX 54.0.2840.98 (64 bits). The shadow is visible on the show/hide of menu but disapear on hover

**Comment by sombriks** [comment]
in order to help to narrow down, my machine works well: http://imgur.com/a/cxjOa

**Comment by marcosmoura** [comment]
I already know what is wrong. It's related to 'clip-path' animation. I will fix this asap.

**Comment by throrin19** [comment]
Yeah it works fine
