### ISSUE TITLE
Fix Doc

### ISSUE THREAD

**Issue by ktquez** [marcosmoura/vue-material#13]
Hello Mark, blz
Thanks for excellent job in package!

I tried to register the components separately and how was documentation.
`Vue.use(VueMaterial.MdCore); //Required to boot vue material`
Then the components that need, e.g.
`Vue.use(VueMaterial.MdToolbar);`

But I looked at your code and the property only worked, at least in my project, with property starting with a lowercase letter, for example.
`Vue.use(VueMaterial.mdCore);`
`Vue.use(VueMaterial.mdToolbar);`

It may be a problem with the name resolution in my project, but it will be what happens to anyone else?
If so, just change the doc, thanks

Or, if you are normal for most, please disregard

**Comment by ktquez** [comment]
Ahhh, in my project I'm using SSR, can possibly be so.
I'm waiting

**Comment by marcosmoura** [comment]
@ktquez Yeah. You're right. This is really a  small problem in my package.  I'll change this ASAP. 
I never tried those components with ssr, but I think that they will work. Can you give me a feedback about it if you try this before me?

**Comment by ktquez** [comment]
@marcosmoura 
Using with SSR had some problems but mainly by manipulating the DOM, but fix it using 
the `jsdom-global`, e.g.
```javascript
require('jsdom-global')(htmlMarkup, { url: 'http://host:port' })
```
This fixes me.
