### ISSUE TITLE
Add ability to get palette from the current v-md-theme directive

### ISSUE THREAD

**Issue by albanm** [marcosmoura/vue-material#130]
I want to build custom components inside my project that can not be built purely from Vue Material base components (svg charts for example) but that should adapt to the same themes.

From what I see in the code maybe I should push something in Vue.material.styles ? This could solve a part of the problem, but ideally it should be possible to bind variables also.

**Comment by marcosmoura** [comment]
Well. What you want it to have a way to get the colors from the Vue Material theme engine, right? Right now this is not possible. As you can see [here](https://github.com/marcosmoura/vue-material/projects/3) there is an item on my backlog to develop this feature. This will be a way to declare a directive (or a component) and style your own custom component. But this is not prioritized yet. Sorry about that.
