### ISSUE TITLE
md-icon-button does not work when run dev locally

### ISSUE THREAD

**Issue by huobaiyu** [marcosmoura/vue-material#132]
<div id="wrapper" v-md-theme="'default'"> 
        <md-toolbar>
          <md-button class="md-icon-button">
            <md-icon>menu</md-icon>
          </md-button>

          <h2 class="md-title" style="flex: 1">Vue Material</h2>

          <md-button class="md-icon-button">
            <md-icon>favorite</md-icon>
          </md-button>
        </md-toolbar>
        <br></br>
         <div class="container">
          <router-view></router-view>
         </div>
    </div>

toolbar md-icon does not work, only show text.

### Steps to reproduce
1. git clone repo
2. npm install
3. npm run dev

### Which browser?
chrome 

latest version. 

### Reproduction Link

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE.

**Comment by marcosmoura** [comment]
Hi @huobaiyu.

Are you using the Material Icons? 
``` html
<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
```

**Comment by huobaiyu** [comment]
Yes. I have run  “npm install material-design-icons",but icons still not be shown.

**Comment by marcosmoura** [comment]
No. That's different. You should import material icons directly as a link in you HTML. Like on the snippet that I gave. :D

**Comment by huobaiyu** [comment]
In main.js file. I have add the following lines:
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'

import App from './App'
import 'bootstrap/dist/css/bootstrap.css'

Vue.use(VueMaterial)


Vue.material.theme.register('default', {
    primary: 'cyan',
    accent: 'pink'
})

**Comment by marcosmoura** [comment]
No. You should add this line in your index.html:
```
<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
```

**Comment by huobaiyu** [comment]
After I added "<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">“ in index.html. It works. Thank you.

**Comment by marcosmoura** [comment]
Cool!
