### ISSUE TITLE
Please share the simple project

### ISSUE THREAD

**Issue by Phanu282003** [marcosmoura/vue-material#133]
Hello,

I tried to implement vue-mateiral with my web application around 2 days ago but I cannot do that, so It would be better If anyone share the simple project by using the vue-material to me please. 

I am very new with vue-material.

Thanks,
Phanuwat

**Comment by marcosmoura** [comment]
Hi @Phanu282003.

I will create some examples on Codepen. Will be present on the 0.4.0 release that it's almost done.
Thanks!

**Comment by cschweda** [comment]
+1

Looking forward to the new release. I'm using vue-material for the components but milligram.css for the grid layout. 

Any plans to incorporate the Materialize grid as part of the package? (Or is this something I can drop right in with the Materialize.css? I guess I should try this first -- but I had been using Milligram.)

Thoughts?

**Comment by marcosmoura** [comment]
I don't have plans to integrate with Materialize or any other lib. I will create a grid layout based on flexbox for v0.5.0. Take a look here #78 #35 #23 #93
