### ISSUE TITLE
<md-bottom-bar > is not at the bottom of page

### ISSUE THREAD

**Issue by huobaiyu** [marcosmoura/vue-material#134]
bottom bar is not fixed at the bottom of html page.

### Reproduction Link

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE.

**Comment by marcosmoura** [comment]
Yep. I could provide some classes that would try to align the bottom bar on the bottom of your page but this maybe don't work for all cases. This is kinda responsability of your application for some reasons:
* If we have a class like 'md-absolute', with position absolute the alignment would not work properly depending of you application structure and/or the parent elements position.
* If we have a class like 'md-fixed', with position fixed the alignment would not work properly depending on the parent elements position. If you have a parent element with a transform, for example, the position fixed will not work.

I will develop those classes in the near future, but the css to fix the bottom bar on the bottom of the page should be in your own code.

Thanks.

**Comment by sombriks** [comment]
@huobaiyu i use something like this on my solution, and it might work for you too

```
<!-- baserouter.vue -->
<template>
  <div id="base" v-md-theme="'default'">
    <router-view></router-view>
    <md-bottom-bar class="fixobaixo" md-shift>
      <md-bottom-bar-item md-icon="history" v-on:click="xxxx('#/')">Recents</md-bottom-bar-item>
      <md-bottom-bar-item md-icon="favorite" v-on:click="xxxx('#/x')">Favorites</md-bottom-bar-item>
      <md-bottom-bar-item md-icon="near_me" v-on:click="xxxx('#/y')">Nearby</md-bottom-bar-item>
    </md-bottom-bar>
  </div>
</template>

<script>
  module.exports = {
    name:"BaseRouter",
    methods: {
      xxxx (path){
        window.location.href=path;
      }
    }
  };
</script>

<style>
  .fixobaixo{
    position:fixed;
    bottom:0px;
    right:0px;
  }
</style>
```
