### ISSUE TITLE
Progress bars with data table

### ISSUE THREAD

**Issue by Sarpedion** [marcosmoura/vue-material#135]
Greetings,

while I am aware that progress bars are planned with milestone v0.5.0  (#20), I was wondering if progress bars will also be incluced in some manner with datatables?

To be more precise on what I had on mind, I was thinking of something like shown here:
[Datatable with progress bar](http://codepen.io/anon/pen/BjvLVJ?editors=1010)

Clicking refresh button will start a progress bar beneath header row of a datatable.

Such a small feature would improve visual effect of a table loading large sets of data.
For now, I am using a third party library for progress bars.

**Comment by marcosmoura** [comment]
Yeah. That md-data-table was used as a source of inspiration. So, after the release of progress bars I will add to the table as well.

Thanks!
