### ISSUE TITLE
md-input component has some of the styles but lacks others

### ISSUE THREAD

**Issue by capttrousers** [marcosmoura/vue-material#136]
### Steps to reproduce
Either clone my repo, `npm install` and then `npm run dev` to see the initial page, or just checkout the relevant code as laid out in the "Whats actually happening" section. Theres not much code to get the vue-material module set up and running, its just not working as expected. 

### Which browser?

most recent of each after running npm update, checking on windows and linux, chrome >=v54

### What is expected?
The first text input on the page is just a general input, but the second is the md-input component. It has some of the md styles applied like the text color and highlight color, but the input label does not behave like the vue-md examples. the label doesnt appear above the input with a nice transition like expected, it just sits to the left of the input.

### What is actually happening?
I dont know, it's possible I missed a set up step, so you can view the repo here:
https://github.com/capttrousers/quickdata/tree/store
(branch store)
The files in question are in the src/ directory, so src/main.js has the import vue-material module and css and set the theme, and then src/app.js starting on line 25: (https://github.com/capttrousers/quickdata/blob/store/src/app.vue#L25) has the `md-input` and container components. 
In the Elements tab of chrome dev tools it looks like the input is registered correctly with the right css classes, and I believe that the importing of the vue-material.css file is working as well because I think I can find that css in style tags in the head of the html doc. 

### Reproduction Link
https://github.com/capttrousers/quickdata/tree/store

**Comment by marcosmoura** [comment]
Thanks for that such detailed description.
The <md-input> SHOULD be used inside <md-input-container>. The default <input> element of HTML doesn't get ANY css. Only the <md-input> have the style. This should be like that because the <md-input-container> have all the behaviour and classes to toggle input and label states. If you don't want the float labels, you can use the md-inline attribute, like on the documentation example.

**Comment by capttrousers** [comment]
Sorry I dont understand. 

When I put `import 'css!vue-material/dist/vue-material.css';` in my main.js file, and then use webpack to load it all up into the bundle, it looks like it's actually loading that css as simple <style> tags in the <head> of the html doc. But maybe it's not getting all the css or soemthing. What I want is the input label to kinda transition and appear above the input, when the user clicks on the input, and if they click away, the label goes away. the examples work like that but for some reason, in my app, the labels just end up to the left of the input

**Comment by capttrousers** [comment]
Also, im using the pug/jade preprocessor for the vue-loader somehow, so im not sure if that is affecting the vue-material components or not. Do i need to register those components in the parent component to use them? ie, in the app.vue component, do i need to register any of the vue-material components?

**Comment by marcosmoura** [comment]
No. You don't need to do anything different that you already have. Try to link your css file like this:
``` vue
<link rel="stylesheet" href="path/to/vue-material.css">
```

**Comment by capttrousers** [comment]
so that vue-material.css file is the one in the node_modules/vue-material/dist folder correct?
Can i just link it in the index.html file like that, or would I need to mess with the express routing, or possibly copy the vue-material.css file into my own build/ folder that is public?

**Comment by marcosmoura** [comment]
Just link. But on build task you will need to copy.
Can you publish this in a URL? I can check this for you.

**Comment by capttrousers** [comment]
Thanks for the help! 
What should I publish in a URL?

**Comment by marcosmoura** [comment]
You project. It is possible?

**Comment by capttrousers** [comment]
I dont have a public facing server to host it on yet, so I will try a variety of options linking that css file to see if i can get it working, and update here. Thanks!
