### ISSUE TITLE
Ripple can't create on right place

### ISSUE THREAD

**Issue by throrin19** [marcosmoura/vue-material#137]
Hi, I have another problem with the ripple effect.

I add my ripple on my element like your example : 

```vue
<div class="btn-action has-ripple" :class="color" v-md-ink-ripple>
    <md-icon>{{ icon }}</md-icon>
    <md-tooltip
        v-if="tooltip"
        :md-direction="direction || 'right'"
    >{{ tooltip }}</md-tooltip>
</div>
```

Normally, the div `md-ink-ripple` is created in this div but, if I test my element in the navigator, this is the generated ripple : 

```html
<div class="btn-action has-ripple big red" data-v-0d8b6bfe=""><i class="md-icon material-icons">delete</i> </div>
<div class="md-ink-ripple"><div class="md-ripple md-active" style="width: 823px; height: 823px; top: -232.5px; left: -395.5px;"></div></div>
```

In this case, my element is a component i create many times with different parameters in the same div, this is the cause of the bug?

Thanks.

**Comment by marcosmoura** [comment]
The element that received the ripple directive have a position relative? It's not explicit on the documentation (yet) but this needs to implemented.

**Comment by throrin19** [comment]
It's my bad, with the `position : relative` it works fine

**Comment by marcosmoura** [comment]
Oh. Don't worry. Stay tuned. I will release a new version this weekend.
