### ISSUE TITLE
Layout bug in examples

### ISSUE THREAD

**Issue by gudvinr** [marcosmoura/vue-material#140]
### Steps to reproduce

- Go to [example page](https://marcosmoura.github.io/vue-material)
- Open some example with clickable elements (e.g. ripple, buttons)
- Push clickable elements

### Which browser?
Chrome 53.0.2785.143. Ubuntu 16.04 (64-bit)

### What is expected?

Predictable click without abnormal behaviour

### What is actually happening?
See screenshots
![vue-mdl-bug](https://cloud.githubusercontent.com/assets/1712806/20865713/f61f4d02-ba2a-11e6-902b-b29b8069a9d4.png)
![vue-mdl-bug 1](https://cloud.githubusercontent.com/assets/1712806/20865715/f61fd5d8-ba2a-11e6-994b-2ca9b721b206.png)
![vue-mdl-bug 2](https://cloud.githubusercontent.com/assets/1712806/20865714/f61f9fd2-ba2a-11e6-8741-5961a68bd535.png)

**Comment by craigvantonder** [comment]
That default area looks odd, this is what mine looks like:
Chrome 54.0.2840.59. Ubuntu 16.04 (64-bit)

![Screenshot](http://i.imgur.com/DhMDO3d.png)

**Comment by marcosmoura** [comment]
I'm releasing a new documentation website. So this bug will be fixed. Thanks!
