### ISSUE TITLE
md-fixed in sidenav doesn't work 0.4.0

### ISSUE THREAD

**Issue by DevEclipse** [marcosmoura/vue-material#146]
![image](https://cloud.githubusercontent.com/assets/19868205/20874365/1748d89c-baec-11e6-988b-aca184d2cfaa.png)

![image](https://cloud.githubusercontent.com/assets/19868205/20874368/1d3cbf7a-baec-11e6-8e00-f99903b5ca8d.png)

**Comment by marcosmoura** [comment]
Which browser? Have you fully updated VueMaterial?

**Comment by marcosmoura** [comment]
@DevEclipse ping!
