### ISSUE TITLE
new Layout tab demos/code doesn't work in chromium Version 53.0.2785.143 Built on Ubuntu 

### ISSUE THREAD

**Issue by mygnu** [marcosmoura/vue-material#147]
### Steps to reproduce
open domo site in chromium on ubunu
### Which browser?

chromium v53.0.2785 --latest available on ubuntu
### What is expected?
tab data in demo and code tabs to be displayed
### What is actually happening?

![screenshot from 2016-12-05 17 48 59](https://cloud.githubusercontent.com/assets/4723535/20876013/29f48cda-bb13-11e6-9684-7b217bd00e08.png)
works like a charm in Firefox, Chrome on the same machine 
### Reproduction Link

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE.

**Comment by marcosmoura** [comment]
I've found this bug. I fixed and I will release it ASAP.
