### ISSUE TITLE
mdIcon not displaying properly

### ISSUE THREAD

**Issue by GaelS** [marcosmoura/vue-material#15]
Thank you for your excellent package, it's really helpful.

I have a question though. I am unable to get mdIcon working properly. Let's say I want to get a _home_ icon, I just get an uppercased text displaying 'HOME'. The css stylesheet is functionnal since I use other components from your package.

What am I missing ?
Thank you for your help !

**Comment by marcosmoura** [comment]
Well. Maybe on the documentation I wasn't clear enough, but you'll need to include in you index file the Google Icons stylesheets. I have plans to support svg icons but for now it's only work with fonts. 
What you need to do it's to only include this link in the ```head``` of your index file:
```html <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">```

**Comment by GaelS** [comment]
Awesome, thanks ! 
Documentation could indeed be improved on that point ;)

**Comment by pedroramostracker** [comment]
i still don't understand, i've imported VueMaterial from 'vue-material' with all modules, why it still needs the font?

**Comment by Malavos** [comment]
@pedroramostracker  I know this is a old question, but let me answer you.

The component itself is there, all right.
But the Icons thenselves, the "images", are not. They come from that url that was posted by marcosmoura.

Just import it into your project, in any way you see fit, and let it rip.
