### ISSUE TITLE
Chips

### ISSUE THREAD

**Issue by Morgul** [marcosmoura/vue-material#152]
Chips represent complex entities in small blocks, such as a contact.

Specs for [Chips](https://material.google.com/components/chips.html)

![Chips](https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VV21LOUp1OGdrRTg/components_acux_chips_chipstxticon.png)
![Chips](https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VM1VORGxxWUx5U0E/components_chips.png)

**Comment by Morgul** [comment]
Just to give my use case here: I have need to adding arbitrary, user defined tags to an object, and then being able to filter by those tags later. The chips component feels like a perfect fit for this.

I might look at contributing this component myself, if it ends up blocking my project, but I'm unsure if you would want an `<input type="text">` to back it, or just a straight implementation with a `<div>`. There's tradeoffs to either, with the div being less accessible to screen readers, etc.

**Comment by marcosmoura** [comment]
Hi @Morgul 

Thanks for the suggestion. I would love to see a PR related to the md-chips components. But first we have to discuss I little bit of the API.
I was thinking here that the API could be something like that:
``` vue
<md-chips :v-model="VARIABLE">
<md-chip :md-deletable="VARIABLE" @delete="METHOD" @click="METHOD">
```

#### md-chips - Properties
| Name             | Type        | Description                                       |
| ------------   |:---------:| ----------------------------------:|
| v-model         | Array        | The model with the set of chips     |

#### md-chip - Properties
| Name              | Type        | Description                                       |
| ------------    |:---------:| ----------------------------------:|
| md-deletable  | Boolean  | If the chip should be deletable        |

#### md-chip - Events
| Name             | Value        | Description                                        |
| ------------   |:---------:| -----------------------------------:|
| delete            | None        | Triggered when the chip is deleted  |
| click               | None        | Triggered when the chip is clicked  |

The idea, to add and remove chips, is something like:
``` vue
<md-chips :v-model="myChips">
  <md-chip md-deletable>johndoe@gmail.com</md-chip>
  <md-chip md-deletable>janedoe@gmail.com</md-chip>
  <md-chip md-deletable>johncena@wwe.com</md-chip>
</md-chips>
```

And if you want to render only a single chip, to show static info:
``` vue
<md-chip>johndoe@gmail.com</md-chip>
<md-chip>janedoe@gmail.com</md-chip>
<md-chip>johncena@wwe.com</md-chip>
```

What do you think about this proposal?

**Comment by Morgul** [comment]
@marcosmoura I like that proposal. It should cover most of the use cases I can think of. I'll have to learn the new scoped slots, but from a quick read through, the seem to fit the use case well. 

I probably won't be starting to work on this for the next week, we'll see. If you haven't seen a PR from me yet, and you want to implement this, ping me here, and I'll let you know if I've gotten anywhere. Definitely don't want to hold anything up. :)

**Comment by marcosmoura** [comment]
Oh. That's really great! I want to release it on the [v0.6.0](https://github.com/marcosmoura/vue-material/milestone/7) which is scheduled for January 7!

If you want send me an email and we can discuss further.

Thank you!

**Comment by vuchl** [comment]
Since you made a spec allready I could implement it today if you want

**Comment by Morgul** [comment]
@vuchl If you're ready right now, go for it! I'm still several days out from having the time.

**Comment by vuchl** [comment]
will see if I can squash it out over the ourse of the day. depends how much load work is

**Comment by marcosmoura** [comment]
Hi Guys. Of course. You can start today, tomorrow, 7 days from now. Don't worry. :D

**Comment by vuchl** [comment]
i started today but got a bit into trouble. especially with the SASS Part. will share a repo later

**Comment by marcosmoura** [comment]
Already in progress!

**Comment by smith64fx** [comment]
The chips were merged. After that the merge was reverted. Is there a reason for this?

**Comment by pytsekas** [comment]
why it is not possible to use md-click method with md-chip?
md-chips has md-click method

**Comment by zeroarst** [comment]
Same here...md-click does not seem to work...?
