### ISSUE TITLE
Ripple lag on v-if large statement

### ISSUE THREAD

**Issue by throrin19** [marcosmoura/vue-material#153]
I've test to render in a basic html tab 1k of data rows whith a button whith the `v-md-ink-ripple` on it and this is the result in chrome timeline : 

![capture du 2016-12-05 16-24-47](https://cloud.githubusercontent.com/assets/1394778/20890574/a11b32a2-bb07-11e6-9006-0d3782fb3dde.png)

All purple/red parts is the render of the `v-md-ink-ripple` on each tab line. If I remove the `v-md-ink-ripple`, this is the result : 

![capture du 2016-12-05 16-25-43](https://cloud.githubusercontent.com/assets/1394778/20890609/c2fee526-bb07-11e6-9b48-45a6913ff7f0.png)

The render of each line has a big freeze in chrome (between 2-5s). 

this is the code of the line part in my template : 

```vue
<tr v-for="user in getUsers" v-on:click="editUser(user)">
    <td>{{ user.firstname + ' ' + user.lastname }}</td>
    <td>{{ user.job }}</td>
    <td class="actions">
        <btn-action icon="delete" color="hover-red" tooltip="Supprimer" direction="left"></btn-action>
    </td>
</tr>
```

and this is the code of my btnAction.vue :

```vue
<template>
    <div class="btn-action has-ripple" :class="color">
        <md-icon>{{ icon }}</md-icon>
        <md-tooltip
            v-if="tooltip"
            :md-direction="direction || 'right'"
        >{{ tooltip }}</md-tooltip>
    </div>
</template>

<script>
    export default {
        name  : 'btn-action',
        props : {
            tooltip     : String,
            direction   : String,
            icon        : {
                type        : String,
                required    : true
            },
            color : {
                type        : String,
                required    : true
            }
        }
    };
</script>
```

The problems come from the `createRipple` function with this part of code : 

```javascript
let elementSize = Math.round(Math.max(holder.offsetWidth, holder.offsetHeight)) + 'px';
```

**Comment by marcosmoura** [comment]
Hi @throrin19 

Yep. I know. The ripple code is not that good. I will recreate the ripple from scratch with performance in mind. Also I will drop the support for ripple directive in the near future. For your use case, I don't have a good workaround (for now). What you can do is:

* Create a custom button:
Instead of `<md-button>` component, you can use a custom buttom with the md-button class
``` vue
<button type="button" class="md-button md-primary">My text</button>
```

* Defer the ripple creation by adding a disbled attribute:
The ripple is rendered only if the button is no disabled, so you can defer his creation with something like that:
``` vue
<md-button class="md-button md-primary" :disabled="deferDisabled">My text</md-button>
```
```javascript
data: () => ({
  deferDisabled: true
}),
mounted() {
  this.$nextTick(() => {
    window.setTimeout(() => {
      this.deferDisabled = false
    }, 50)
  })
}
```

Sorry for the inconvenience. :(

**Comment by throrin19** [comment]
Have you try to use another ripple like this ? https://github.com/surmon-china/vue-touch-ripple

After test in my app, this is the result with my large list : 

![capture du 2016-12-06 09-20-29](https://cloud.githubusercontent.com/assets/1394778/20918038/57affa9c-bb95-11e6-8a5f-c14fcc781c79.png)

I think, if you have no time to rewrite and optimize your ripple, the best way is to use anoter ripple. 

In this case, the solution, is to make your ripple optional in the project and let developers use their chosen ripple library.

**Comment by marcosmoura** [comment]
I will develop a new ripple component and add a configuration to disable it.
