### ISSUE TITLE
Switch problem

### ISSUE THREAD

**Issue by jeimz143** [marcosmoura/vue-material#157]
### Reproduction Link

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE. 

hi bro there is a problem with the switch page on your website and i cant review the code snippet.
https://vuematerial.github.io/#/components/switch. since i cant review the code, i tried to use the lower version switch but the problem is, The  switch was disabled. i just follow the instruction. please reply asap thanks :)

**Comment by jeimz143** [comment]
hi bro there is a problem with the switch page on your website and i cant review the code snippet.
https://vuematerial.github.io/#/components/switch. since i cant review the code, i tried to use the lower version switch but the problem is, The  switch was disabled. i just follow the instruction. please reply asap thanks :)

**Comment by marcosmoura** [comment]
Uh. Sorry about that. I will fixx this ASAP. Some examples:
``` vue
<md-switch v-model="checked0" id="my-test0" name="my-test0"></md-switch>
<md-switch v-model="checked1" id="my-test1" name="my-test1" class="md-primary">Primary Color</md-switch>
<md-switch v-model="checked2" id="my-test2" name="my-test2" class="md-warn">Warn Color</md-switch>
<md-switch v-model="checked3" id="my-test3" name="my-test3" disabled>Disabled</md-switch>
```

**Comment by ragamuffinguil** [comment]
Hi dude same issue here, using the code above. Do we need to code something for it to work? the  switch button is always disabled.

**Comment by marcosmoura** [comment]
Do you have the v-model variable in your data/computed? Are you running your code in which env? Browserify? Webpack? Another tool? Standalone? Which browser? Can you put part of your code on Codepen/JSBin?

**Comment by jeimz143** [comment]
@ragamuffinguil  try to add a value on your data/computed bro. :)

**Comment by ragamuffinguil** [comment]
Yehey it works, thanks @jeimz143

**Comment by marcosmoura** [comment]
@ragamuffinguil Did the data/computed thing worked for you? Do you have some suggestions to make the docs better? Can I close this issue?

**Comment by marcosmoura** [comment]
Wow. You've commented first! Great! If something come up let me know! Thanks!
