### ISSUE TITLE
big data in dialog content

### ISSUE THREAD

**Issue by thoss** [marcosmoura/vue-material#161]
Hi,

I have a md-table in md-dialog element, if there is a huge amount of rows the content will be cut off and it is not possible to scroll

[Image](https://pl.vc/zopzp)

Tested with Google Chrome in v54

I will make a codepen if the latest version is supported.

**Comment by marcosmoura** [comment]
I will check this ASAP.

**Comment by thoss** [comment]
Thanks for the quick implementation!

2016-12-08 12:44 GMT+01:00 Marcos Moura <notifications@github.com>:
