### ISSUE TITLE
Dialog applies backdrop to itself

### ISSUE THREAD

**Issue by Sarpedion** [marcosmoura/vue-material#162]
Greetings,

I am using the same code as provided in documentation (for custom dialog). When I open dialog, it applies backdrop to itself. Tested on Chrome Version 55.0.2883.75 m
By that I mean that it looks like:

![image](https://cloud.githubusercontent.com/assets/16826299/20926325/06470d4a-bbbc-11e6-8066-ef7f65f6bc81.png)

My current workaround is that I apply custom css style to dialog.

CSS:
```
.dialog-fix {
  .md-dialog {
    background: #fff;
  }
}
```

HTML:
```
<md-dialog md-open-from="#custom" md-close-to="#custom" ref="dialog1" class="dialog-fix">
...
</md-dialog>
```

Also, I'd like to use this chance to thank you for the great job you are doing on this project :)

**Comment by marcosmoura** [comment]
This is strange. Are you using the theme correctly?

**Comment by Sarpedion** [comment]
It seems I have been applying it wrongly the whole time, although this is first time I had issue with it:

The way I was applying it was:

```
<div class="container" >
    <first-component ref="sidenav" v-md-theme="'firstTheme'"></first-component>

    <first-component v-md-theme="'secondTheme'"></first-component>

    <div class="content" v-md-theme="'thirdTheme'">
        <router-view></router-view>
    </div>
</div>
```

When I applied theme to the wrapping div, it worked fine:

```
<div class="container"  v-md-theme="'firstTheme'" >
    <first-component ref="sidenav"></first-component>

    <first-component></first-component>

    <div class="content">
        <router-view></router-view>
    </div>
</div>
```

Sorry for bothering you with this issue

**Comment by marcosmoura** [comment]
@Sarpedion Don't worry. I will make some improvements over themes in the nexts versions, so issues like that will be fixed.
