### ISSUE TITLE
mdTablePagination - No way to know if next page or prev page?

### ISSUE THREAD

**Issue by petarjs** [marcosmoura/vue-material#163]
mdTablePagination emits `pagination` and `page` events, but there's no way to know if we should move to the next page or the previous page (unless I'm missing something?).

Here's the code responsible for that:
https://github.com/marcosmoura/vue-material/blob/master/src/components/mdTable/mdTablePagination.vue#L73

The same method is called regardless of if it's the next or the previous button that has been pressed.

This could be fixed by passing an argument to that method [here](https://github.com/marcosmoura/vue-material/blob/master/src/components/mdTable/mdTablePagination.vue#L15) and [here](https://github.com/marcosmoura/vue-material/blob/master/src/components/mdTable/mdTablePagination.vue#L11).

I can create a pull request to implement this if that's okay?

**Comment by jonataswalker** [comment]
I'm exactly in the same situation.

**Comment by marcosmoura** [comment]
I will focus on improvements over pagination. I will fix this for the very next version. Sorry about that. Thanks!

**Comment by petarslovic** [comment]
Awesome, thanks!

**Comment by jonataswalker** [comment]
I've tested some modification locally and this was enough:

```javascript
      previousPage() {
        if (this.canFireEvents) {
          this.currentPage--;
          this.$emit('page', this.currentPage);
          this.emitPaginationEvent();
        }
      },
      nextPage() {
        if (this.canFireEvents) {
          this.currentPage++;
          this.$emit('page', this.currentPage);
          this.emitPaginationEvent();
        }
      }
```

**Comment by jonataswalker** [comment]
There's more:

```jsx
<span>{{ ((currentPage - 1) * currentSize) + 1 }}-{{ currentSize * currentPage }} {{ mdSeparator }} {{ mdTotal }}</span>
```

**Comment by marcosmoura** [comment]
@jonataswalker Great! Can you create this as a PR? :D

**Comment by petarjs** [comment]
@jonataswalker Just watch when incrementing / decrementing currentPage, so it doesn't go below 0 or above total number of items :)

**Comment by jonataswalker** [comment]
@petarjs Yes, for sure, I'll handle it.

@marcosmoura The PR is on the way.
