### ISSUE TITLE
md-tabs doesn't trigger @change event

### ISSUE THREAD

**Issue by jtouzy** [marcosmoura/vue-material#168]
In the docs, md-tabs seems to trigger "change" event when a tab is changed:

![image](https://cloud.githubusercontent.com/assets/5709133/20960682/e08c46d2-bc61-11e6-8efd-5780d5b973e8.png)

But no event is triggered in mdTabs.vue

I can send a pull request to correct it. I think this is just a missing $emit() in the setActivateTab() method (forked project with correction works : event is triggered in md-tabs initialization and in each tab change).

What do you think ?

**Comment by marcosmoura** [comment]
Yeah. The tabs have been recreated on the latest version, and I think that I missed this event. Sorry about that. I would love to see a PR with this change. Thanks.

**Comment by jtouzy** [comment]
The PR : #167
