### ISSUE TITLE
md-whiteframe

### ISSUE THREAD

**Issue by throrin19** [marcosmoura/vue-material#169]
Hi, It's possible to remove the specific design of the md-whiteframe ? 

```
position: relative;
z-index: 1; 
```

In my case, I use the whiteframe for an absolute element and this rules broke my design.

Otherwise, instead of having to create an element, why not go through a directive that adds depth-specific design to the element that uses it ?

Like this : 

```
<div md-elevation="2"></div>
```

**Comment by marcosmoura** [comment]
Yeah. I think will be better to remove this z-index. Although it can be overwritten in your use case. 
I don't like the idea of having a directive, but maybe I can change the component to pass another property called "md-tag". In this case you can pass any tag name that you want and the whiteframe will render it.

**Comment by throrin19** [comment]
the whiteframe has still this design in the last version (`0.4.1`) : 

```
.md-whiteframe {
    position: relative;
    z-index: 1;
}
```

In my elements i should use the `!important` flag but it's not the best slution

**Comment by marcosmoura** [comment]
You don't need `!important`. You can add a class to the element that you want and the apply your z-index.
