### ISSUE TITLE
Vue-material + Laravel gulpfile

### ISSUE THREAD

**Issue by sldobri** [marcosmoura/vue-material#17]
I saw that u use laravel, and I wonder compile the components using gulpfile is possible ??
I would love to use the vue material into a new project I'm implementing.

**Comment by marcosmoura** [comment]
Well. You can use gulp with Vue Material. It's totally fine and easy. You can use the standalone build and include the ```vue-material.js``` in your HTML or use some other tools like babel or browserify to import the library directly inside your js code. This second option is the best because you can have more control of your dependencies.
If you want to build new components, contribute or change something in a fork you still can use gulp, but you have to setup webpack as well. This project need some loaders that only webpack can achieve without change the source code.

What is your environment? Are you using Laravel Elixir to compile the assets?

**Comment by sldobri** [comment]
I use macOS Sierra with, Laravel 5.3 and to compile the assets Elixir in my gulpfile.

**Comment by echr** [comment]
@sldobri just follow the instruction at [Getting Started](https://marcosmoura.github.io/vue-material/#/getting-started) , simply npm install all required dependency...
if you having trouble with the `import 'vue-material/dist/vue-material.css'` or want to combine the `vue-material.css` with your own css, you can edit your **gulp** file in elixir function and add `mix.copy('node_modules/vue-material/dist/vue-material.css', 'resources/assets/sass/material.scss');`

**Comment by sldobri** [comment]
@echr  my laravel files:
``` package.json
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "dependencies": {
    "autosize": "^3.0.17",
    "element.scrollintoviewifneeded-polyfill": "^1.0.1",
    "node-sass": "^3.10.1",
    "scopedQuerySelectorShim": "github:lazd/scopedQuerySelectorShim",
    "stream-browserify": "^2.0.1",
    "vue": "^2.0.2",
    "vue-material": "^0.1.2",
    "webpack": "^1.13.2"
  },
  "devDependencies": {
    "autoprefixer": "^6.5.0",
    "babel-core": "^6.17.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "bootstrap-sass": "^3.3.7",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^3.0.1",
    "css-loader": "^0.25.0",
    "eslint": "^3.7.1",
    "eslint-friendly-formatter": "^2.0.6",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-html": "^1.5.3",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "gulp": "^3.9.1",
    "highlight.js": "^9.7.0",
    "html-webpack-plugin": "^2.22.0",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-11",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.16.2",
    "node-sass": "^3.10.1",
    "ora": "^0.3.0",
    "raw-loader": "^0.5.1",
    "sass-loader": "^4.0.2",
    "vue-hot-reload-api": "^2.0.6",
    "vue-html-loader": "^1.2.3",
    "vue-loader": "^9.5.1",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.1",
    "vue-style-loader": "^1.0.0",
    "vue-template-compiler": "^2.0.1",
    "webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.8.4",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1"
  }
}
```

``` gulpfile.js
const elixir = require('laravel-elixir');
require('laravel-elixir-vue-2');

elixir(mix => {
    mix.webpack('app.js');
});
```

``` app.js
import Vue from 'vue'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'

Vue.use(VueMaterial)

const app = new Vue({
    el: '#app'
});
```

``` welcome.blade.php
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>Theme Example</title>
  </head>
  <body>

    <div id="app">

      <md-toolbar>
        <h1 class="md-title">My Title</h1>
      </md-toolbar>

      <md-button class="md-primary">Primary Button</md-button>

    </div>

    <script src='/js/stories.js'></script>
  </body>
</html>
```

**Comment by iraklisg** [comment]
following @echr advice, I still get the following error when runing `gulp`

> Error: ./~/vue-material/dist/vue-material.js│Module build failed: SyntaxError: 'with' in strict mode (8:13503)
