### ISSUE TITLE
Question: getInViewPosition scroll position

### ISSUE THREAD

**Issue by VicarEscaped** [marcosmoura/vue-material#172]
Hi!
I have a question: does in getInViewPosition.js in position calculation included scroll position?
I have run into bag, than i have multiple menu/select components on page dropdown top position does not calculated properly.

**Comment by marcosmoura** [comment]
Hi @VicarEscaped 
Can you add a example on Codepen?
Thanks!

**Comment by VicarEscaped** [comment]
Sorry for delay.
I can't reproduce this issue on codepen (there it works like a charm). I report then i can reproduce it. But for now we can close this issue.

**Comment by VicarEscaped** [comment]
I've dig into problem and, i think, i've found that caused issue.
When in [getInViewPosition.js](https://github.com/marcosmoura/vue-material/blob/master/src/core/utils/getInViewPosition.js#L8) calculating element positioning in viewport, calculation depends on window.innerHeight. And if there is a large content (7000px in my case), select dropdown will display always at top of page, beacuse in getInViewPosition.js does not include window.scrollY or window.pageYOffset, like it does in angular's [version](https://github.com/angular/material/blob/master/src/core/util/util.js#L154)

**Comment by VicarEscaped** [comment]
probably #175 fix this
