### ISSUE TITLE
Input's name attribute is not set

### ISSUE THREAD

**Issue by DmitrySkripkin** [marcosmoura/vue-material#174]
When I do that
```
<md-input-container>
   <label>First name</label>
   <md-input v-model="firstName" type="text" name="firstName"></md-input>
</md-input-container>
```
I expect to have name attribute to be set for input created. I can see this behaviour for type, disabled, placeholder and others attrs.

My usecase was to use https://github.com/logaretm/vee-validate for validation. But name attr is required for it.

**Comment by marcosmoura** [comment]
The name attribute is applying, as you can see here on [Codepen](https://codepen.io/vue-material/pen/ZBRoaw/).

**Comment by DmitrySkripkin** [comment]
Sorry, you are right. Name attr is ok, no idea how I lose it. Something is wrong when I try to use it with vee-validate, but that's anouther issue. Next time I'll check everything before creating an issue.
BTW thanks for updates.

**Comment by DmitrySkripkin** [comment]
But funny thing is that I have fix for it. But since I don't understand the problem I'm confused.
Here is the fix I did:
https://github.com/DmitrySkripkin/vue-material/commit/a36ddff1c354f2fd66f686b91928f0d3047f0d67
I'll add Copepen in a few minutes to show the problem I run into.

**Comment by DmitrySkripkin** [comment]
If you change something you'll see vee-validate errors below the input. And `filed: null` that's the problem. Works fine with plain html input. Or with fix I mentioned before.
https://codepen.io/DmitrySkripkin/pen/BQVqYM

**Comment by throrin19** [comment]
To run vee-validate with the vue-materials forms compoents, you should add the ` data-vv-name` attribute. I see this attribute in this issue on problems between vee-validate and custom form components : https://github.com/logaretm/vee-validate/issues/118#issuecomment-261817224.

In my project, the code works fine whith this options : 

```
<md-input data-vv-name="firstname" v-model="user.firstname" v-validate data-vv-rules="required"></md-input>
```

**Comment by tsunamilx** [comment]
The name attribute is not set in my case, as I see in the source, there is no name attribute is applied.

Source from the latest master (#c8a6445768a1028512c04a0760ca77ac4d5c8abc)
```html
<template>
  <input
    class="md-input"
    :type="type"
    :value="value"
    :disabled="disabled"
    :required="required"
    :placeholder="placeholder"
    :maxlength="maxlength"
    :readonly="readonly"
    @focus="onFocus"
    @blur="onBlur"
    @input="onInput"
    @keydown.up="onInput"
    @keydown.down="onInput">
</template>
```
