### ISSUE TITLE
@blur v-on:blur not working on md-input and @change don't fire if change from somewhere else

### ISSUE THREAD

**Issue by delueg** [marcosmoura/vue-material#177]
Hello,

i can't make it work to trigger something "onblur"-event.

And the @change event (the only one is working for me) don't fire if the v-model gets a change from somewhere else.

see here https://jsfiddle.net/delueg/mrmdo8y5/1/

Can somebody help me?

**Comment by marcosmoura** [comment]
To fire native events in custom compontens you should use `.native` modifier:
`v-on:blur.native` or `@blur.native`

**Comment by delueg** [comment]
Oh ok thanks. And about the @change "issue"

**Comment by ChenZerong** [comment]
@delueg you can use `.native` modifier on `@change` : 
`v-on:change.native` or `@change.native`  it's work for me.

**Comment by ChenZerong** [comment]
Because the `@change` is a custom events by `<md-input>`, look here [source](https://github.com/marcosmoura/vue-material/blob/master/src/components/mdInputContainer/common.js#L55).
