### ISSUE TITLE
drag and drop with sortablejs

### ISSUE THREAD

**Issue by thoss** [marcosmoura/vue-material#179]
Hi,

I have tried to implement sortablejs within a md-list but it is not working with md- elements.
Is there any workaround to use such an sortable framework?
Are there plans to implement drag and drop ?

Thank you

**Comment by marcosmoura** [comment]
Hi @thoss.

I didn't try anything like that, so I don't have a workaround for now. But I have plans to create the sortable list. 

Thanks!
