### ISSUE TITLE
md-table issues

### ISSUE THREAD

**Issue by lzuccaro** [marcosmoura/vue-material#181]
Hi,
I'm experiencing some issues with the md-table component. 

1. The pagination ignores the 'md-total' prop, showing the value of Number.MAX_SAFE_INTEGER as total items.

2. Sorting doesn't work anymore.

Thanks for your support.

**Comment by marcosmoura** [comment]
Hi @lzuccaro.

I will take a look at the pagination thing. Regarding sorting I'm using and testing constantly and I didn't have problems with it. Can you provide a Codepen example with this bug?

**Comment by jtouzy** [comment]
I get into the sorted issue too, directly on the demo website:

First sort:
<img width="513" alt="capture d ecran 2016-12-12 a 08 07 53" src="https://cloud.githubusercontent.com/assets/5709133/21090779/4fd92eea-c042-11e6-8b0a-ccd018af3865.png">

Second sort:
<img width="507" alt="capture d ecran 2016-12-12 a 08 08 04" src="https://cloud.githubusercontent.com/assets/5709133/21090780/4fda8948-c042-11e6-802a-e6d460e7248a.png">

No changes in the table except the borders re-render.
I'm in Google Chrome 54.0.2840.98 (64-bit) in macOS Sierra.

**Comment by marcosmoura** [comment]
I think I wasn't clear enough on the documentation example, but the sort don't do anything there. The sort functionality ONLY fire a event to when a user clicks on the `md-table-head`. I will change the documentation with better examples.

**Comment by lzuccaro** [comment]
Thanks for the clarification.
With regard to the pagination issue here is what I see.

![screenshot from 2016-12-12 09-04-38](https://cloud.githubusercontent.com/assets/16936064/21092030/44961252-c04a-11e6-8224-bd2c36d8c86e.png)

**Comment by marcosmoura** [comment]
Uh. Sorry about that. I will fix this ASAP for the next version. The workaround for now is to pass the 'md-total' with a valid number or text.
