### ISSUE TITLE
Question: Adding transition to card

### ISSUE THREAD

**Issue by Sarpedion** [marcosmoura/vue-material#182]
Greetings,

I am not quite sure if this is a right place to ask such a question, but is there any way to add a transition to card whose content is dynamically changing?
 To be more specific, I have a card that has a table content in it, and when I use paging to show more rows, rows just snap into a place without transition, while I would like to see a transition.

I've prepared a codepen that shows a card that has a table that doesn't use transition on content resize:
[Without transition](http://codepen.io/Sarpedion/pen/GNBbxa)

On the other hand, here is a codepen, with tabs content, where card actually does use a transition when content resize occurs. I have no idea why there is a transition here.
[With transition](http://codepen.io/Sarpedion/pen/oYMrQQ)

Thank you for your time

**Comment by marcosmoura** [comment]
The transition here is due to tabs component. The tabs automatically calculate the height of his active tab and create this transition. On the date you can also create a transition but you need to do it by hand. Here is how:
https://vuejs.org/v2/guide/transitions.html

Thanks.

**Comment by Sarpedion** [comment]
Oh thank you. I will try to implement it myself, thanks for the tip.
Closing now
