### ISSUE TITLE
Populating input values within custom dialog closes the dialog?

### ISSUE THREAD

**Issue by craigvantonder** [marcosmoura/vue-material#183]
I wanted to try make a simple form inside of the new custom dialog and it is looking good so far but I have one problem, if I enter input into any of the input fields then it will close the dialog.

I was able to reproduce the issue in a simple fiddle: http://codepen.io/craigvantonder/pen/dOjBeg

Still trying to figure out what is triggering the event to close the modal. Any ideas on how I could solve this?

**Comment by marcosmoura** [comment]
Oh. That's crazy. Hahaha. I will check this ASAP. Thank you.

**Comment by strothj** [comment]
I'm also running into this problem. For me it's with a normal dialog prompt. I'm getting the same DOM child error in the console.
