### ISSUE TITLE
Dialog in the document in the Android system WeChat and uc browser to display the error

### ISSUE THREAD

**Issue by stevieyu** [marcosmoura/vue-material#184]
https://vuematerial.github.io/#/components/dialog

![kapture 2016-12-11 at 20 06 18](https://cloud.githubusercontent.com/assets/8325201/21080402/f8b3577a-bfe8-11e6-821c-feef76ae9cd7.gif)

video link https://drive.google.com/open?id=0B1x81UAQyNzkQ3h2Q1BoeG5GWW8

**Comment by marcosmoura** [comment]
Hi @stevieyu 

When this happens? Can you provide a detailed description?
Thanks!

**Comment by stevieyu** [comment]
1. Find Android
2. Download WeChat or UC, recommended download UC
3. Open the https://vuematerial.github.io/#/components/dialog with WeChat or UC

WeChat apk download link https://play.google.com/store/apps/details?id=com.tencent.mm
UC apk download link https://play.google.com/store/apps/details?id=com.UCMobile.intl

These two software use more people in China,

**Comment by marcosmoura** [comment]
Hi @stevieyu 

I will try to check the docs in UC Browser, but this project do not aim to support it. I will close this issue and reopen if something changes.
Thanks.

**Comment by stevieyu** [comment]
@marcosmoura macOS 10.12.2 Safari 10.0.2 This also occurs
![kapture 2017-01-06 at 22 12 14](https://cloud.githubusercontent.com/assets/8325201/21720299/3e98768e-d45d-11e6-8180-265aa3d3628c.gif)

**Comment by baddbrain** [comment]
Setting a `flex-basis` value fixes this for me:
`
.md-dialog-content {
    flex-basis: auto;
}
`
