### ISSUE TITLE
Please add documentation for webpack 2

### ISSUE THREAD

**Issue by kristianmandrup** [marcosmoura/vue-material#187]
Trying to grog [css-loader](https://github.com/webpack/css-loader) but rather confusing

```js
  module: {
    loaders: [  
  {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.css$/,
        loader: 'css'
      }
  }
}
```

The `vue` loader works, but in the css-loader docs it says to use the full `css-loader` name? 
What is the correct way? I hate having to go through so many docs and trial and error in order to make a a few libs work together. Please help us having to go through all this trouble. 
Thanks.

**Comment by kristianmandrup** [comment]
I keep getting this error:

```
ERROR in ./~/vue-material/dist/components/mdToolbar/index.css
Module parse failed: /Users/kristianmandrup/repos/react-vue2-apollo/node_modules/vue-material/dist/components/mdToolbar/index.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
```

Fuck!

**Comment by marcosmoura** [comment]
Hi @kristianmandrup 

I can't check that. This is a Webpack 2 issue.
Try to change in the webpack config:
``` javascript
{
  test: /\.css$/,
  loader: 'css-loader'
}
```

Thanks!
