### ISSUE TITLE
Separated html file for custom dialog

### ISSUE THREAD

**Issue by huhk-sysu** [marcosmoura/vue-material#191]
By far, it seems that we have two ways to define the content of a dialog:
- Use the `md-dialog` directive and directly write html code in it.
- Use predefined dialog with `md-content-html`.
 
For the first solution, it would be hard to manage the content when the html code grows bigger and bigger. Especially, when we have several dialog with full content, the whole html code for the page would be in a mess.

For the second solution, it makes the code cleaner since it separates the dialog code with the page code. However, it's also inconvenient to write html code in the form of string, even with the help of **template string** in ES6.

Is it possible to write the html code for the dialog in another separated file and then reference it?

**Comment by marcosmoura** [comment]
Well. The first approach is the best one. You can write your own html in html/vue files. The second one is designed to output simple html content, like bold text. And you will miss the flexibility of writing your own markup. 

If your html is getting bigger then you should think about splitting your application in small components. Maybe your dialog can be a component. 

But if you still want to load a html from another file, to output in md-content-html, you can use webpack with the raw-loader. And notice that this it's not gonna load your file asynchronously. 

Thanks.
