### ISSUE TITLE
Material Themes, "hue" property don't work with accent/warn 

### ISSUE THREAD

**Issue by lhas** [marcosmoura/vue-material#193]
It only works with primary.

### Reproduction Link

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE.

**Comment by marcosmoura** [comment]
Hi @lhas 

I will check this. In my tests I didn't face this problem. The 0.4.0 version will come with an improved theme engine.

**Comment by marcosmoura** [comment]
@lhas ping!
