### ISSUE TITLE
[Question] Using vue-router definition in <md-list-item>

### ISSUE THREAD

**Issue by rslhdyt** [marcosmoura/vue-material#194]
I have installed this awesome `vue-material` in my vuejs project, also I use `vue-router` to manage app routing. In component list I want use `<router-link>` as `<md-list-item>` instead of using url properties in `<md-list-item url="URL">`. 

this is posible and how can I implement it?

**Comment by fusion44** [comment]
To my knowledge it is not possible at the moment. As a workaround I use Javascript routing like this:


`<md-button @click="onSignIn">Sign In</md-button>`


``` javascript
methods: {
  onSignIn() {
    this.$router.push({name: 'login'}); 
  }
}
```

**Comment by marcosmoura** [comment]
The @Sarpedion solution is the way to achieve that. The Vue Material documentation use this approach.

Thanks!

**Comment by rslhdyt** [comment]
@Sarpedion actualy I've try like your example. but more simple.

````
<md-list-item>
  <router-link exact to="/changelog">My Profile</router-link>
</md-list-item>
````
but unfortunately it is not working.

I'll use @fusion44 solutions, because I need a callback after page is reloaded.

Thank You All

**Comment by marcosmoura** [comment]
The @fusion44 methos works, but dont let users to open the link in another tab.
I'm using this in the documentation Website:
``` vue
<md-list-item>
  <router-link exact to="/">Introduction</router-link>
</md-list-item>
```

**Comment by rslhdyt** [comment]
> The @fusion44 methos works, but dont let users to open the link in another tab.

Noted! @marcosmoura
