### ISSUE TITLE
md-button-toggle unexpected behavior

### ISSUE THREAD

**Issue by capttrousers** [marcosmoura/vue-material#195]
#22 

### What is expected?
initial data test should be false, meaning md-toggle is not applied initially but after clicked it is.

### What is actually happening?
the class binding is behaving opposite of expected, when test is true, md-toggle is not applied, and vice versa

### Reproduction Link
http://codepen.io/anon/pen/mOzpyo

**Comment by capttrousers** [comment]
Repro'd in codepen link above. 

Hierarchy data value is 'none' thus the isParent method should return false initially, thus the md-toggle class should not be applied initially, but it is applied

**Comment by capttrousers** [comment]
I dunno if this is an issue with the class binding of vue.js or with the md-toggle button / class itself. Or maybe it's just the opposite because the md-toggle class means the button is "off" so to speak

**Comment by marcosmoura** [comment]
I've found the problem. Your logic is almost correct.
When you are using a method to check something on your HTML you should **always** call it as a function:
``` vue
<md-button @click="toggleHierarchy" :class="{ 'md-toggle': isParent() }">
```
To omit the parenthesis you can create a computed property, so you'll be able to use `isParent` like a variable:
``` vue
<md-button @click="toggleHierarchy" :class="{ 'md-toggle': isParent }">
```

Thank you!

**Comment by capttrousers** [comment]
Thanks for the clarification.
So I tried both ways, either with that md-toggle class check switched to a computed property and no `()` and as a method with the `()` and neither seem to work. 
Repro steps with computed prop:
1. http://codepen.io/anon/pen/yVRKQe
2. hierarchy starts as 'none', demonstrated in the text below the button, button is not highlighted, and does not have the md-toggle class, verified by inspecting the element in chrome dev tools
3. click the toggle button once, text below button changes to 'parent', but toggle button stays unhighlighted and does not have the md-toggle class
4. click the toggle button one more time, button toggles, is highlighted, and has the md-toggle class, and the text below also changed and says hierarchy == 'none'

**Comment by marcosmoura** [comment]
You only need to set the md-toggle class if you want to highlight when the page opens! So basically you don't need to change the class when the user clicks on the button because the md-button-toggle will do this for you. 
Simply remove the ` :class="{ 'md-toggle': isParent }"` and you're good to go.

Thanks!

**Comment by capttrousers** [comment]
Ahhh haha I'm an idiot. Thanks it works!

**Comment by marcosmoura** [comment]
Don't worry! Glad to help. Please tell me if something wrong come up. Thanks!
