### ISSUE TITLE
mdSwitch doesn't updates when value prop changed

### ISSUE THREAD

**Issue by ghettovoice** [marcosmoura/vue-material#200]
Hi. I have an issue with updating state of the mdSwitch after it was rendered on the page. Take a look at the test case example below. I initialize mdSwitch with value from parent data, after 2 sec I update parent 
property value, mdSwitch updates only it's color, but the button remains in place.
Is it expected behaviour?
I think it lacks watcher for `value` property to update internal state and button position
https://github.com/marcosmoura/vue-material/blob/master/src/components/mdSwitch/mdSwitch.vue#L52
```
watch: {
  ...,
  value () {
    this.checked = this.value
  }
}
```
Thank you for your work! It's excellent library

### Steps to reproduce
Render mdSwitch inside some parent component, initialize it's value prop with parent component data, then change parent data
### Which browser?
Vue ^2.0, Vue Material latest
### What is expected?
I expect that changing value property of the mdSwitch component should update it's view
### What is actually happening?
Only color was changed
### Reproduction Link
[Test case](http://codepen.io/anon/pen/GNYepQ)

**Comment by marcosmoura** [comment]
Hi @ghettovoice 

Yep. You're right. It's missing a watcher. I will fix this asap. Thanks!

**Comment by ghettovoice** [comment]
Ok! Thank you
