### ISSUE TITLE
Cannot read property 'installed' of undefined(…)

### ISSUE THREAD

**Issue by DomenicRoti** [marcosmoura/vue-material#203]
I'm using v0.4.1 with vue v2.1.6

It's causing this error:
`vue.js?3de6:3357 Uncaught TypeError: Cannot read property 'installed' of undefined(…)` which appears to happening here:

`function initUse (Vue) {
  Vue.use = function (plugin) {
    /* istanbul ignore if */
    if (plugin.installed) {
      return
    }`

That error is in chrome, but firefox it is similiar it says `TypeError: plugin is undefined`
and I believe is orginating in my main.js  with `Vue.use(VueMaterial.mdCore)`

**Comment by DomenicRoti** [comment]
Actually, I figured out it out, the syntax changed from

`Vue.use(VueMaterial.mdCore)` to
`Vue.use(VueMaterial.MdCore)`

**Comment by marcosmoura** [comment]
Yep. I forgot to mention. I will update the documentation. Sorry about that! Thanks!

**Comment by gazpachu** [comment]
@marcosmoura just a reminder about updating the docs. That's how I ended up here :)

**Comment by iseos** [comment]
Update the documentation. pls

**Comment by Andrauss** [comment]
Update documentation

**Comment by gkatsanos** [comment]
I made a pull request.

**Comment by qodehub-nanadjei** [comment]
Please how do I install:
 ``import { MdDatePicker } from "vue-material/dist/components";``
