### ISSUE TITLE
Vee-Validate

### ISSUE THREAD

**Issue by rafaelbrotas** [marcosmoura/vue-material#204]
First of all I would like to parabeze you for the great work!
I started working with vue-material today and I have little experience, so it's probably a problem I'm not identifying.

When I configure vee-validate with an element "input" it is working normally but when I use "md-input" vee-validate does not identify the field.

I'm sorry for the English, but I'm using the translator.

**Comment by marcosmoura** [comment]
Hi @rafaelbrotas 

Can you create a Codepen with your issue? I can't help without see the code.

Thank you!

**Comment by rafaelbrotas** [comment]
Hello Marcos, how are you?
Note that vee-validate identifies the input field by "name" but in md-input it assigns "undefined" and consequently I can not assign the classes of errors. Thank you very much! 
http://codepen.io/anon/pen/XNyoyV

**Comment by marcosmoura** [comment]
You should add the ```data-vv-name="emailMD"``` property. This is on the latest release of vee-validate. It's flagged as a breaking change. Thank you!

**Comment by rafaelbrotas** [comment]
Thank you very much!
