### ISSUE TITLE
mdTableEdit as textarea

### ISSUE THREAD

**Issue by kpilard** [marcosmoura/vue-material#205]
Hello,

we need a way to edit a textarea in a table. The mdTableEdit only provides an input field.
I could implement it, but i have to know the api (own component or a property for mdTableEdit)

And the mdTableEdit is missing in the docs since v0.4.0. Is there a reason for it or have you forgotten it?

**Comment by marcosmoura** [comment]
Hi @kpilard.

Yes. I didn't mentioned because it's not finished yet. I will improve the md-table component with the table-edit. J would love to see an improvement over this element, but I would recommend you to way until the next version. 

Thank you.

**Comment by kpilard** [comment]
Yes i will wait for the next version
