### ISSUE TITLE
<md-icon> component Icons on Material site not working properly

### ISSUE THREAD

**Issue by DevEclipse** [marcosmoura/vue-material#206]
for example i want to use "exit to app" icon

`<md-icon>exit to app</md-icon>`

would not reveal anything

another thing is that it parses the wrong icon for example

`<md-icon>shopping cart</md-icon>`

it will parse

`<md-icon>shop</md-icon>`

**Comment by huhk-sysu** [comment]
try `<md-icon>shopping_cart</md-icon>`
use the underscore instead of space

**Comment by marcosmoura** [comment]
@huhk-sysu already gave you the answer. I will update the documentation with better examples. Thanks.
