### ISSUE TITLE
Snackbars and toasts

### ISSUE THREAD

**Issue by marcosmoura** [marcosmoura/vue-material#21]
Snackbars provide brief feedback about an operation through a message at the bottom of the screen.

Specs for [Snackbars](https://material.google.com/components/snackbars-toasts.html)

![Snackbar](https://material-design.storage.googleapis.com/publish/material_v_9/0B7WCemMG6e0VSjZkendtc19iZ2M/components_snackbars.png)

**Comment by ozgureffe** [comment]
Hi and thank you for your excellent work. I wonder when this component will available? Or is there any way to use it before you publish?
