### ISSUE TITLE
md-input type="date" the label doesnt keep the input wide enough

### ISSUE THREAD

**Issue by capttrousers** [marcosmoura/vue-material#210]
### Steps to reproduce
using an md-input with type="date"
if there is no value set, no initial value, or the v-model data property doesnt have an initial value, click the input and choose something, and then click the X to clear it, then click anywhere else on the page to clear the input focus

### What is expected?
I'd expect the label and the "placeholder" of the date input type to maintain the input box normally sized

### What is actually happening?
the input box ends up shrinking pretty small, which squeezes the label onto two lines, overflowing

### Reproduction Link
http://codepen.io/anon/pen/qqQzpq

**Comment by jeimz143** [comment]
@capttrousers i believe its just your table element that makes your input date squeeze.
you should try some other way or use something like this example http://materializecss.com/grid.html

**Comment by marcosmoura** [comment]
Hi @capttrousers 

Your table is affecting the size of your input. If you remove it you'll see that the problem goes away. I will release a new verison this week with a grid system, so, if you want, you do not need to use that Materialize grid that @jeimz143 said. 

Thank you.

**Comment by jeimz143** [comment]
ill be waiting with your grid system :)

**Comment by marcosmoura** [comment]
It's already available!

**Comment by jeimz143** [comment]
i can't see the code again... when i preview the code ..
https://vuematerial.github.io/#/ui-elements/layout

**Comment by marcosmoura** [comment]
I will fix this ASAP/

**Comment by capttrousers** [comment]
@marcosmoura  when you release new versions, all we need to do to get the updated version is just `npm update vue-material` ? or maybe just `npm update` in order to get updates to any dependencies? or is there any other steps? Thanks!

**Comment by marcosmoura** [comment]
There is no dependency attached with Vue Material. Only Vue.js itself. So `npm update` or `npm i --save` it's enough. For the new version (0.5.0) there is a breaking change, so you should follow the instructions on the changelog page. Thanks!

**Comment by capttrousers** [comment]
Nice dude, well done, I'm very excited about the grid system.

**Comment by capttrousers** [comment]
fyi, the link in the title of the changelog here https://vuematerial.github.io/#/changelog
that links to this page https://vuematerial.github.io/releases/v0.5.0/
says that link doesnt exist

**Comment by marcosmoura** [comment]
It'll be fixed too! Thanks!
