### ISSUE TITLE
Include cdnjs into workflow?

### ISSUE THREAD

**Issue by craigvantonder** [marcosmoura/vue-material#214]
Just wondering if we could consider to add cdnjs into the workflow of this package, it would be awesome if we had CDN links to make use and I think the cdnjs-importer would make it easy to update the CDN when you release new versions?

I just figure it would make it easier for noobs like me to get going with vue-material as I battled a bit :)

Also, making fiddles i've been using rawgit but it's problematic and not sure if theres a better way to go about including the resources but having a CDN copy would make it a lot easier.

Links:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
https://github.com/cdnjs/cdnjs-importer
https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

**Comment by marcosmoura** [comment]
Agreed! I will prioritize that! Will be released ASAP! Thank you!

**Comment by marcosmoura** [comment]
I already have a CDN: https://unpkg.com/vue-material
I will add this to the docs. Thanks!
