### ISSUE TITLE
Cannot scroll down on the docs site in Firefox

### ISSUE THREAD

**Issue by craigvantonder** [marcosmoura/vue-material#218]
I'm having issues with the new docs site. Cannot scroll up or down.

Ubuntu 16.04 - Firefox 50.1.0

That being said, it works fine in chrome.

Notice these errors in the console in firefox:

+ Blocked loading mixed active content "http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" [Learn More] vuematerial.github.io
+ Blocked loading mixed active content "http://fonts.googleapis.com/icon?family=Material+Icons" [Learn More] vuematerial.github.io

And in chrome: 

+ Mixed Content: The page at 'https://vuematerial.github.io/#/components/table' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://codepen.io/pen/define'. This endpoint should be made available over a secure connection. Ae @ docs.0c76b7b3.js:7
+ WGavBE:13 Mixed Content: The page at 'https://vuematerial.github.io/#/themes/configuration' was loaded over HTTPS, but requested an insecure prefetch resource 'http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic'. This content should also be served over HTTPS.
+ WGavBE:13 Mixed Content: The page at 'https://vuematerial.github.io/#/themes/configuration' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic'. This request has been blocked; the content must be served over HTTPS.
+ WGavBE:14 Mixed Content: The page at 'https://vuematerial.github.io/#/themes/configuration' was loaded over HTTPS, but requested an insecure prefetch resource 'http://fonts.googleapis.com/icon?family=Material+Icons'. This content should also be served over HTTPS.
+ WGavBE:14 Mixed Content: The page at 'https://vuematerial.github.io/#/themes/configuration' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/icon?family=Material+Icons'. This request has been blocked; the content must be served over HTTPS.

Seems like it would be an easy fix by giving https links to the relative assets in https://github.com/marcosmoura/vue-material/blob/master/docs/index.html but unsure of that issue with the codepen link.

**Comment by marcosmoura** [comment]
Gotcha! I've found the problem. It's due to a flexbox issue on Firefox. I will release the fix in a couple hours. Thank you!
