### ISSUE TITLE
Only one line displayed in dialog content (IE 11)

### ISSUE THREAD

**Issue by thoss** [marcosmoura/vue-material#219]
Hi,

there will only one line displayed in the dialog content, for example the [confirm dialog](https://vuematerial.github.io/#/components/dialog) of your documentation. (tested in IE 11)

Thank you

**Comment by marcosmoura** [comment]
When this happens? Only for the confirm Dialog on the documentation?

**Comment by thoss** [comment]
The confirm and prompt dialog

**Comment by aagahi** [comment]
Same with
![Screen iOS 10.2](https://cloud.githubusercontent.com/assets/308452/21506565/5343b98e-cc71-11e6-8083-c85a09c109e9.png)

As a quick workaround I suggest using css:

`
.md-dialog, .md-dialog-content, .md-dialog-actions {
  background-color: white !important;
}
`

**Comment by aagahi** [comment]
To clarify, the background property of `.md-dialog-content` is quiet fuzzy to me. I don't get why there are so many values for just a white background ;), but the issue same to be related to those values.

`linear-gradient(180deg,#fff 0,#fff 1px,transparent 0),linear-gradient(0deg,#fff 0,#fff 3px,transparent 0),linear-gradient(180deg,rgba(0,0,0,.12) 0,rgba(0,0,0,.12) 1px,transparent 0),linear-gradient(0deg,rgba(0,0,0,.2) 1px,rgba(0,0,0,.2) 2px,transparent 0)`

**Comment by marcosmoura** [comment]
This color is not for the background itself, but for the scroll border trick.

**Comment by marcosmoura** [comment]
#184
