### ISSUE TITLE
Manipulate toggle buttons

### ISSUE THREAD

**Issue by joostlawerman** [marcosmoura/vue-material#22]
Is there anny way of manipulating the state of an toggle button for example:

    <md-button class="md-icon-button" @click="toggleBold" :class="{ 'md-toggle': this.state.bold }">
        <md-icon>format_bold</md-icon>
    </md-button>

It should be activated when the state bold is true... but it does not seem to work this way.

**Comment by marcosmoura** [comment]
@joostlawerman just remove the "this" keyword in your template

**Comment by joostlawerman** [comment]
@marcosmoura of course thank you seems I was not paying attention.

**Comment by marcosmoura** [comment]
Oh. Don't worry.

**Comment by capttrousers** [comment]
Piggy backing on this thread, @marcosmoura  is the md-button-toggle wrapper component necessary if we want a single toggle button? I could use the switch/checkbox component but I like the toggle button for my UI better. Or can we just do an <md-button> component and programtically add or remove the md-toggle button to get the same effect?

**Comment by marcosmoura** [comment]
No. You will need to add the wrapper.

**Comment by capttrousers** [comment]
I can't seem to get the toggle to behave like I expect, here's my code, but basically it applies the md-toggle class the opposite from when it should. When isParent returns true, the class is not applied, when it returns false, the md-toggle class is applied. The button component will not initially be toggled, and it is not when using the below code:

```jade
md-button-toggle.md-primary(v-md-theme="'row'")
          md-button(@click="toggleHierarchy", :class="{ 'md-toggle': isParent }") Parent
```

**Comment by marcosmoura** [comment]
Can you add your example on Codepen?

**Comment by capttrousers** [comment]
Hey @marcosmoura , I tried doing a jsfiddle, but I couldnt get the dependencies in. I see the template for codepen now, I will get that up and see if I can reproduce the issue, and open a new gh issue. Thanks!
