### ISSUE TITLE
Allow Center-xs and Middle-xs just like in flexboxgrid.com

### ISSUE THREAD

**Issue by DevEclipse** [marcosmoura/vue-material#224]

**Comment by Morgul** [comment]
Just for reference, the section being referred to is here: http://flexboxgrid.com/#alignment

![image](https://cloud.githubusercontent.com/assets/770655/21290198/cd79550e-c476-11e6-94bf-8582147bd0ee.png)

![image](https://cloud.githubusercontent.com/assets/770655/21290202/ef3b8b12-c476-11e6-9f6d-4583ca8a96c7.png)

I think these would be useful additions, thought I think that could could pull off `center` with something like this:

```html
<md-layout>
  <md-layout md-flex="50" md-flex-offset="25">
    <b>Centered Content Here</b>
  </md-layout>
  <md-layout md-flex="25"></md-layout>
</md-layout>
```

But I think we can all agree that's not optimal.

**Comment by marcosmoura** [comment]
Hi @DevEclipse and @Morgul 

To center a element you can use the offset for now:
``` vue
<md-layout>
  <md-layout md-flex="50" md-flex-offset="25">
    <b>Centered Content Here</b>
  </md-layout>
</md-layout>
```
I will add another alignment property to fix this issue.
Thank you!
