### ISSUE TITLE
[0.5.1] <md-switch> doesn't work

### ISSUE THREAD

**Issue by leopard7777777** [marcosmoura/vue-material#225]
\<md-switch\> doesn't work

**Comment by marcosmoura** [comment]
Give me some details, please. Thank you

**Comment by Sarpedion** [comment]
I guess he is talking about error that pops up in [switch documenation](https://vuematerial.github.io/#/components/switch.)

![image](https://cloud.githubusercontent.com/assets/16826299/21289677/5a9c61d4-c4a3-11e6-88fd-de38c6d10cfc.png)

**Comment by justinjkline** [comment]
I'm getting this error as well. It's both on Vue Material's website as well as when I upgraded to the latest version (0.5.1).

**Comment by leopard7777777** [comment]
as same as  @Sarpedion  say, can't render this component.
now, i use 0.4.3 and wait for next stable version.
i enjoy your project very much.

**Comment by mycarrysun** [comment]
Love this project but I'm getting the same error: 
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in component <md-switch>)
Getting this in both my application and on the docs pages.

**Comment by bolerodan** [comment]
Seems to be a missing opening <template> tag in the mdSwitch.vue source.

**Comment by jeimz143** [comment]
@mycarrysun 
@marcosmoura 
i have the same issue here  :(( need help

**Comment by marcosmoura** [comment]
Oh. That's really bad. I'm fixing this now!

**Comment by jeimz143** [comment]
can you return the older version for a while it keeps me redirecting to the newer version  whenever i switch to the older version. thanks :))

**Comment by marcosmoura** [comment]
This will be fix too. The end of the year here in Brazil is a little hard, so I'm trying to find time to deal with those bugs. Sorry about that!

**Comment by amor520** [comment]
+1 

**i enjoy your project very much.**
