### ISSUE TITLE
active-tab as a prop in md-tabs component.

### ISSUE THREAD

**Issue by ozgureffe** [marcosmoura/vue-material#228]
I think tab component needs a property to select active tab. 
It will allow us to switch tabs programmatically without directly clicking tabs.
I am currenctly using $refs to achieve this. But it will be much easier if I can select active tab with its name, or id of it. And I think it is a common scenario to switch tabs like this.

`<md-tabs :active-tab="music">`

**Comment by marcosmoura** [comment]
This property already exists. And it's inside the md-tab component as `md-active`.

**Comment by brunnolou** [comment]
Ok @marcosmoura but how to switch tabs programmatically? Like with next and previous actions?

**Comment by marcosmoura** [comment]
There is no "next" and "previous" actions. You can set the "active" property dynamically by setting the "md-active" property of a particular tab:

``` vue
<md-tabs>
  <md-tab :md-active="activeTab === 0">
  </md-tab>

  <md-tab :md-active="activeTab === 1">
  </md-tab>

  <md-tab :md-active="activeTab === 2">
  </md-tab>
</md-tabs>
```

**Comment by nothinggift** [comment]
There is a issue
Set activeTab default to 1,click tab 2,and then set activeTab to 1,nothing would happen.

**Comment by mrodal** [comment]
I think this should be in the documentation
