### ISSUE TITLE
Pagination component not working correctly

### ISSUE THREAD

**Issue by vesavlad** [marcosmoura/vue-material#229]
### Steps to reproduce
1. Initialize the pagination component via binding the values to locally stored values (default ones)
<md-table-pagination
            :md-size="pagination.perPage"
            :md-page="pagination.current"
            :md-total="pagination.total"
            md-label="Rows"
            md-separator="of"
            :md-page-options="[5, 10, 15, 25, 50]"
            @pagination="onPagination">
        </md-table-pagination>
2. Make an api call that will update the paginator configuration:
pagination: {
                    perPage: 15,
                    currentPage: 1,
                    total: 1
                }

### Which browser?

vuejs: version 2.1.16
vue material: 0.5.1
OS: Mac OS sierra, Chrome

### What is expected?
The next page should be enabled since the server response will update the paginator configuration as follows:
currentPage: 1
currentSize: 5
lastPage: false computed
mdLabel: "Rows" prop
mdPage: 1 prop
mdPageOptions: Array[5] prop
mdSeparator: "of" prop
mdSize: 15 prop
mdTotal: 48 prop
subTotal: 15
totalItems: 1

This is a copy paste from vue debugger for chrome

### What is actually happening?
Next page button remains disabled.

See the attached image.
<img width="1498" alt="screen shot 2016-12-18 at 11 17 08" src="https://cloud.githubusercontent.com/assets/1428537/21292579/96376156-c513-11e6-8a06-e7a2caf5f171.png">

**Comment by marcosmoura** [comment]
Duplicated #192
