### ISSUE TITLE
Do you have a grid component in pipeline?

### ISSUE THREAD

**Issue by msoftware** [marcosmoura/vue-material#23]
I like vue-material but I need a grid component to show tables. Do plan to implement something like this?

**Comment by marcosmoura** [comment]
Yes. The md-table is a must have. But I have other components prioritized, like menus, cards, progress, toasts and dialogs. Then I will develop the data table component. I think that this will fit for the 0.5.0 release. 

Thank you.

**Comment by marcosmoura** [comment]
The component will be developed in the next minor version (v0.3.0). You can track the progress on the following issue: #32
