### ISSUE TITLE
md-select documentation for emitted events

### ISSUE THREAD

**Issue by nicolas-bonnel** [marcosmoura/vue-material#230]
The [documentation for select](https://vuematerial.github.io/#/components/select) states that there is one emited event upon change that is named `selected` where in the code there are 2 other events :

``` 
changeValue(value) {
   this.$emit('input', value);
   this.$emit('change', value);
}
```

**Comment by marcosmoura** [comment]
Hi @nicolas-bonnel 
The input and change events are used only to update the v-model. But the selected event should be in the md-option, so will change this inside the documentation. Sorry about that. 
Thanks!
