### ISSUE TITLE
Bug when change routes (vue router)

### ISSUE THREAD

**Issue by odranoelBR** [marcosmoura/vue-material#231]
When change routes, the error occurs.

```javascript
Cannot read property 'offsetLeft' of undefined(…)
calculateIndicatorPos @ vue-material.js?ec92:8
boundFn @ vue.common.js?e881:127
(anonymous function) @ vue-material.js?ec92:8
```

Tks

**Comment by marcosmoura** [comment]
Oh. That's strange. In the Vue Material documentation there is a vue-router, and it's working fine.
Can you provide a Codepen with an example?

**Comment by huhk-sysu** [comment]
It's really strange. I find this error when I try routing to a page, while the error doesn't happened when I am routing to another page in the same way. I have made some test and it seems that there's no association between the error and the content of the child page.

So far my workaround is: 
> Using `router-link` element to produce an `<a>` instead of  using `$router.push` in javascript code

**Comment by bolerodan** [comment]
Are you sure it's md-button? It seems a bit misleading. CalculateIndicatorPos is a method within mdTabs. Do you have a tabs component on these routes you've been testing perhaps?

**Comment by marcosmoura** [comment]
HI. Thanks for a such detailed description. This helped me a lot. I've found the problem and I will release a fix soon. Thank you!

**Comment by odranoelBR** [comment]
Tks @huhk-sysu for reproducing.
Tks @marcosmoura for the help!

**Comment by sxxhlx** [comment]
`<router-link to="/center">

            <md-button style="color:white" class="md-icon-button">
                <i class="icon avatar-icon"></i>
            </md-button>
            </router-link>`

this code shows the same error
