### ISSUE TITLE
Theme issue (version 0.5.1) - Grey as background doesn't work 

### ISSUE THREAD

**Issue by bjarnik** [marcosmoura/vue-material#233]
Registering a theme with the background as 'grey' doesn't appear to have any effect. 
Looking at the CSS the body is still set as #fff. 

Tried other colors and they have the desired effect, is it possible that there's an issue specifically connected to the color grey?

**Comment by marcosmoura** [comment]
Hi @bjarnik 
No. The default is grey, with A100 as default. I will change this to be white as the default. 
Thanks!

**Comment by huhk-sysu** [comment]
> with A100 as default

I wonder whether the hue can be set by my self.
I defined my theme in the following way:
```javascript
Vue.material.registerTheme({
  default: {
    primary: {
      color: 'blue',
      hue: 700
    },
    accent: 'red',
    warn: 'red',
    background: {
      color: 'deep-orange',  // just for example
      hue: 'A200'  // doesn't work
    }
  },
}
```
I change the `background.hue` from `'A200'` to `'A700'`, and `500`/`700` later. But the `background-color` **dosen't change** at all.
![image](https://cloud.githubusercontent.com/assets/14769033/21323210/64f079a8-c657-11e6-8a1b-4b6b204a3015.png)
Interestingly the `color` change between (0,0,0,0.87) to (255,255,255,0.87) according to the hue.

**Comment by huhk-sysu** [comment]
> with A100 as default

Can I set the hue as I wish? I tried writing code like
``` javascript
background: {
      color: 'grey',
      hue: 300
 },
```
but I failed. It seems the hue is fixed to `'A100'`

**Comment by pipejesus** [comment]
Hi, i came across the same issue when trying to setup a "dark" theme. Seems like all backgrounds appear in a very light hue of selected color and setting 'hue' does not change anything.
