### ISSUE TITLE
mdTabs with v-if cause error

### ISSUE THREAD

**Issue by VicarEscaped** [marcosmoura/vue-material#235]
### Steps to reproduce

1. click "open modal" button
2. focus on input
3. click close

### Which browser?

Google Chrome 55.0.2883.87 m
### What is expected?
Modal closed without error
### What is actually happening?
in console i get error:

> Uncaught TypeError: Cannot read property 'offsetLeft' of undefined
    at o.calculateIndicatorPos (VM2922 vue-material@0.5.1:8)
    at o.n [as calculateIndicatorPos] (VM2921 vue.min.js:6)
    at VM2922 vue-material@0.5.1:8

If not focusing on input no error will shown

### Reproduction Link
[codepen](http://codepen.io/anon/pen/WomNJz)

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE.

**Comment by marcosmoura** [comment]
I've found this bug and the fix will come in the very next release. Sorry about that.
This is related to #231
