### ISSUE TITLE
[Query] Alternative to Bootstrap navbar element?

### ISSUE THREAD

**Issue by mubaidr** [marcosmoura/vue-material#236]
I am trying to use `Toolbar` component [https://vuematerial.github.io/#/components/toolbar](url) as a replacement for bootstrap `navbar` but i cannot get it to behave like bootstrap `navbar`. 

For example i want menu links in the navbar/toolbar to shrink to drop-down menu (hamburger icon) when on small screen but i cannot see if such functionality is available here. I did think of workaround to use `md-hide-{type}` to hide and show different elements depending upon screen size, but it does not feel right.

**Comment by bolerodan** [comment]
Im not 100% sure if that typeof functionality is to Material Design spec, so in that case this seems like something you'd have to implement yourself with CSS and media selectors. But I could be wrong, it does seem a bit out of place for Material Design.

**Comment by Morgul** [comment]
@mubaidr Out of the box, no, `vue-material` does not support responsive collapsing. You would need to put your content in a `<md-layout>` and use utility classes like `md-hide-{type}`, as you saw.

**Comment by marcosmoura** [comment]
HI @mubaidr.

The Material Design specs do not cover this scenario. The best option that you can have is to hide the items using a custom media query or using the `md-hide-small` class. You can have a overflow button with something like "more" options (or the less priority ones).

Thank you.
