### ISSUE TITLE
Button provided in mdListItem is not clickable

### ISSUE THREAD

**Issue by VicarEscaped** [marcosmoura/vue-material#237]
### Steps to reproduce

- open [list's docs](https://vuematerial.github.io/#/components/list)
- click on any icon button in list item
- button is not clickable

### Which browser?
Firefox 50.1.0 on Windows 7

### What is expected?
Button in list item is clicked. 
### What is actually happening?
List item receive event

### Reproduction Link
[list's docs](https://vuematerial.github.io/#/components/list)

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE.

**Comment by marcosmoura** [comment]
Hi @VicarEscaped. 
In fact the list item event will not be triggered if you click inside the icon. This is a common behaviour to have separated actions, one for the actual list item and another for the "secondary" action. But in Firefox it seems that the ripple effect is not working, so I will keep this issue opened to fix this bug.
Thanks!
