### ISSUE TITLE
mdSidenav method "show" should be "open" according to the docs

### ISSUE THREAD

**Issue by sylvainpolletvillard** [marcosmoura/vue-material#238]
According to the docs, mdSidenav should have an `open` method but when looking into the source code, it appears it is called `show`.

See: https://github.com/marcosmoura/vue-material/blob/master/src/components/mdSidenav/mdSidenav.vue#L29

![image](https://cloud.githubusercontent.com/assets/566536/21356822/45f45de0-c6d3-11e6-869a-c696bf08462e.png)

### Reproduction Link

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE.

**Comment by marcosmoura** [comment]
Oh. Yeah. You're right. I will fix this ASAP.
