### ISSUE TITLE
Links (<a> elements) in md-menu-item?

### ISSUE THREAD

**Issue by mhchen** [marcosmoura/vue-material#239]
First of all, thanks for your work on this project. Excited to be able to use a component library like Material in a lightweight framework like Vue.

Is there a right way to make it so my menu items are just straight up links to other pages (not router links)? I wrapped my <md-menu-item> in <a> tags which works but doesn't produce valid markup (ul > a > li):
```
<a href="/profile">
  <md-menu-item>
    My profile
  </md-menu-item>
</a>
```

Any plans to make it possible to put links in the menu, or should I just work out a better hack?

**Comment by marcosmoura** [comment]
The md-menu-item accepts the href property. The output will be the `<a>` tag.
Thanks!

**Comment by romangit** [comment]
Hi Marcos,
> The md-menu-item accepts the href property. The output will be the `<a>` tag.

It's not working
http://codepen.io/anon/pen/XpVJBO
