### ISSUE TITLE
md-select text vs value

### ISSUE THREAD

**Issue by Lukino2000** [marcosmoura/vue-material#24]
Hi,

is there a reason for displaying value instead of the text in md-select?

i think it shoud behave like html select:
you click the "text" when dropdown is open (and this works also in vue-material) 
and view "text" when the dropdown is closed (at the moment it display the value associated ad md-option. 

thanks
/L2K

**Comment by marcosmoura** [comment]
@Lukino2000 Yeah. You're right. The md-select have some bugs. I'm creating the md-menu component, and the md-select will inherit some properties and some code that will improve his behaviour. I will fix this text/value in the next version. Thank you for reporting this!

**Comment by marcosmoura** [comment]
Already implemented and will be shipped on the very next release (v0.3.0)
