### ISSUE TITLE
Release version select doesn't work 

### ISSUE THREAD

**Issue by ascarpello** [marcosmoura/vue-material#240]
https://vuematerial.github.io/#/
I can't switch between docs versions, i can only see te last doc version (0.5.1)
![schermata 2016-12-21 alle 16 05 07](https://cloud.githubusercontent.com/assets/13118130/21394397/c7b899ac-c798-11e6-99db-56ccb753267d.png)

**Comment by marcosmoura** [comment]
Yeah. This is a sad bug. I will fix this asap.
