### ISSUE TITLE
Css Order

### ISSUE THREAD

**Issue by rafaelbrotas** [marcosmoura/vue-material#241]
How to import css after <style type="text/css" id="md-theme-default">?
Thanks!

**Comment by marcosmoura** [comment]
The style tag is generated automatically by the the engine. Why do you need a css after?

**Comment by rafaelbrotas** [comment]
I need to customize some components in specific cases and am creating a separate css file for this. It's possible? Thanks!

**Comment by marcosmoura** [comment]
You can create another external css and reference it in your index file. But make sure that your styles have a higher specificity.
