### ISSUE TITLE
the menu content separate from the menu trigger elements

### ISSUE THREAD

**Issue by despird-zh** [marcosmoura/vue-material#242]
### Which browser?
Version 55.0.2883.95 (64-bit)

### What is actually happening?
the menu content separate from the menu trigger elements
![new](https://cloud.githubusercontent.com/assets/9362558/21412203/7114cc10-c829-11e6-8e5a-b92e9797086c.png)

**Comment by despird-zh** [comment]
seems the menu content element ignore the scroll up/down event, and not re-calculate the new absolute position.

**Comment by marcosmoura** [comment]
Hi. 

I will check that ASAP. Thanks.
