### ISSUE TITLE
md-select (multiple) not being reactive

### ISSUE THREAD

**Issue by thoss** [marcosmoura/vue-material#245]
The `md-select` `multiple` component is not being updated when the `v-model` changes. Also the initial state of a select with `multiple` is not working.

**Comment by marcosmoura** [comment]
Can you give me a Codepen example?

**Comment by thoss** [comment]
Hi,

here is the [codepen](http://codepen.io/thoss/pen/BQexmm)

This example only works if the `users array` will be set in the `data property`

Or is there something wrong with the code?

Thanks and happy christmas!
