### ISSUE TITLE
Is there any possible way of adding themese with custom color?

### ISSUE THREAD

**Issue by ozgureffe** [marcosmoura/vue-material#250]
Hi. I wonder if is it possible to create palette and register as theme based on my custom color.
I mean can I use this service with vue-material => https://angular-md-color.com/#/

**Comment by Sarpedion** [comment]
As far as I know, at this moment the theme engine does not allow to define custom theme colors, but it is scheduled for milestone 0.7.0  (#202). 
If you really need to use a custom theme, you can fork the project and alter [palette.js file](https://github.com/marcosmoura/vue-material/blob/master/src/core/components/mdTheme/palette.js) and then rebuild the project and use it for yourself.

**Comment by marcosmoura** [comment]
Duplicated #39 #202

**Comment by tfsimondouglas** [comment]
I'm having this issue right now. I will report back if there is a work around using https://www.npmjs.com/package/path-override-webpack-plugin
