### ISSUE TITLE
Everything became undefined after updating Vue to 2.1.7

### ISSUE THREAD

**Issue by DevEclipse** [marcosmoura/vue-material#251]
If you are the author of a plugin/component that ships a pre-compiled dist file:

It is recommended to re-compile the dist file using the latest versions of vue-template-compiler and vue-template-es2015-compiler. The new generated code is backwards-compatible, but code generated by older versions of the compilers may not work properly with the latest runtime.

Code generation changes that affect compatibility are very rare and we will avoid introducing similar changes in future patch releases.

Please Recompile the dist thank you :)

**Comment by vouill** [comment]
I tried to update the repo in a fork, however its not as simple as : 
`yarn upgrade vue-template-compiler@2.1.7 vue@2.1.7`

It works, however i do have some 'undefined' that appears  for few ms, enough to be noticeable, before the component gets fully rendered. Moreover when checking out the `npm run dev`, it seems the entry animations of the different components in the doc is bugged.

**Comment by fiws** [comment]
codepen repo: http://codepen.io/anon/pen/Ypbjqd

**Comment by marcosmoura** [comment]
I will check that. The 2.1.7 is too new, but I will release a patch for this for the v0.5.2.
