### ISSUE TITLE
[0.5.2] Please set <md-table-pagination> totalItems computed

### ISSUE THREAD

**Issue by leopard7777777** [marcosmoura/vue-material#254]
totalItems of mdTablePagination.vue return by data function.

i select mdTotal from db asynchronously. so i set mdTotal = 0 firstly, but totalItems won't refresh, the .md-table-pagination-next button is always disabled 

so i suggest you set totalItems by computed function.

thx very much

**Comment by marcosmoura** [comment]
Related with #192. Thanks!
