### ISSUE TITLE
Embed radio input into the label tag,  don't need id/name attribute

### ISSUE THREAD

**Issue by huangyifu** [marcosmoura/vue-material#255]
`<label> <input type="radio"  /> Male</label>`

when click the label, radio can get the focus even has no id/name attribute.

**Comment by marcosmoura** [comment]
This is correct way to create radio inputs:
``` vue
<md-radio v-model="radio1" id="my-test1" name="my-test-group1" md-value="1">My beautiful radio</md-radio>
```

**Comment by huangyifu** [comment]
This is the better way to create radio inputs:
`<md-radio v-model="radio1"  md-value="1">My beautiful radio</md-radio>`

---template like this----
`<template>
  <div class="md-radio" :class="[themeClass, classes]">    
    <label :for="id || name" class="md-radio-label" v-if="$slots.default">
    <div class="md-radio-container" @click="toggleCheck">
          <input type="radio" :name="name" :id="id" :disabled="disabled" :value="value">
          <md-ink-ripple :md-disabled="disabled" />
    </div>
      <slot></slot>
    </label>
  </div>
</template>`

**Comment by marcosmoura** [comment]
Why?
