### ISSUE TITLE
File Input - Rendering issue

### ISSUE THREAD

**Issue by fabien-lg** [marcosmoura/vue-material#259]
### Description
Rendering issue with HTML file input

### Steps to reproduce
1. Create an input with file type
`<md-input type="file"></md-input>`
2. There is a «box» visible at the left-side of the file input

### Which version?
Vue 2.1.7, vue-material 0.5.2

### Reproduction Link
http://codepen.io/FabienLG/pen/JbQrpE

### Suggestion
Maybe we should have something like this? http://codepen.io/shepard_one/pen/MypdLy

**Comment by marcosmoura** [comment]
Right now the file input is not supported. I will create this on the very next version. Thank you.

**Comment by marcosmoura** [comment]
Already in development!
