### ISSUE TITLE
discussion on menu backdrop

### ISSUE THREAD

**Issue by despird-zh** [marcosmoura/vue-material#265]
Hi Marcosmoura,

This is not an issue ticket, just a discussion about menu widget to meet my curiosity.

I know you add a backdrop layer(div) in the menu component and use it to close the menu content when user click outside of the menu content. this way is okey except when user click another menu. 
let's imagine there are 2 menus A and B. when click A , the menu conten(A) shows. in this situation, user want to click menu(B), he will find menu content(A) disappear, but menu content(B) not shown as expected, he has to click on menu(B) again to tigger the menu content(B). 
this functionality is okay, but this will make user confused, I click on menu B why I have to click twice.(the backdrop layer is transparent, he doesn't know). I'm afraid that this is not a best experience, right?

I'm not very clear about the detail of menu component, I just guess the backdrop layer intercept the user click intention on menu B. As for menu etc. components the backdrop layer is not a required feature, it just need a trigger to close dynamic content when not need any more. Anyway, menu not like popover etc. components need a backdrop layer to block click outside content.

There is another way to implement closing menu content, following vue package may shed some light on this issue:
https://www.npmjs.com/package/vue-clickoutside
https://www.npmjs.com/package/vue-click-outside

we just need an event to trigger close and not block the click on any other components.;-)

many thanks, keep up the great work!!!!

**Comment by despird-zh** [comment]
Have you ever think add a popover component?

**Comment by marcosmoura** [comment]
Thanks for raise this discussion. 

The menu backdrop do not aim to be a "ghost" click to close the dropdown (although it have a click action), but provide a way to stop the user to interact with other elements and scroll the page. The idea is to have exactly the same behaviour of a native `select` tag. I know that `md-menu` is different of the 'md-select', but both have the same idea.

When opened, the native `select` tag **do not** allow us to interact to another HTML element or even scroll the page (or the parent container). You still need to click twice to focus on another thing. While using a normal application, if you are focused in one menu, you should decide to select one option or move to another thing. If you want to move you have to close it and then open another. Unless in a "menubar" component, when a dropdown is connected to another.

This behaviour works the same in other native elements, like `<dialog>` or `<datalist>` tags. 

If I change this concept and implement this idea we will have some problems:
* When open, if the user scrolls, I have to move the content to another position, causing performance glitches.
* A user can accidentally click by mistake and open a external link for example
* And some other implementation problems like add a event on body to close the dropdown

About the popover component: This is not a spec on the Material Design. You can still fill your "md-menu" with other content, like on the contact card example in the documentation website.

Thank you! :D
