### ISSUE TITLE
Password input and tabbing

### ISSUE THREAD

**Issue by schlaus** [marcosmoura/vue-material#271]
This is about password inputs within an `<md-input-container>` that has the property `md-has-password`, ie. where the password input can be changed into a regular, unobscured text input with a button within the actual input. Currently, the button which reveals the value of a password field can be tabbed to, but the button gives no indication that it has focus. This can potentially cause someone to inadvertently reveal their password, and is also a bit confusing, since it seems like the form just loses focus altogether.

My opinion is that the button should not be reachable by tabbing, and as such I'd ask that you consider giving the button a negative tabIndex.

Alternatively, if the button can be tabbed to, it should give some indication that it has focus.

**Comment by marcosmoura** [comment]
@schlaus The idea is to have a "focusable" state of the button. If you press tab it will highlight the button, and if the enter key is pressed, the button will fire the action. This is already scheduled here #31.

Thank you!

**Comment by schlaus** [comment]
@marcosmoura Whoops, seems like I missed that. Glad to hear it's on the list!

**Comment by marcosmoura** [comment]
@schlaus Don't worry! Thanks for reporting that!
