### ISSUE TITLE
How do you make a reactive sidebar like on the docs?

### ISSUE THREAD

**Issue by Morgul** [marcosmoura/vue-material#272]
What I'm going for is a sidebar that works like the documentation sidebar; it is present on larger screen sizes, but works like a normal sidebar on smaller sizes.

Right now, the only option I can see is to make the content a component, and then load it twice; one in a layout that's visible only on larger sizes, and the other in a sidebar that only shows up on small screens.

Would it be possible to simply have an option for the current sidebar component that lets it work in a responsive manner?

**Comment by Morgul** [comment]
I just saw #154. Would it be possible to get a brief example of the media query work around you're using on the docs site, as a work around for now?

**Comment by marcosmoura** [comment]
Hi. You can see it here: #44 

I will develop this new component in the next versions.
