### ISSUE TITLE
css utility classes for color and custom build not working

### ISSUE THREAD

**Issue by Lynges** [marcosmoura/vue-material#273]
I was trying to put in a set of utility classes that would be available to color custom components with the theme colors.
So far as I can work out it would only take to add a few lines to core.theme. Something like this I think:

```
/* Utility classes for custom components */

.THEME_NAME .md-primary-background {
  background-color: #{'PRIMARY-COLOR'};
  color: #{'PRIMARY-CONTRAST-0.99999'};
}

.THEME_NAME .md-accent-background {
  background-color: #{'ACCENT-COLOR'};
  color: #{'ACCENT-CONTRAST-0.99999'};
}

.THEME_NAME .md-warn-background {
  background-color: #{'WARN-COLOR'};
  color: #{'WARN-CONTRAST-0.99999'};
}

.THEME_NAME .md-background-background {
  background-color: #{'BACKGROUND-COLOR'};
  color: #{'BACKGROUND-CONTRAST-0.99999'};
}
```

That would be cool to have and make it much easier to use the theme system.

AS I am on a project with a looming deadline I though that rather than wait for you to put this feature in, that I would just fork the repo and add it myself. I have been unable to test it as when I make npm install it from my repo it just gives me this error upon running my project:

```
Uncaught Error: Cannot find module "!!babel-loader!vue-loader/lib/selector?type=script&index=0!./mdTheme.vue"
```

I am using it in a project with electron-vue and I have absolutely no issues when using the vue-material from the npm registry.

Any ideas as to what might be happening.
I am afraid that I did commit changes to the master branch and I included the dist folder since I would be using it directly, but I can't see how that could be the source of this error.

Thanks a bunch for any insights you may have to share.

**Comment by Sarpedion** [comment]
I had the same error as @Lynges had upon rebuilding project (I just added a custom theme, but error is present even if i don't change anything in source). I've solved it by reverting the `build` folder to previous version, and then rebuilding again, but I guess that is just a temporary solution.

**Comment by korylprince** [comment]
I'm also having issues building the current master with the included build script, but should be able to build the latest stable (0.5.2):

```
git clone https://github.com/marcosmoura/vue-material.git
cd vue-material
git checkout v0.5.2
npm install
# make your changes
npm run build:lib
# new build in /dist
```

**Comment by korylprince** [comment]
Also the error you're getting suggests you're trying to use your own webpack config. Most likely you're missing this section:

```
module: {
    ... ,
    resolve: {
    ... ,
        extensions: ['', '.js', '.vue']
    }
}

```

The extensions part allows you to import without file extension, which the project uses in a few places.

**Comment by marcosmoura** [comment]
Hi @Lynges.

[Syncronize](https://gist.github.com/CristinaSolana/1885435) your fork to get the latest changes. Always use the develop branch, because maybe there is something new or already fixed. Can you try this first? Thank you.

**Comment by korylprince** [comment]
@marcosmoura, for what it's worth I'm having the same issue on the develop branch. It looks like between 0.5.2 and now you've changed the configs in the build directory.

It successfully builds, but upon importing the built library and running in a browser, I get the same error @Lynges was getting.

I checked out the build directory from the v0.5.2. tag and rebuilt develop and everything worked fine.

**Comment by marcosmoura** [comment]
That's strange. Can you guys sync the repo again and check if something is still broken? Are you running it on which OS?

**Comment by jutin** [comment]
I have the same issue when using v0.6.0 in a Meteor project (MacOs Sierra). Here is the error that I receive:

```
Uncaught Error: Cannot find module "!!babel-loader!vue-loader/lib/selector?type=script&index=0!./mdTheme.vue"
```

 I rolled back to v0.5.2 and it works again.

**Comment by marcosmoura** [comment]
It's fixed now. I'm releasing a new version right now!
