### ISSUE TITLE
md-select do not work with vee-validate

### ISSUE THREAD

**Issue by malinosqui** [marcosmoura/vue-material#276]
### Steps to reproduce

- Install package [vee-validate](https://github.com/logaretm/vee-validate/) with npm
- Put attributes in md-select element as the vee-validate recommend: `data-vv-rules="required" data-vv-as="field" data-vv-name="field"`
- Inspect element rendered

### Which browser?
Chrome

### What is expected?
The attributes are rendered in html select element

### What is actually happening?
The attributes are rendered in div element above select

### Reproduction Link
http://codepen.io/gabrielmalinosqui/pen/GrKgrR

**Comment by stramec** [comment]
Hi

Your codepen was missing a couple of bits, the following works for me:

```
const Hello = Vue.extend({
  data () {
    return {
      movie: ''
    }
  },
  template: `
  <div>

<md-input-container :class="{'md-input-invalid': errors.has('movie')}">
    <label>Movie</label>
      <md-select required v-model="movie" data-vv-name="movie" v-validate data-vv-rules="required">
       <md-option value=""></md-option>
      <md-option value="godfather">Godfather</md-option>
      <md-option value="godfather_ii">Godfather II</md-option>
      <md-option value="godfather_iii">Godfather III</md-option>
      <md-option value="godfellas">Godfellas</md-option>
      <md-option value="pulp_fiction">Pulp Fiction</md-option>
      <md-option value="scarface">Scarface</md-option>
      </md-select>
      <span class="md-error">{{errors.first('movie')}}</span>
    </md-input-container>
  </div>
  `
})

Vue.use(VueMaterial)
Vue.use(VeeValidate)

new Vue({
  el: '#app',
  render: (h) => h(Hello)
});

```

http://codepen.io/stramec/pen/jyNWRY

Hope it helps.

Cheers

**Comment by malinosqui** [comment]
Hi @stramec you're right! This works, buts not with  `this.$validator.validateAll('form');`

Thanks for the answers.

**Comment by stramec** [comment]
Hey @malinosqui 

Not something I've done but are you passing the individual objects to the validateAll()? Looking at the api example doesn't look like you can pass the form as a whole.
```
validateForm() {
            this.validator.validateAll({
                email: this.email,
                name: this.name
            });
        },

```

http://vee-validate.logaretm.com/api#validator

Good luck with it!

**Comment by korylprince** [comment]
@malinosqui I don't think you're using the vee-validate API correctly.

`validateAll` only takes an object like the one @stramec uses above. You *can* use the `validate` method to specify a [scope](http://vee-validate.logaretm.com/examples#scope-example), but you have to specify a scope on the parent form first with `data-vv-scope`.

This would be for having multiple forms on a page with separate validations. If you're just trying to validate one field then use `validate(<fieldname>)`.

**Comment by marcosmoura** [comment]
I can try to help with the vue-validate integration, but if something needs to be changed internally, I will make it with a low priority for [several reasons](https://github.com/marcosmoura/vue-material/issues/197#issuecomment-266925768): #197

**Comment by gazpachu** [comment]
Any luck integrating vee-validate? I've tried with vue-validator but I get `template syntax error - invalid expression: v-validate="minLength: 2, maxLength: 10"`. So, I'm going to try with vee-validate

**Comment by gazpachu** [comment]
Fixed. I was missing the `data-vv-name`, which strangely, the docs mention it's an 'alternative' to the 'name' attribute...
