### ISSUE TITLE
input label not reset when set v-model variable empty

### ISSUE THREAD

**Issue by nothinggift** [marcosmoura/vue-material#277]
`<md-input-container>
    <label>Initial value</label>
    <md-input v-model="initialValue"></md-input>
  </md-input-container>`

Input something and set initialValue empty,  the label will not reset , test on 0.5.2 .

**Comment by korylprince** [comment]
I've seen this problem as well. I've created a codepen showing this issue.

Type some content into the input, then click the "Break!" button to set the `v-model` to `null`. The label doesn't move down to fill the input like it would if you deleted all the text manually.

**Comment by korylprince** [comment]
@nothinggift, I submitted a PR to fix this issue, so as long as it looks good to @marcosmoura, this should appear in the next release. I'm also realizing I never actually pasted the codepen in my previous post. For reference, it is: http://codepen.io/anon/pen/XpraNV

**Comment by nothinggift** [comment]
It's useful,thanks!

**Comment by marcosmoura** [comment]
PR merged!

**Comment by pluschen** [comment]
still present in version 0.7.1
