### ISSUE TITLE
Broken expand list when resize

### ISSUE THREAD

**Issue by ChangJoo-Park** [marcosmoura/vue-material#278]
### Steps to reproduce
Resize window with expandable list

### Which browser?

vue 2.1.8 with electron browserwindow

### What is expected?
Can't see expandable list when resize window

### What is actually happening?

https://www.dropbox.com/s/612k72ysdjdf0cz/%EB%AC%B4%EC%A0%9C.mov?dl=0

### Reproduction Link

<!-- You could start with this template: http://codepen.io/vue-material/pen/WGavBE.

**Comment by marcosmoura** [comment]
Uh. That's bad. I will fix this for the next version. Right now there is no good workaround. Sorry about that. And thank you for a such detailed description (and the video).

**Comment by ChangJoo-Park** [comment]
Thank you for response 👍  I'll wait for fix.

**Comment by ChangJoo-Park** [comment]
Thank you !!
