### ISSUE TITLE
Standalone css bundle for md themes?

### ISSUE THREAD

**Issue by uicestone** [marcosmoura/vue-material#284]
VueMaterial has a standalone css file (dist/vue-material.css), and will also embed <style> tags into HTML for md themes. These embedded style will rewrite any style in linked css file.

There's a situation that I'm using sass to write custom styles, combined into a css file but accidentally rewritten by md theme embedded styles.

Is there any possible that we can pack the theme style into a standalone css file? Thus we can import that css to sass as well and control the import order we need.

If this shouldn't be a feature or this can be done via a webpack plugin or something, can someone provide me an example for extracting md theme style to a css file?

**Comment by marcosmoura** [comment]
This is not possible. The theme engine generates the css content inside the browser. So this is not a build task. What you can do is to change this in a fork. Sorry about that.

**Comment by uicestone** [comment]
Thank you for providing the info.

**Comment by yondaimus** [comment]
Hi,

I would like to know how modify a scss file like MdSelect.scss and compile to update vue-material.css?

Thanks
