### ISSUE TITLE
Floating Action Button positioning

### ISSUE THREAD

**Issue by capttrousers** [marcosmoura/vue-material#286]
Two ideas for FAB's:

1. Basically the buttons that provide a menu of other action buttons, either when hovering on the button or clicking the button initially. The MD page says those are called speed dials which are already on list of components to make.

2. The Floating Action Buttons already provide an Absolute positioning class, where they have `style="position:absolute;"` and I think a Fixed positioning class would help as well. Absolute ends up staying in the same spot on the page even when I have it in my base #app div and the page scrolls down. Fixed positioning stays the same spot on the screen as I scroll. 

Numer 2 seems simple enough, I'd be willing to add it in a PR, I believe it's only adding those classes to [this file](https://github.com/marcosmoura/vue-material/blob/master/src/components/mdButton/mdButton.scss )

**Comment by korylprince** [comment]
It's pretty easy to make your own speed dial:

http://codepen.io/korylprince/pen/EZxpxx

That's not a perfect implementation of the spec, but it wouldn't take too much mucking around with the CSS to get there.

It would be cool to have an `md-speed-dial` that encapsulated `md-button`s and took care of transitions and such though.

**Comment by capttrousers** [comment]
Nice yea thats a good mock up. Where did you get those transition components?

Another cool component would be a general Collapsible div that can be triggered with events. We already have something like this with the `md-list-expand` but I havent tried that without another `md-list` inside. Also, from what I see, the expand component needs to be nested inside an existing `md-list` > `md-list-item` component, so the first list item will always show and act as the toggle button. 

This could be used to abstract the `md-list-expand`, and allow both the accordian and static expand options, the latter being when you click to expand one section, and then click to expand a second section, they both stay expanded. This Collapsible component could also be used with a one time click to cancel, to show some type of banner or announcement only once that the user would then click and cancel and the banner wouldn't appear again.

**Comment by korylprince** [comment]
The transition component is built into Vue itself, and the css I'm using is almost directly copied from the docs:

https://vuejs.org/v2/guide/transitions.html

As far as the rest, I think @marcosmoura is focusing on building components in the Material Design spec. I'm not seeing anything there that meets what you're describing. However I think just like the fab button example, it shouldn't be too hard to make yourself with a transition component and some css.

**Comment by capttrousers** [comment]
@korylprince , thanks for the reply, I never noticed the transition component in the standard vue.js library. 

As for the collapsible component, from the material.io site, they list Expansion Panels as a separate component.

It looks like they behave the same as the `md-list-expand` component, and they're listed again in the List Controls section as an collapsible list component, so I guess maybe for md-vue we could make it an expandable panel that you can optionally put nested lists in. 

Where it's currently documented in md-vue under the List component makes it seem like the expandable component is being relegated to be a sub component of lists when it doesnt necessarily need a list context. Or am I off base? I haven't tried it without a list inside the expand component, so maybe it's just a matter of giving the expandable component it's own section and showing a demo with just some content and then another demo with content that uses the md-list component inside the expanded component.

**Comment by korylprince** [comment]
@capttrousers No, it looks like you're right. When I skimmed over Expansion Panels I thought they just covered lists, but they look to be pretty generic.

It looks like @marcosmoura already has both speed dial and expansion panels on his list to do:
https://github.com/marcosmoura/vue-material/projects/6

**Comment by marcosmoura** [comment]
Hi Guys. Sorry for the delay to answer. The Speed Dial will be the next component to be delivered. Also @korylprince, GREAT job on that codepen!!!

**Comment by korylprince** [comment]
@marcosmoura thanks! I modeled it after the speed dial in the google inbox app.

**Comment by capttrousers** [comment]
no worries @marcosmoura hope you had a good holidays. what do you think about adding a fixed class to the Floating Action Button so they can be fixed on a scrollable page, like the Compose button in the gmail app or the directions button the the gmaps app? is it as simple as i think? if so i'd love to contribute

**Comment by marcosmoura** [comment]
I'm thinking in a special class for the fab, like md-fixed.
