### ISSUE TITLE
[md-table] Wrong data in 'select' event after original data was changed

### ISSUE THREAD

**Issue by sergey-koretsky** [marcosmoura/vue-material#292]
Lets say we have smth like this: (just from my [previous issue](https://github.com/marcosmoura/vue-material/issues/288) )

```javascript
data() {
    return {
      rows: [
        {id: 1, name: "Record #1 name", isEnabled: true},
        {id: 2, name: "Record #2 name", isEnabled: false},
        // ...
        {id: 20, name: "Record #20 name", isEnabled: true},
      ]
    }
}
```

**select** event handler for [md-table](https://vuematerial.github.io/#/components/table) and custom onDelete:

```javascript
    // some code here
        methods: {
            onSelect(rows) {
                console.warn(rows)     // after the first deletion these new rows will be wrong
                this.selectedIds = []
                
                for (var i in rows) {
                    this.selectedIds.push(rows[i].id)
                }
            },

            onDelete() {
                this.rows = this.rows.filter((row) => {
                    return this.selectedIds.indexOf(row.id) === -1
                })
                
                this.selectedIds = []
            }
```
And if we select some rows then hit delete (triggering onDelete) the table will be redrawn correctly (without deleted rows in this.$data.rows) but from this time all new **rows** in onSelect handler willn't match to actually selected rows in md-table

**Comment by sergey-koretsky** [comment]
i think we have to 'unselect' that selected rows array which is passed each time with **select** event but that one is md-table internals and there is no any API provided for that

**Comment by marcosmoura** [comment]
You're right! The md-table still have some problems. I will update it asap. You can track the progress here: #192
