### ISSUE TITLE
Determine active tab of md-bottom-bar

### ISSUE THREAD

**Issue by Morgul** [marcosmoura/vue-material#294]
I'm struggling to figure out how `md-bottom-bar` is intended to be used. I can get it working just like the demo, however, I can't figure out how I'm supposed to tell which item is currently active. I would expect a property to be exposed (possibly with the ability to set a name on `md-bottom-bar-item`). (Alternative, a `switched` event could be added, that emitted the index of the item.)

Looking at the code, each `md-bottom-bar-item` has an active property on it, but I shouldn't have to set a `ref` on them to check, should I? It feel wrong digging into the internal state of a component like that.

Possibly unrelated, I tried putting `@click` handlers on the `md-bottom-bar-item` tags, but they never fired. I'm assuming that's intended to work. There might be some issue with my app, though `md-button` and other components work just fine, in the same template.

**Comment by marcosmoura** [comment]
Well. To set an active item you can use the `md-active` property, like you said.

Can be something like that:
``` vue
<md-bottom-bar>
  <md-bottom-bar-item md-icon="history" :md-active="activeItem === 1">Recents</md-bottom-bar-item>
  <md-bottom-bar-item md-icon="favorite" :md-active="activeItem === 2">Favorites</md-bottom-bar-item>
  <md-bottom-bar-item md-icon="near_me" :md-active="activeItem === 3">Nearby</md-bottom-bar-item>
</md-bottom-bar>
```

To add a @click event you should always use the .native modifier: `@click.native="myMethod"`

**Comment by Sulsummer** [comment]
@marcosmoura 
Hi marcosmoura, I got a problem with bottom bar either.
I'm trying to manually activate items either using md-active-item in md-bottom-bar or md-active in item like your example, neither works.

Here's my screenshot of vue dev tool, you may see that I have set mdActiveItem successfully but bottom-bar's computed activeItem is still another one...
https://pan.baidu.com/s/1o7CZ8L0

**Comment by andyttran** [comment]
I resolved this issue recently. I placed the md-active-item prop on the md-bottom-bar tag instead of on the individual bar items.  The bar items all need an id. Then set the md-active-item matching one of the item ids to set that item to active.

```html
<md-bottom-bar :md-active-item="activeVal">
  <md-bottom-bar-item md-icon="history" id="recent">Recents</md-bottom-bar-item>
  <md-bottom-bar-item md-icon="favorite" id="favorite">Favorites</md-bottom-bar-item>
  <md-bottom-bar-item md-icon="near_me" id="nearby">Nearby</md-bottom-bar-item>
</md-bottom-bar>
```
Here is the js part:
```javascript
export default {
  data() {
    return {
      activeVal: "recent"       // change this value dynamically
    }
  }
}
```
