### ISSUE TITLE
In the <md-input> key modifier (v-on:keyup.enter) not working

### ISSUE THREAD

**Issue by PascalBabey** [marcosmoura/vue-material#298]
Hi,

In the <md-input> element is the key modifier (v-on:keyup.enter) not working. I tried to add a input with the key modifier inside the <md-input>, but i didn't help. 

Thanks for your help and your great layout.

**Comment by korylprince** [comment]
You just need to use the [native](https://vuejs.org/v2/api/#v-on) modifier:

https://codepen.io/korylprince/pen/QdwoNr

This is not easily found... I wish the main Vue event docs talked about this...

**Comment by PascalBabey** [comment]
With the native modifier it's working. Now I do it like this: 
 <md-input placeholder="Name" @keyup.native="add(value, $event)"></md-input>

  methods: {
      add: function(value, event){
            if (event.key === 'Enter')
            {
               //AddSomeThing
            }
          },
  }

Many thanks.
