### ISSUE TITLE
theme not getting applied when using webpack context

### ISSUE THREAD

**Issue by fiws** [marcosmoura/vue-material#300]
I recently updated from 0.2 to 0.5.X and noticed that no themes get applied at all.

I narrowed the bug down to my webpack configuration and specifically the `context` & `output.publicPath` options, but have not figured out where exactly the problem is.

### Steps to reproduce
1. Clone my repo: https://github.com/fiws/vue-material-bug-300
2. run `yarn install`
3. run `yarn dev`

### Which browser?
All Browsers, since 0.5.X i think (the big breaking theme change i guess)

### What is expected?
All components are styled using the default theme.

### What is actually happening?
No component has seems to have a theme at all. They have the ` md-theme-default` class, but that class does not apply any styles.

**Comment by marcosmoura** [comment]
The theme engine works on your browser. So this is probably not related to your webpack config.
Did you set up your themes correctly (following the new docs)? Did you see the [Breaking Changes](https://github.com/marcosmoura/vue-material/releases/tag/v0.5.0)?

**Comment by fiws** [comment]
i think so, i set no theme at all, so the default theme *should* be applied, no?

**Comment by marcosmoura** [comment]
Yes. Can you upload  part of your code in Codepen?

**Comment by fiws** [comment]
[yea](http://codepen.io/anon/pen/dNYber), but its basically a hello world app. It works on codepen.

As I said, i think it is build related.

**Comment by marcosmoura** [comment]
I will take a look at this and I report back, ok?

**Comment by korylprince** [comment]
@fiws Okay, so the error is actually pretty simple.

You're using the HtmlWebpackPlugin which inserts the built javascript into index.html. But you also included it with a script tag. So it is running your javascript twice.

You just need to remove the script tag from index.html and everything will work right.

**Comment by marcosmoura** [comment]
I will close this issue for now. If something comes up you can ask on the new [Gitter Channel](https://gitter.im/vuematerial). Thank you!

**Comment by fiws** [comment]
Thanks @korylprince that fixed it. I am pretty surprised that including all my js x2 did not cause any other major problems.. :O
