### ISSUE TITLE
Content is not rendered inside the Table Body

### ISSUE THREAD

**Issue by kayyyy** [marcosmoura/vue-material#301]
### Which browser & Versions?
vue 2.1.0, vue-material 0.5.2, vue-resource 1.0.3. Chrome & Firefox in OSX

#### Table.vue
```
<template>
<div>
  <md-table v-once>
    <md-table-header>
      <md-table-row>
        <md-table-head>Bild</md-table-head>
        <md-table-head>ASIN</md-table-head>
        <md-table-head>Preis</md-table-head>
        <md-table-head md-numeric>Ø Verkäufe p. Tag</md-table-head>
        <md-table-head md-numeric>Rank</md-table-head>
        <md-table-head>Kategorie</md-table-head>
      </md-table-row>
    </md-table-header>

    <md-table-body>
      <md-table-row v-for="article in articles">
        <md-table-cell><md-avatar><img :src="article.image"></md-avatar></md-table-cell>
        <md-table-cell>{{ article.asin }}</md-table-cell>
        <md-table-cell>{{ article.price }}</md-table-cell>
        <md-table-cell md-numeric>0</md-table-cell>
        <md-table-cell md-numeric>{{ article.rank }}</md-table-cell>
        <md-table-cell>{{ article.category }}</md-table-cell>
      </md-table-row>
    </md-table-body>
  </md-table>
</div>
</template>

<script>
export default {
  name: 'Table',
  data () {
    return {
      articles: {}
    }
  },
  created () {
    this.getAll()
  },
  methods: {
    getAll () {
      this.$http.get('http://seller.dev/api').then(function (response) {
        this.articles = response.data
      }, function (response) {
        console.log(response)
      })
    }
  }
}
</script>

<style lang="scss">
.md-table-cell-container img { max-height: 80px; }
</style>
```
I get the Data successfully which is bind to `this.articles`. The Objects are also there as the Screenshot of the VueDevtools shows.

But the Content from the `v-for` loop isnt`t loaded inside the Table as you can see.

![image](https://cloud.githubusercontent.com/assets/8193345/21745343/ef386608-d529-11e6-9e4c-05192aa6bd9f.png)

![image](https://cloud.githubusercontent.com/assets/8193345/21745347/fa1f9f00-d529-11e6-87f2-23b143f4002a.png)

What could be the Error?

**Comment by fabien-lg** [comment]
Hello,

2 ideas
- In your data, you define articles as an Object but you fill it with an Array, maybe that causes an issue ?
- This is what I currently use to fill a table, could you try it?
             `<md-table-body>
                <md-table-row
                        v-for="(row, rowIndex) in items"
                        :key="rowIndex"
                        :md-item="row">
                    <md-table-cell>
                        {{ row.property }}
                    </md-table-cell>
                </md-table-row>
            </md-table-body>`

**Comment by marcosmoura** [comment]
You cannot use `v-once` in the md-table component. The inner components like the `<md-table-row>` need the table instance to work. So to build a cheap table you can add v-once to the `<md-table-cell>`.
