### ISSUE TITLE
unfinished vue syntax output in browser

### ISSUE THREAD

**Issue by mikeashi** [marcosmoura/vue-material#304]
So I am new to Vue and to vue-material ...and I am testing with vue-material however I noticed that there is  unfinished vue syntax output in browser so I used v-cloak to solve the problem but now I have another problem which is the styling of the  vue-material components takes a couple of seconds before rendering to view  so how can I solve that

**Comment by marcosmoura** [comment]
You can't solve. You can only mask it. In fact this is not a problem. You can add a spinner to your page with a backdrop element. And when your application is fully loaded you can remove it. This is because some css is being downloaded before your scripts.
