### ISSUE TITLE
Fail to boot up the app, after upgrading to 0.6.0

### ISSUE THREAD

**Issue by despird-zh** [marcosmoura/vue-material#309]
hi marcosmoura, 

I cannot boot up the app after upgrading to 0.6.0 ver. bellow is my webpack dependencies:  "dependencies": {
    "v-media-query": "^1.0.3",
    "vue": "^2.1.8",
    "vue-material": "^0.6.0", 
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.3",
    "vuex": "^2.1.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.6.1",
    "autosize": "^3.0.20",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-es2017": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "chalk": "^1.1.3",
    "chokidar": "^1.6.1",
    "clipboard": "^1.5.16",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "element.scrollintoviewifneeded-polyfill": "^1.0.1",
    "eslint": "^3.13.0",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^1.7.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "highlight.js": "^9.9.0",
    "html-webpack-plugin": "^2.26.0",
    "json-loader": "^0.5.4",
    "node-sass": "^4.1.1",
    "optimize-js-plugin": "^0.0.4",
    "ora": "^0.4.0",
    "opn": "^4.0.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^4.1.1",
    "url-loader": "^0.5.7",
    "vue-hot-reload-api": "^2.0.7",
    "vue-html-loader": "^1.2.3",
    "vue-loader": "^10.0.2",
    "vue-router": "^2.1.1",
    "vue-style-loader": "^1.0.0",
    "vue-template-compiler": "^2.1.8",
    "webpack": "^1.14.0",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.15.0",
    "http-proxy-middleware": "^0.17.2",
    "webpack-merge": "^2.3.1"
  }
the browser console log:
Uncaught Error: Cannot find module "!!babel-loader!vue-loader/lib/selector?type=script&index=0!./mdTheme.vue"
    at eval (eval at <anonymous> (app.js:864), <anonymous>:7:21592)
    at Object.eval (eval at <anonymous> (app.js:864), <anonymous>:7:21734)
    at t (eval at <anonymous> (app.js:864), <anonymous>:6:292)
    at Object.defineProperty.value (eval at <anonymous> (app.js:864), <anonymous>:6:20165)
    at t (eval at <anonymous> (app.js:864), <anonymous>:6:292)
    at Object.eval (eval at <anonymous> (app.js:864), <anonymous>:6:27723)
    at t (eval at <anonymous> (app.js:864), <anonymous>:6:292)
    at Object.eval (eval at <anonymous> (app.js:864), <anonymous>:7:22263)
    at t (eval at <anonymous> (app.js:864), <anonymous>:6:292)
    at Object.e.exports.version (eval at <anonymous> (app.js:864), <anonymous>:6:687)

but if I rollback to 0.5.2 , it works well.

Did I miss some steps to upgrade to 0.6.0 ????

**Comment by badbrainz** [comment]
Same issue here.

`Uncaught Error: Cannot find module "!!babel-loader!vue-loader/lib/selector?type=script&index=0!./mdTheme.vue"`

**Comment by ascarpello** [comment]
Same issue.
Uncaught Error: Cannot find module "!!babel-loader!vue-loader/lib/selector?type=script&index=0!./mdTheme.vue"
vue-material.js: **7**

**Comment by lzuccaro** [comment]
Same issue here. I had to rollback to 0.5.2.

**Comment by petslane** [comment]
Same issue.
I installed  vue-material:
```
$ npm install --save vue-material
my-project@1.0.0 /home/petslane/tmp/wp2/my-project
└── vue-material@0.6.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
And inserted code to my app:
```
var Vue = require('vue')
var VueMaterial = require('vue-material')

Vue.use(VueMaterial)
```
Getting error in console:
`vue-material.js:7Uncaught Error: Cannot find module "!!babel-loader!vue-loader/lib/selector?type=script&index=0!./mdTheme.vue"(…)(anonymous function) @ vue-material.js:7(anonymous function) @ vue-material.js:7t @ vue-material.js:6Object.defineProperty.value @ vue-material.js:6t @ vue-material.js:6(anonymous function) @ vue-material.js:6t @ vue-material.js:6(anonymous function) @ vue-material.js:7t @ vue-material.js:6e.exports.version @ vue-material.js:6t @ vue-material.js:6(anonymous function) @ vue-material.js:6(anonymous function) @ vue-material.js:6n.(anonymous function).exports @ vue-material.js:612 @ vue-material.js:6t @ bootstrap 485d22f…:50(anonymous function) @ app.3a9aad9….js:formatted:34t @ bootstrap 485d22f…:50(anonymous function) @ app.3a9aad9….js:formatted:76t @ bootstrap 485d22f…:50(anonymous function) @ app.3a9aad9….js:formatted:10t @ bootstrap 485d22f…:50window.webpackJsonp @ bootstrap 485d22f…:21(anonymous function) @ app.3a9aad9….js:formatted:1`

**Comment by oldskool73** [comment]
Same here. Found that if I ...

```import VueMaterial from 'vue-material/dist/vue-material.debug';```

instead (note the '.debug') it works, if that helps anyone.

Only started using this project today, got updated about an hour after I started, then it broke... been a wild ride so far :)

**Comment by marcosmoura** [comment]
Oh God. I'm sorry about that. I will fix it in a couple hours
