### ISSUE TITLE
can't load version 0.6.1

### ISSUE THREAD

**Issue by alberanid** [marcosmoura/vue-material#311]
Hi,
I've switched to the latest version (from a working 0.5.x), and I got:

    ERROR in ./~/vue-material/dist/vue-material.js
    Module not found: Error: Cannot resolve module 'Vue' in /home/da/ibt2/node_modules/vue-material/dist
 @ ./~/vue-material/dist/vue-material.js 6:83-97

I include vue-material with:
    import Vue from 'vue';
    import VueMaterial from 'vue-material';
    import 'vue-material/dist/vue-material.css';

Am I doing something wrong, or is it a bug?

I've also tried removing the whole node_modules directory and rebuilding it with npm install, to no avail.

Thanks.

**Comment by marcosmoura** [comment]
Hi @alberanid 

Have you installed Vue properly?

**Comment by korylprince** [comment]
@marcosmoura I can confirm that I get the same message. If I import from vue-material/src/index.js and build vue-material into the bundle myself it works fine, but if I bundle the built js (normal and debug) from node_modules I'm getting the same message.

**Comment by bolerodan** [comment]
Just chiming in here. I seem to be not having any issues. I have updated to 0.6.1, using the new components fine. Very strange.

**Comment by marcosmoura** [comment]
@korylprince @alberanid 
Running on which build system, OS, Vue version? Webpack, Browserify or Rollup? With babel or another transpiler?

**Comment by korylprince** [comment]
@marcosmoura 

Arch Linux,
Vue 2.1.8
Webpack 1.14.0
Babel (core) 6.21.0

I'm wondering if it's a case sensitive thing. I'm digging now to see if I can identify what is going on.

**Comment by marcosmoura** [comment]
I'm running Arch Linux here too. With the same packages. I've tested in two different projects and created another based on Webpack 2. No problems :(

**Comment by korylprince** [comment]
Okay, then it's almost got to be a webpack thing. Can you post what webpack config you're using for the projects?

**Comment by marcosmoura** [comment]
Basically the Vue CLI template:
``` js
var path = require('path')
var webpack = require('webpack')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js'
  },
  resolveLoader: {
    root: path.join(__dirname, 'node_modules'),
  },
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      }
    ]
  },
  devServer: {
    historyApiFallback: true,
    noInfo: true
  },
  devtool: '#inline-source-map'
}

if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    })
  ])
}

```

**Comment by alberanid** [comment]
@marcosmoura : Ubuntu 16.04, npm 3.5.2, webpack 1.14.0.  If fails just tying to build the project, which. It's a standard config created by vue init webpack. Moving back to 0.5.2 make it works again.

Thanks for your help.

**Comment by korylprince** [comment]
I've found something...

Here's my current webpack resolve section:

    resolve: {
        alias: {
            "vue$": "vue/dist/vue.common.js"
        },
        extensions: ["", ".js", ".vue"]
    }

If I add `"Vue$": "vue/dist/vue.common.js"` (notice capital V) to the alias section I can compile and run everything. So there does appear to be some sort of case issue.. Still digging...

**Comment by marcosmoura** [comment]
Why do you need this alias?

**Comment by alberanid** [comment]
@marcosmoura : I can confirm @korylprince finding.  But no idea why it fix the issue.

**Comment by korylprince** [comment]
@marcosmoura It's from the Vue docs: 
https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by korylprince** [comment]
Okay, so I found what's causing the error message:

https://github.com/marcosmoura/vue-material/blob/aef7021375f0c55522b0942caca409a56192f56a/build/webpack/prod-lib.js#L50

Is there a reason why you're using `Vue` as the external instead of `vue`? Changing it to `vue` fixes the issue for me.

**Comment by marcosmoura** [comment]
Releasing another update. Im so sorry about so many updates :(

**Comment by marcosmoura** [comment]
@alberanid @korylprince The new version is working?

**Comment by lzuccaro** [comment]
It works now. Thank you.

**Comment by alberanid** [comment]
@marcosmoura : 0.6.2 works for me!  Thanks for the fix.
