### ISSUE TITLE
Error when change state "disabled" button after upgrade ^0.6.0

### ISSUE THREAD

**Issue by echr** [marcosmoura/vue-material#313]
Hi @marcosmoura , thanks before for the new components updates 👍 .

but since i upgrade the package to ^0.6.0, i've got error when enabling a disabled button by reactive data property. everything works fine in ^0.5.0

### Steps to reproduce
* md-button in **disabled** state 
* try to enabled the button by change a computed property data.
* error happen when trying to enabled it

<img width="849" alt="screen shot 2017-01-11 at 02 16 13" src="https://cloud.githubusercontent.com/assets/5493091/21822038/437d7962-d7a8-11e6-9595-328afe020e9c.png">

**Block Code**
- the button:

`<md-button class="md-raised md-primary" :disabled="submitDisabled" @click="process()">Process</md-button>`

- my computed property:

`submitDisabled() {
                return this.$store.getters.loadingStatus
            },`

### Which browser?
tested on chrome browser & Mac OS Sierra

### What is expected?
The button should be enabled without produce error.., from the error log, it shown that the new `<md-ink-ripple>` components have problem with the disabled md-button component.. is there any idea how to fix this?

**Comment by korylprince** [comment]
@marcosmoura I'll look into this if you haven't fixed it yet.
