### ISSUE TITLE
Vue.material.inkRipple = false not working

### ISSUE THREAD

**Issue by akubasa** [marcosmoura/vue-material#316]
I tried all variations, Vue.material.inkRipple = false in main.js
I also tried this.$material.inkRipple = false in instance, both values are not working.
this.material.inkRipple is false in Object but not working in browser, ripple effect is still working.

**Comment by marcosmoura** [comment]
Take a look at this [Pen](http://codepen.io/vue-material/pen/NdxXKy?editors=0010) here with the complete exemple. Thank you!

**Comment by akubasa** [comment]
well, I am using .vue single file components,
but no matter where I place the this.$material.inkRipple = false, it is not working,
it is setting the value to false, but the ripple effect ist still working, am I missing something?

        mounted: function () {
            console.log("here1")
            this.$material.inkRipple = false;
        },
        beforeCreate: function () {
            console.log("here2")
            this.$material.inkRipple = false;
        },
        created: function () {
            console.log("here3")
            this.$material.inkRipple = false;
        },
        beforeMount: function () {
            console.log("here4")
            this.$material.inkRipple = false;
        },
        beforeUpdate: function () {
            console.log("here6")
            this.$material.inkRipple = false;
        }

I added the lines to my main ->

/* eslint-disable no-new */
new Vue({
    el: '#app',
    router,
    render: h => h(App)
});

and also in all other vue instances, no chance for me to get this work.

**Comment by marcosmoura** [comment]
Can you upload your code to a repo? Let's discuss this on the new [Gitter Channel](https://gitter.im/vuematerial). Thank you!
