### ISSUE TITLE
Data Table

### ISSUE THREAD

**Issue by marcosmoura** [marcosmoura/vue-material#32]
Data tables display sets of raw data. They usually appear in desktop enterprise products.

Specs for [Data Tables](https://material.google.com/components/data-tables.html)

![Data Table](https://material-design.storage.googleapis.com/publish/material_v_9/0B3mOPoJlxiFhUTEwa21JUEtza0k/components_datatables_cards_tablecard.png)

**Comment by dacodekid** [comment]
@marcosmoura do we have a release date for 0.3.0 on sight?

**Comment by marcosmoura** [comment]
@dacodekid Yes. November 7. You can keep track of those dates in milestones. I'm expecting to launch a new milestone every 10~15 days. :) 

https://github.com/marcosmoura/vue-material/milestones

Thank you!

**Comment by dacodekid** [comment]
U beauty 👍  . Thx :)

**Comment by marcosmoura** [comment]
Already implemented and will be shipped on the very next release (v0.3.0)
