### ISSUE TITLE
Select component md-menu-class

### ISSUE THREAD

**Issue by filpineda** [marcosmoura/vue-material#323]
First off thank you for this amazing project.

Now I've been trying everything and its been great, but I can't seem to to make the the "md-menu-class" property of Select component to work. What I was trying to achieve is to use md-align-trigger and md-size on the select options. An example implementation will be much appreciated.

Thank you in advance and again amazing job on this project.

**Comment by marcosmoura** [comment]
Hi @filpineda 

the md-menu-class only apply a different class to the select container. What do you want to do with your select?

**Comment by filpineda** [comment]
Hi @marcosmoura 

I was trying to align the top of the select options container to the bottom of the select container by using md-menu-class="md-align-trigger" and to adjust the width of the select options container by using using md-size prop. I thought it would work since the md-select component uses md-menu as container of the select options iirc... 

Is that possible to achieve using md-menu-class?
