### ISSUE TITLE
Error on table pagination

### ISSUE THREAD

**Issue by Sarpedion** [marcosmoura/vue-material#326]
Greetings,

when I use pagination on a table, following errors are shown in console:

![image](https://cloud.githubusercontent.com/assets/16826299/21856781/7ffe18f8-d823-11e6-86eb-d9ec9b4e23a1.png)

To reproduce errors, official [table documentation](https://vuematerial.github.io/#/components/table) can be used (the table with pagination). Error is thrown when paging to the second page, and then paging to previous page. I've tested on Chrome and Firefox.

Furthermore, after updating to most recent version, if table moves, because I added more content or something on page, row borders glitch out. For example:

![image](https://cloud.githubusercontent.com/assets/16826299/21857266/28e958a0-d825-11e6-9bff-030c087c4827.png)

Unfortunately, I have not been able to reproduce this issue. I've noticed that on next render, borders are all properly aligned. I've noticed this issue only on chrome.
I know this might be a bit ambigous question, but what could cause such weird border behaviour?

**Comment by marcosmoura** [comment]
Related to #313
