### ISSUE TITLE
select label not reset when set v-model variable empty

### ISSUE THREAD

**Issue by pluschen** [marcosmoura/vue-material#333]
What is the proper way to reset select fields?
Issue similar to reset input label bug fixed in version 0.6.3.
See updated codepen http://codepen.io/anon/pen/qRZMbe, select label will not reset.

**Comment by korylprince** [comment]
I thought I had explicitly checked the select when it was fixed for md-input and it was working. I'll look into it.

**Comment by korylprince** [comment]
@pluschen 

Just so you know, when you updated your codepen for your other issue, you overwrote this one.

**Comment by pluschen** [comment]
@korylprince 
sure my fault :)
