### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by brsHunterX** [marcosmoura/vue-material#334]
I updated my project today with version 0.6.3, but when I run it returns the following error:

`Uncaught TypeError: Cannot read property 'toString' of undefined
    at e.default (eval at <anonymous> (http://localhost:8080/app.js:1698:2), <anonymous>:7:5084)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1698:2), <anonymous>:6:31353)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1698:2), <anonymous>:6:30975)
    at Array.forEach (native)
    at v (eval at <anonymous> (http://localhost:8080/app.js:1698:2), <anonymous>:6:30950)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1698:2), <anonymous>:6:31565)
    at Array.forEach (native)
    at g (eval at <anonymous> (http://localhost:8080/app.js:1698:2), <anonymous>:6:31537)`

However, if I go back to versions earlier than 0.6.0 the problem does not appear.

If you could help me, I'd be grateful. I would like to thank the incredible work = D

**Comment by korylprince** [comment]
Unless you provide a codepen example or a link to your code, it's going to be almost impossible to find out what's going on.

Could you provide one of those?

**Comment by brsHunterX** [comment]
This is the problem, I update the lib, run the npm run dev command and when the page opens in my browser, it gets totally blank with this error on console it is impossible to know where the error comes from ...

**Comment by brsHunterX** [comment]
However it only returns me the error in version 0.6.0 onwards, if I go back to previous versions it works perfectly.

**Comment by korylprince** [comment]
Is this private code? Can you put your full project on GitHub so someone can try to replicate your issue? As it stands, there's nothing to go on...

**Comment by brsHunterX** [comment]
Yes the project is from my company, which does not allow me to upload it in Github

**Comment by marcosmoura** [comment]
I can't help you without see the part of the code.
Which version you were using? Which Vue.js version? Which OS? Which env? Webpack? Browserify? Standlone? Have you checked the breaking changes?

**Comment by brsHunterX** [comment]
Sorry for the delay, but it seems that I discovered the problem, it happens that in the theme register I had some objects with the "hue" property declared and others without, this somehow generated this error. So I just added hue to all and the error stopped .

**Comment by brsHunterX** [comment]
An example that reproduces the error:

Vue.material.registerTheme({
'theme1': {
  primary: {
    color: 'blue-grey',
    hue: 900,
  },
  accent: {
    color: 'white',
  },
},
'theme2': {
  primary: {
    color: 'deep-orange',
  },
  accent: {
    color: 'white',
    hue: 500,
  },
},
})

**Comment by marcosmoura** [comment]
I will take a look at this ASAP. I will close this issue for now. thank you
