### ISSUE TITLE
select options are not hided when select is placed inside custom dialog

### ISSUE THREAD

**Issue by pluschen** [marcosmoura/vue-material#337]
When select component is placed in dialog, clicking outside the options doestn hide select options.
Even if you close dialog, select options remain still visible.  

http://codepen.io/anon/pen/qRZPZr

**Comment by marcosmoura** [comment]
Oh. That's bad! I will fix it! Sorry about that!

**Comment by pluschen** [comment]
@marcosmoura 
Thank you, you are making exceptional job! :+1:
