### ISSUE TITLE
MdInkRipple error in disabled watcher

### ISSUE THREAD

**Issue by bolerodan** [marcosmoura/vue-material#344]
### Steps to reproduce
 Put a :disabled attribute on md-button and toggle it on and off. When putting disabled = true, everything is fine, md-ink-ripple is removed as per the code, however, putting :disabled to false will result in an error
```
TypeError: Cannot read property 'parentNode' of null
```
### Which browser?
Chrome 55

### What is expected?
for md-ink-ripple to append itself back to its initial parent (in this case, md-button)
### What is actually happening?
Fails to attach it self back to its parent

This may be related to  #329  as well.
Looking through the code, the error is in the watcher of the disabled prop. When disabled is true, md-ink-ripple is destroyed, removed from parent. When switched to true, `this.init()` is executed, however at that point in time,` this.$el` is no longer attached to its parent, thus when calling `getClosestPositionedParent(`) in the `init()` function, there is no parent on `this.$el`

Either in the watcher for disabled, `this.$el` should be reinserted into `this.parentElement` before calling init().

I wish I had time to setup a PR but I was able to investigate this much. Thanks again for your awesome work.

**Comment by jonataswalker** [comment]
Related #343.

**Comment by korylprince** [comment]
This was already reported in #313 and fixed in PR #317 (using pretty much your code.) It should make it into version 0.6.4.

**Comment by bolerodan** [comment]
Maybe im reading the code wrong in PR #317 but does that seem to only do a null check and not re insert the md-ink element back into its parent? If I disable the the button, then re-enable it, the watcher for disabled will call init() because disabled will be false, then this.getClosestPositionedParent() with the new PR will return false thus not re-enabling md-ink ?

Perhaps I am reading that PR wrong.

**Comment by marcosmoura** [comment]
I will take a deep look into it. Thanks!

**Comment by korylprince** [comment]
@marcosmoura 

Currently in `init`, `this.parentElement` is always reset to `this.getClosestPositionedParent(this.$el.parentNode)`. Perhaps `this.parentElement` should only be set if it is not `null`.

I would do a PR, but obviously my last solution didn't fully solve the problem. I want to make sure I fully understand what's going on here.

**Comment by copitz** [comment]
@korylprince Your solution solved the problem but it is neither in current [master](https://github.com/marcosmoura/vue-material/blob/master/src/core/components/mdInkRipple/mdInkRipple.vue#L64) nor in [0.6.3](https://github.com/marcosmoura/vue-material/blob/v0.6.3/src/core/components/mdInkRipple/mdInkRipple.vue#L64)

@marcosmoura [Line 64 - 68](https://github.com/marcosmoura/vue-material/blob/master/src/core/components/mdInkRipple/mdInkRipple.vue#L64-L68) should be like

        const parent = element ? element.parentNode : undefined;

        if (!parent || parent.tagName.toLowerCase() === 'body') {
          return false;
        }

**Comment by jonataswalker** [comment]
My development is (kind of) stopped depending on `0.7.0` publishing. Same problem here.

**Comment by marcosmoura** [comment]
I was sick for those 13 days and I didn't have time to deal with so many issues. Sorry about that. I will fix that really soon.

**Comment by jonataswalker** [comment]
We are very grateful for your work @marcosmoura, sorry if it looked like some pressure. Indeed, there are so many issues but you a fast developer, impressive.

**Comment by marcosmoura** [comment]
No. It didn't look like that. Don't worry. Stay tuned. The new version will be delivered really soon. :)

**Comment by korylprince** [comment]
I've fixed this (I think) in the above mentioned commit, if you want to pull it. I used, in part the code from @copitz. In testing, this seems to completely resolve the issue.
