### ISSUE TITLE
Cannot read property 'indexOf' of undefined - md-select

### ISSUE THREAD

**Issue by elisangela89** [marcosmoura/vue-material#346]
Hello,
I have the following error when I use select with property "multiple" and the md-option with v-for.
“Cannot read property 'indexOf' of undefined “
My component is as follows:
http://codepen.io/CARLA001/pen/bgeoKZ
And I'm calling this way:

> 
`<template>`
` <div>`
       `<dsg-select` dsgpLabel="teste" :dsgpItens="dsgpItens"   
                             :dsgpVmodel="dsgpItens" :dsgpMultiplo="true" `:dsgpChange="teste()">`
       `</dsg-select>`
  `</div>`
`</template>`
`<script>`
import dsgSelect from './dsgSelect.vue'
export default {
  name: 'hello',
  data () {
    return {
      dsgpItens:[
                  {'id':'1', 'texto':'teste1'},
                  {'id':'2', 'texto':'teste2'},
                  {'id':'3', 'texto':'teste3'},
                  {'id':'4', 'texto':'teste4'},
      ]
    }
  },
  components:{
    dsgSelect
  },
   }
}
`</script>`

**Comment by marcosmoura** [comment]
Some points: 

- You cannot use something like `dsgpVmodel` to bind itens selected in your component. Vue.js works with one way bind.
- Why you need to create another component wrapping the `md-select`?

**Comment by juppdes** [comment]
Hello Marcos, 

We are creating our own components, just referencing them to the Vision Material, to create internal parameter standards, nomenclatures, and to keep the base library always original, with fewer problems with version updates.

The problem occurs in md-select only in the "multiple" option, when it does not, it works normally.

Other components we are achieving quietly.

Is there any way to resolve this issue?

**Comment by marcosmoura** [comment]
Can you create an example on Codepen with that error? The link that you sent is not working...

**Comment by juppdes** [comment]
Marcos... i create a repo here..    https://github.com/juppdes/mdSelect-trouble
Please make clone and run npm install.
When run (npm run dev) you will see that the first select, which is not multiple, brings in the line just below the selected content correctly.
In the second select, which is multiple, it selects correctly in the child component, but does not bring the value to the parent component (hello.vue).

**Comment by marcosmoura** [comment]
Please create upload your example at Codepen. It is hard to clone repositories only to see the code.
BTW, I created [one](http://codepen.io/vue-material/pen/oBzRRW) and the problem is with your markup. You were passing props in camel case instead of using dashes:
``` vue
<dsg-select dsgpLabel="teste" :dsgpItens="items" dsgpVmodel="selec" :dsgpId="selectDess"
              :dsgpMultiplo="true" dsgpName="selectDessis">
</dsg-select>
// should be
<dsg-select dsgp-label="teste" :dsgp-itens="items" dsgp-vmodel="selec"
              :dsgp-multiplo="true" dsgp-name="selectDessis">
```

Take a look at the Vue.js [documentation](https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case)

**Comment by juppdes** [comment]
Marcos,In your codepen example, in the html part, can you display the contents of the variable pointed to in v-model (select)?
