### ISSUE TITLE
Input fields rendering bug in IE11

### ISSUE THREAD

**Issue by jry2** [marcosmoura/vue-material#348]
### Steps to reproduce
Open https://vuematerial.github.io/#/components/input in IE11

### Which browser?
IE11 (Windows 7)

### What is actually happening?
There are several problems when rendered in IE11:
- Scrollbars displayed for some fields.
- Wrong * placement.
- Wrong error placement.

Note that version 0.6.2 cannot be switched to 0.6.3 in IE11, I'm receiving "404 File not found" page.

![input_problem](https://cloud.githubusercontent.com/assets/10026109/21944933/ea663002-d9d8-11e6-9258-04570e0682c6.png)

**Comment by marcosmoura** [comment]
I will take a look at this. Vue Material still lacks some tests on IE 10 and 11. Thanks for reporting that.

**Comment by SkaterDad** [comment]
I'm seeing the same error message placement in Firefox 51.0b14.

Adding `left: 0` to the `<span class="md-error">` element fixes it on my machine.
