### ISSUE TITLE
Grid Support

### ISSUE THREAD

**Issue by krisanalfa** [marcosmoura/vue-material#35]
I see that this package does not include grid system. It would be great if it supports grid system. Anyway, great work out there!

**Comment by marcosmoura** [comment]
I didn't scheduled yet but will be developed after release v0.3.0. I already have an API in mind. Will be something like:
``` html
<md-layout md-row>
  <md-layout md-row>

  </md-layout>

  <md-layout md-column>

  </md-layout>
</md-layout>
```

**Comment by marcosmoura** [comment]
You can check a temporary solution for grid system on #37

**Comment by krisanalfa** [comment]
I think that is the best solution for now. But I'm still waiting for official support. Thank for your great job out there!

**Comment by marcosmoura** [comment]
Sure! And it is only a few weeks of it's release. Thank you for waiting and be so early adopter on my project.
