### ISSUE TITLE
hide/close options api on md-select

### ISSUE THREAD

**Issue by mehyaa** [marcosmoura/vue-material#353]
Hi,

Can you expose a close function that closes the inner menu or a ref to inner menu itself (cause it has one). I'm adding an optional li element inside the select and opening a modal with its click but the options menu stays visible (as expected). If there is a close api which i can trigger i can close the menu manually.

**Comment by marcosmoura** [comment]
This is not going to be implemented. This cannot be done in the regular <select> and this library aims to be clean and the more close to the default components.
