### ISSUE TITLE
I can not access the md-select value

### ISSUE THREAD

**Issue by juppdes** [marcosmoura/vue-material#356]
In the codepen example, [SELECT](http://codepen.io/Jupp/pen/bgwPLX), I can not access the content returned from the md-select multi-selection in the HTML.
Please show me how to access the multiple content selected in the HTML part.

**Comment by marcosmoura** [comment]
You're creating a wrapper component. You should use v-model for that.
Please follow the [documentation](https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events) for custom components of Vue.js.
