### ISSUE TITLE
Select component not focusable with tab key

### ISSUE THREAD

**Issue by ascarpello** [marcosmoura/vue-material#358]
### Which browser?
Google Chrome v 55.0.2883.95 (64-bit) on Mac OS X Sierra
Firefox v 50.0 /  50.1.0 (64-bit) on Mac OS X Sierra
### What is expected?
Tabindex navigation between form fields
### What is actually happening?
tabindex attribute value is set to "-1"

### Reproduction Link
[http://codepen.io/asca/pen/ygVVXQ?editors=1010](url)

**Comment by marcosmoura** [comment]
I see. This will be done in #31 and #260. I will close this for now and I report back. Thank you!

**Comment by rcovell** [comment]
@marcosmoura wanted to check on the status of this.  I am on the latest code base and tabbing does not affect select components.

**Comment by rcovell** [comment]
@ascarpello were you able to find a resolution for this issue?
