### ISSUE TITLE
md-select native html5 form errors with required attribute

### ISSUE THREAD

**Issue by ascarpello** [marcosmoura/vue-material#359]
Hi, i have a simple form width some input and a select, all with the required attribute, but when i try to submit, the submit event not fire (if i fill or not the md-select) and i can't see the native html error handler to md-select and to all the required fields next to the select

### Which browser?
Google Chrome v 55.0.2883.95 (64-bit) on Mac OS X Sierra
Firefox v 50.0 /  50.1.0 (64-bit) on Mac OS X Sierra

### Reproduction Link
[http://codepen.io/asca/pen/ygVVXQ?editors=1010](url)

**Comment by vms82** [comment]
you didnt provided any data function for your v-models the following will fix your issue when added to the instance, also i suggest to go thrue vuejs.org docs and at least read the basics guide.
data() {
    return {
      movie:'',
      initialValue: '',
      
 }

**Comment by marcosmoura** [comment]
The snippet of @vms82 will fix your issue! Thank you!
