### ISSUE TITLE
SELECT component: displaying selected text (rather than value)

### ISSUE THREAD

**Issue by cheresier** [marcosmoura/vue-material#36]
Hey Marcos,

This is more of a question than an issue. I am using the SELECT component, but unlike the example you have in your docs (https://marcosmoura.github.io/vue-material/#/components/select) my value attribute for the items is different from the item text. However, the control seems to display the selected value rather than the text once an item is selected. Is there a way to display the text instead?

Attached is the screenshot of some sample code.
![2016-10-27 10_46_15-namevaluedropdown vue c__aewgit_entity-setup atom](https://cloud.githubusercontent.com/assets/18665877/19771973/b7259bc6-9c32-11e6-9f45-ac3e03f65b9d.png)

And here is what my screen looks like after I selected an item with Name "One"
![2016-10-27 10_47_28-inbox - daniel freink aew com - outlook](https://cloud.githubusercontent.com/assets/18665877/19772045/f159e7a2-9c32-11e6-94c2-08646ce42969.png)
I would prefer if it displayed the Name ("One") rather than the Value ("1"), as it does now.

Once again, thank you for the awesome library!

**Comment by marcosmoura** [comment]
Hey @cheresier.

I'm sorry about that. This is a bug. The ```<select>``` from HTML have this behaviour that you described and the ```<md-select>``` will have it too.
Right now you can't do this, unfortunately. I will fix and report on this on the issue #24 

Thank you! and sorry to make you wait a little longer to use this component properly.

**Comment by cheresier** [comment]
Sorry for the duplicate. One other thing I noticed (just FYI) is this. In my example, if you select the item with value 0 this is how it displays:
![2016-10-27 10_58_56-program manager](https://cloud.githubusercontent.com/assets/18665877/19772518/7ffc8130-9c34-11e6-8a57-b4e403320e3d.png)

Probably because it evaluates as boolean false. I am guessing it will be fixed in the next iteration as well, but I thought I'd let you know.

**Comment by marcosmoura** [comment]
Oh. Don't worry about the duplicate. And yes. You're right about that. It's evaluating as a Boolean in a silly and wrong way. This will be fixed on the next release. :D

**Comment by cheresier** [comment]
Sorry to bother again. Quick question (although I have a feeling that the answer to it may be obvious): is there a way to set the selected item programmatically? Something similar to the "selected" attribute on one of the options in the HTML select?
