### ISSUE TITLE
Table set height with fixed header option

### ISSUE THREAD

**Issue by bfrost2893** [marcosmoura/vue-material#361]
Awesome work so far!
Would it be possible to have an option on the table with a fixed height on the table and scrollable `tbody`? Material Design doesn't seem to say anything about it. But I find this is pretty common in most apps. 

Thanks,
Brad

**Comment by marcosmoura** [comment]
This will be done in the feature. I'm not going to prioritize it now, but I will keep this on track. Thank you!

**Comment by pablohpsilva** [comment]
How is this feature going? I tried to make it manually but I'm having some issues
