### ISSUE TITLE
TextArea error message not moving down

### ISSUE THREAD

**Issue by SkaterDad** [marcosmoura/vue-material#362]
### Steps to reproduce
Go to https://vuematerial.github.io/#/components/input and scroll down to the "Required and Errors" card.  The example of a textarea with error message below.

### Which browser?
Chrome on Android & Desktop, Firefox on Desktop, possibly more.

### What is expected?
I would expect the error message to shift down as the textarea height is resized.

### What is actually happening?
The error message stays in its original location.

Here's a screenshot of the bug in action:
![textarea_error_bug](https://cloud.githubusercontent.com/assets/13255599/22048909/af848478-dcf5-11e6-9c88-112378767a67.png)

### Potential fix
Watching the elements in Chrome's dev tools, it looks like the tab container `div` and `textarea` are both getting heights recalculated as you create new rows in the `textarea`.  Since the error `<span class="md-error">` is `position: absolute`, it also needs its `top: ## px` value updated as the `textarea` expands.

**Comment by SkaterDad** [comment]
I did some hacking around in `mdTextarea.vue` in the `development` branch, and was able to fix this.

This is probably not a great solution, but it illustrates what _can_ be done.

The code between the `// NEW CODE` comments searches the parent element for a child with `md-error` in its classes, then attaches an event listener to the `textarea` element on `autosize:resized`.  It then sets a new `top` value to the `md-error` element based on the new `offsetHeight` of the `textarea`.  I'm sure `clientHeight` could work also, depending on what your CSS can do.

```javascript
  export default {
    mixins: [common],
    watch: {
      value() {
        this.$nextTick(() => {
          autosize.update(this.$el);
        });
      }
    },
    mounted() {
      this.parentContainer = getClosestVueParent(this.$parent, 'md-input-container');

      if (!this.parentContainer) {
        this.$destroy();

        throw new Error('You should wrap the md-textarea in a md-input-container');
      }

      this.setParentDisabled();
      this.setParentRequired();
      this.setParentPlaceholder();
      this.setParentValue();
      this.handleMaxLength();

      if (!this.$el.getAttribute('rows')) {
        this.$el.setAttribute('rows', '1');
      }

      // START - NEW CODE
      const errorMessageElement = this.parentContainer.$el.querySelector('.md-error');
      const thisEl = this.$el;

      if (errorMessageElement) {
        this.$el.addEventListener('autosize:resized', function(args) {
          errorMessageElement.style.top = thisEl.offsetHeight + 20 + 'px';
        });
      }
      // END - NEW CODE

      this.$nextTick(() => {
        autosize(this.$el);
      });
    },
    beforeDestroy() {
      autosize.destroy(this.$el);
    }
  };
```

Let me know if I can be of any more help!

**Comment by marcosmoura** [comment]
Thank you for the workaround. I will fix this issue using css, with a bottom position instead of top.
