### ISSUE TITLE
Table Docs - broken pagination?

### ISSUE THREAD

**Issue by ackzell** [marcosmoura/vue-material#363]
### Steps to reproduce
1. Open up the docs at the Table section:
https://vuematerial.github.io/#/components/table

2. Scroll to the _Within cards with pagination_ example

3. Click on the *>* button at the pagination controls for the _Nutrition_ table

4. Click on the *<* button

### Which browser?

Chrome Version 55.0.2883.95 (64-bit)

### What is expected?
Pagination controls allow to visualize the changes on the presented table.

### What is actually happening?

All the functions for the Demo site break. Nothing is clickable anymore.
![image](https://cloud.githubusercontent.com/assets/601266/22051322/c318f462-dd07-11e6-9c74-3fe84c68f615.png)

**Comment by marcosmoura** [comment]
Duplicated #354
