### ISSUE TITLE
md-list-item secondary button submits form

### ISSUE THREAD

**Issue by mounsterjavi** [marcosmoura/vue-material#365]
Using a md-list with md-list-item inside a form with a secondary action assigned. Clicking the secondary action causes the form to submit.

could you add a default type="button" to buttons to prevent autosubmission of forms, thanks.

**Comment by bolerodan** [comment]
Hmm, looking at the source code for md-button, the default type is indeed "button" which you can also override on that specific button. Looking at the examples of a md-list-item with a secondary button action on the docs, it does indeed have type="button".

I just tested this in a <form> of my own, and my md-button does not submit my form and does indeed have type="button" as default. What version of vue-material are you using? can you show us an example of your form and methods used on your buttons?

**Comment by mounsterjavi** [comment]
Hi @bolerodan



the md-button is fine, the problem is using [expansion list](https://vuematerial.github.io/#/components/list), when the component is rendered the action button doesn't have type="button" attribute.

<li class="md-list-item md-list-item-expand" data-v-819e694e="">
<button class="md-button md-list-item-container">...</button>
</li>

https://jsfiddle.net/3h55pq9c/

**Comment by bolerodan** [comment]
@mounsterjavi 

Ah so more specifically, it's the expansion type. Also, it's always handy if you can just provide a fiddle right off the top (thanks for the fiddle afterwards though) as well as your vue-material version, web browser version etc so we're not dancing around sorting these things out.

Looking at the code it does indeed seem the expansion type is using createElement(button) and not providing a default type="" for that. Good find.
