### ISSUE TITLE
checkbox checked attribute

### ISSUE THREAD

**Issue by Shhu** [marcosmoura/vue-material#366]
Checkbox didnt update the "checked" attribute. When you submit a classic form with the checkbox components, the browser didnt send the checkbox because the checked attribute is missing.

http://codepen.io/anon/pen/WRRZJM

checked output is 
`<input type="checkbox" name="my-test1" id="my-test1" tabindex="-1" value="false">`
and should be
`<input type="checkbox" name="my-test1" id="my-test1" tabindex="-1" value="false" checked>`

**Comment by Shhu** [comment]
Same for `<select>` the html composant isnt synced and return an empty value.
Radio didnt work without a v-model (this one will be probably much more complicate)

Should i create an issue per component or its fine here cause its for the same use case?

**Comment by marcosmoura** [comment]
I added the checked attribute to the input checkbox.
Please open another issue for each subject. It will be easier to detect changes and to track what should be done. :)
