### ISSUE TITLE
[md-input] Cursor jumps to end of input after first edit

### ISSUE THREAD

**Issue by lee-frank** [marcosmoura/vue-material#367]
### Steps to reproduce
Any input after the first input will move the cursor to the end of the textfield. Seems to occur in md-input with a v-model. So for example, in the vue-material input documentation, inserting any character before the string "My initial value" will move the cursor to the end of "value".

### Which browser?
Chrome, vue-material 0.6.3, Vue 2.1.8

### Reproduction Link
You can try it in the vue-material documentation, in the "my initial value" example:
https://vuematerial.github.io/#/components/input

Codepen (same as the documentation)
http://codepen.io/anon/pen/oBBExK

Thanks for all your work so far!

**Comment by marcosmoura** [comment]
You're right. Nasty bug!

**Comment by scbizu** [comment]
It also causes the `Input with v-model` can not correctly write **chinese characters** . However, it works in FireFox .

**Comment by marcosmoura** [comment]
It's fixed and just waiting to be deployed along with the 0.7.0 version.
