### ISSUE TITLE
dialog property `md-click-outside-to-close` bug

### ISSUE THREAD

**Issue by Chandler9Wilson** [marcosmoura/vue-material#368]
Setting `md-click-outside-to-close` to `false` does not stop the dialog from closing when clicking outside the dialog.
* Here is a [codepen](http://codepen.io/Chandler9Wilson/pen/gggvmw) with the property on line 12

**Comment by marcosmoura** [comment]
You have to bind the value to the component:
`:md-click-outside-to-close="false"` instead of `md-click-outside-to-close="false"`. Note the colon...

**Comment by Chandler9Wilson** [comment]
Thanks for the quick response, I was trying to use a normal html attribute, for future reference I did not understand [dynamic props](https://vuejs.org/v2/guide/components.html#Dynamic-Props) were being used here. This was my fault I hope the link helps people in the future.

P.S. thanks for the great library
