### ISSUE TITLE
Custom theme,

### ISSUE THREAD

**Issue by elisangela89** [marcosmoura/vue-material#369]
How do I register a theme where I can change the class properties too, for example: In the "default" theme the md-list classes will have the blue background color and the md-list-item classes will have the black background color. I tried the following code and I was not successful:

Vue.material.registerTheme ({
   Default: {
        .md-list: {
            background: "blue"
         }
         .md-list-item: {
                 background: "black"
          }
     }
})

Grateful

**Comment by marcosmoura** [comment]
You are doing it wrong. First you need to define the theme:
``` js
Vue.material.registerTheme ({
  'listTheme': {
    background: 'blue'
  }
  'listItemTheme': {
    background: 'black'
  }
})
```

Then you use the theme attribute in the desired component.
``` vue
<md-list md-theme="listTheme">
  <md-list-item md-theme="listItemTheme"> ... </md-list-item>
</md-list>
```

Plase take a look in the theme documentation section: https://vuematerial.github.io/#/themes/dynamic-themes
