### ISSUE TITLE
[md-input] Can't listen native events

### ISSUE THREAD

**Issue by jtouzy** [marcosmoura/vue-material#371]
On md-input, developers can't listen input's native events like "v-on:focusout", "v-on:keyup", because of the "md-input" wrapper. Can we $emit the events when they're sended ?

I think it could be a performance problem (too much $emit phase) so I prefer ask for the feature before proposing a pull request.

Maybe the developer can register events that he needs and md-input can registers them on the fly ?

What do you think ?

**Comment by vivescere** [comment]
If I remember correctly, you can use @focus.native.

**Comment by johanbove** [comment]
I had the same question. Thank you for replying @vivescere . Can you please elaborate a little on how this would work? I'm trying this, but the event is not fired:

```
  <md-input-container>
     <label>Vorname</label>
     <md-input v-model="firstName" @keyup.enter="getStep(3)"></md-input>
  </md-input-container>
```

**Comment by johanbove** [comment]
Never mind. I found the correct event notation; Thanks!

```
<md-input-container>
   <label>Vorname</label>
   <md-input v-model="firstName" @keyup.enter.native="getStep(3)"></md-input>
 </md-input-container>
```
