### ISSUE TITLE
Do we have VUE CLI show casing marcosmoura/vue material framework?

### ISSUE THREAD

**Issue by donPuerto** [marcosmoura/vue-material#375]
This framework is freaking awesome, but it is nicer to have dedicated VUE CLI using marcosmoura/vue material framework.

**Comment by marcosmoura** [comment]
This will be developed. I'm going to close this issue, for now, but I will try to create this for the v0.9.0. For now you can use this initial boilerplate: https://github.com/marcosmoura/vue-boilerplate
