### ISSUE TITLE
md-hide inside md-toolbar

### ISSUE THREAD

**Issue by maesklaas** [marcosmoura/vue-material#376]
Hi,

I have a toolbar with some buttons. Now i am trying to hide those on small screens.
Just using md-hide-xsmall doesn't work and adding md-layout in and or around the md-toolbar, changes te look of the toolbar.

Any suggestions on how to get this working?

Thanks

**Comment by marcosmoura** [comment]
Just use as a class and it'll work. <md-button class="md-hide-xsmall"></md-button>.
I wil add this to the documentation soon.

**Comment by almaweb** [comment]
Hi,
I tried md-hide-large as class but doesn't work as it should because it hide element in small screen..
Thanks

**Comment by cotterjd** [comment]
I'm having the same problems trying to hide things within a toolbar...

**Comment by JacobGeoGeek** [comment]
@cotterjd have you found any solution for your problem, Cuz I have the same problem

**Comment by cotterjd** [comment]
https://stackoverflow.com/questions/54470689/why-isnt-md-xsmall-hide-class-hiding-the-div/54602209#54602209

**Comment by JacobGeoGeek** [comment]
> 
> 
> @JacobGeoGeek https://stackoverflow.com/questions/54470689/why-isnt-md-xsmall-hide-class-hiding-the-div/54602209#54602209

Nope its does not work with you're trying to hide some element when screen is medium large or xlarge.

**Comment by cotterjd** [comment]
@JacobGeoGeek what doesn't work on a medium - xlarge screen? can you post your code? what exactly are you trying to accomplish?

**Comment by JacobGeoGeek** [comment]
Nvm i add some Css queries in order to solve the problem thxs for the help
