### ISSUE TITLE
[md-radio]: md-value can't be assigned 0

### ISSUE THREAD

**Issue by polunzh** [marcosmoura/vue-material#378]
### Steps to reproduce
Set  `md-value`  to `0`, when binded model value is `0` the radio won't be selected.

### Which browser?
`chrome 55.0.2883.87 m (64-bit)`
`vue 2.1.8`
`vue-material 0.6.3`

### What is expected?
`md-value` can be assigned `0`

### What is actually happening?
I think the code:
``` javascript
'md-checked': this.value && this.mdValue.toString() === this.value.toString(),
```
the  `this.value` variable should be checked by another way.
[source code](https://github.com/marcosmoura/vue-material/blob/master/src/components/mdRadio/mdRadio.vue#L34)

### Reproduction Link
[jsfiddle](https://jsfiddle.net/btLc51t4/)

**Comment by marcosmoura** [comment]
In the reproduction link I could check all the radio.

**Comment by polunzh** [comment]
Sorry.
I mean when the `v-model` initial value is `0`, the radio can not be selected by default.
Did I get anything wrong?

**Comment by marcosmoura** [comment]
Oh. I see now. I will fix! Sorry about that!

**Comment by polunzh** [comment]
thanks!
