### ISSUE TITLE
md-file cannot open it with FileReader()

### ISSUE THREAD

**Issue by joelmandell** [marcosmoura/vue-material#379]
I am trying to open a file with md-file component. It is with an v-model="file".
When trying to read fr.readAsData(file) it does not work...

 execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

**Comment by mathieutu** [comment]
@joelmandell it's normal and it's about Vue and not the material package.
If you search that on google, you can find many explanations and tips :
Mine : 

```
<md-file v-model="pic1Name" @selected="onFileUpload($event, 'pic1')" required/>
```

```
onFileUpload(e, pic) {
    const file = e[0];
    if (file) {
        const reader = new FileReader();
        reader.onload = (e) => {
            const binaryString = e.target.result;
            this[pic] = btoa(binaryString);
        };
        reader.readAsBinaryString(file);
    }
},
```

You're welcome ! 😃

**Comment by joelmandell** [comment]
Thx a lot man!
I tried to search for an example, but my google-skills aren't that well apparently 😃
