### ISSUE TITLE
stop propagation on expandable list arrow icon

### ISSUE THREAD

**Issue by delueg** [marcosmoura/vue-material#382]
Hello,

when i click on the expandable-list-arrow-icon the click event bubbles to the list-item itself. Can i prevent this somehow?

see here http://codepen.io/delueg/pen/oBwbyo

**Comment by marcosmoura** [comment]
No. You can't. I will change that. Sorry about that.

**Comment by delueg** [comment]
No Problem - thank you for your great work.

I mean somehow it makes also sence to open the expandable list on click on the item in order of user experience. Maybe to make it configurable would be nice

**Comment by marcosmoura** [comment]
I'm not going to implement this in the list-item. There will be a new component called md-expansion-list for this kind of job.
