### ISSUE TITLE
Adding chips triggers form submit

### ISSUE THREAD

**Issue by d3radicated** [marcosmoura/vue-material#383]
### Steps to reproduce
Add an `md-chips` component inside a form with a submit handler

### Which browser?
Google Chrome 55.0.2883.87

### What is expected?
Form should not submit when adding chips.

### What is actually happening?
Chip is added and triggers form submit.

### Reproduction Link
https://codepen.io/dEradicated/pen/VPWeQy

**Comment by marcosmoura** [comment]
I will fix that soon. Sorry about that.

**Comment by Xilesun** [comment]
This issue seems still happen on version 1.0.0-beta-10.2.

**Comment by subham-king** [comment]
KIndly fix this issue. I just love VueMaterial but this issue is making things worse.
