### ISSUE TITLE
[Bug] Maxlength on input doesn't update when v-model update

### ISSUE THREAD

**Issue by mathieutu** [marcosmoura/vue-material#384]
### Which browser?
Last version of Vue and vue-material, all browsers

### What is expected?
The counter of maxlenth should update when the value of the field is updated (not only when typing).

### What is actually happening?
It doesn't hold the change at all!

### Reproduction Link
http://codepen.io/anon/pen/YNQWGX

Thank's.

**Comment by marcosmoura** [comment]
Oh. That's bad. I will fix that ASAP. Sorry!

**Comment by mathieutu** [comment]
Great! Thanks for the reactivity!
