### ISSUE TITLE
[md-gutter][bug] Gutter not working in any way

### ISSUE THREAD

**Issue by gazpachu** [marcosmoura/vue-material#385]
I've tried many different `md-gutter` definitions but none of them seem to be working.

http://codepen.io/gazpachu/pen/oBwzgY

**Comment by marcosmoura** [comment]
The gutter only works between columns. If you want an space before and after your content, you should do it manually.
Thanks!

**Comment by gazpachu** [comment]
@marcosmoura thanks for the clarification but I am still unable to add gutters between columns. Maybe the examples are wrong? Could you please check them? Thanks

**Comment by marcosmoura** [comment]
The md-gutter only accepts 8|16|24|40 values.
> The responsive grid focuses on consistent margin and gutter widths, rather than column width. Material design margins and columns follow an 8dp square baseline grid. Margins and gutters can be 8, 16, 24, or 40dp wide. Margins and gutters don’t need to be equal. For example, it’s acceptable to use 40dp margins and 24dp gutters in the same layout.

**Comment by sbefort** [comment]
I modified this codepen to match the docs.  If you do not specify a numeric value for the md-gutter, the class gets stripped from the final HTML.

http://codepen.io/anon/pen/yMvPKp

**Comment by luckylooke** [comment]
I am also not able to make md-gutter work

**Comment by pablohpsilva** [comment]
@sbefort change your code to :
```html
<div id="app">
  <md-layout md-gutter="8">
    <md-layout md-column>
     <!-- ... -->
  <!-- ... -->
</div>
```
