### ISSUE TITLE
[BUG] Support :href in md-button

### ISSUE THREAD

**Issue by mathieutu** [marcosmoura/vue-material#391]
```
<md-button class="md-icon-button" :href="myLink">
      <md-icon>get_app</md-icon>
</md-button>
```
The `:href` tag is not supported as a link, so we can't load link from variable.. 😢 

if I do 
```
<md-button class="md-icon-button" href="myLink">
      <md-icon>get_app</md-icon>
</md-button>
```

I will have a simple `a href="myLink"` in html.

Thanks!

**Comment by mathieutu** [comment]
Ok, apparently this is apparently working, I don't know why I had this problem.
Sorry !

**Comment by marcosmoura** [comment]
Take a look at this pen: http://codepen.io/vue-material/pen/apwMOQ
