### ISSUE TITLE
Pressing tab key on the tab component messes up the layout

### ISSUE THREAD

**Issue by sqal** [marcosmoura/vue-material#392]
### Which browser?
Any

### What is expected?
When the tab content is focused and user hits tab key, the content should not switch.

### What is actually happening?
Layout is messed up

![img1](http://image.prntscr.com/image/b6c7b4c28e5843c38d771e53b2b99646.png)

### Reproduction Link
https://vuematerial.github.io/#/components/tabs>

- Click on the text in the first tab
- Click tab key
- You should see something similar as in the screenshot above

**Comment by marcosmoura** [comment]
Oh. That is just crazy, hahaha. I'm going to fix that on #31 
Thank you for reporting that. :)
