### ISSUE TITLE
[Feature Request] Allow putting md-input inside of a md-toolbar

### ISSUE THREAD

**Issue by Morgul** [marcosmoura/vue-material#395]
Currently, if you want to put a `md-input` inside of a toolbar, you end up with unexpected behavior:

![image](https://cloud.githubusercontent.com/assets/770655/22266792/ed3a0a80-e246-11e6-9b72-8a9f0330d4e2.png)

What I would expect, is something more along the lines of:

![image](https://cloud.githubusercontent.com/assets/770655/22266949/918f73ea-e247-11e6-95e0-86dc7f715e68.png)

The issues that I see here are:

1) The input needs to theme appropriately.
2) By default, inside a toolbar, it should set itself to `flex: 1`, or similar.

While I'm not against having to do _some_ work to do this, it's a natural scenario when you want to filter the contents of a list to put it in a card, with a toolbar. Other CSS frameworks make this very easy, I'd like to see the same level of ease in VueMaterial.

**Comment by marcosmoura** [comment]
You're correct. Should have a better styling. I will fix that.
I'm going to create a search-bar component too, but on the future.

> The input needs to theme appropriately. By default, inside a toolbar, it should set itself to flex: 1, or similar.

I don't think so. You can still use md-layout inside the md-toolbar, for example.
``` vue
<md-layout md-tag="md-toolbar></md-layout>
<!-- or -->
<md-toolbar>
  <md-input-container class="md-flex"></md-input-container><!-- This is actually a hack, but will work -->
</md-toolbar>
```

Thanks!

**Comment by Morgul** [comment]
@marcosmoura It was only after thinking about this that I realized that the answer really is to just use `md-layout` inside the toolbar. Perhaps an example of that added to the toolbar docs?

**Comment by marcosmoura** [comment]
Sure. I will add that. But the themes still doesn't match. I will fix that an then a return back with the example. Thank you!

**Comment by mcfarljw** [comment]
Can you update the code example on the website? I'm seeing an input field on the first example, but the code doesn't seem to have been updated.

<img width="455" alt="screen shot 2017-04-19 at 2 27 39 pm" src="https://cloud.githubusercontent.com/assets/4167341/25166195/b031c6c4-250c-11e7-8bd3-0e3302c08b3a.png">
<img width="450" alt="screen shot 2017-04-19 at 2 29 49 pm" src="https://cloud.githubusercontent.com/assets/4167341/25166196/b0324248-250c-11e7-896e-a08572874902.png">

**Comment by guanzo** [comment]
Can we get an official example of input inside toolbar?
