### ISSUE TITLE
MdInkRipple laggy scroll

### ISSUE THREAD

**Issue by antonelepfl** [marcosmoura/vue-material#396]
### Steps to reproduce
I have just added the md-ink-ripple in a single page component and repeat this component several times from a parent component.
### Which browser?

Chrome 55
### What is expected?
If you scroll the page has lag 
### Reproduction Link

In this commit I had to remove it https://github.com/antonelepfl/usecases/commit/61c99f12c55852e92284d8a30926e766487bf758 before it was laggy.

### Thank you for your hard work and time

**Comment by marcosmoura** [comment]
This is really strange. The md-ink-ripple don't use any scroll events. Can you create an example on Codepen?
