### ISSUE TITLE
Pagination Error

### ISSUE THREAD

**Issue by d3radicated** [marcosmoura/vue-material#398]
### Steps to reproduce
1. Go to demo of table component.
2. On the demo of "Within cards with pagination", go to the next page then back to the previous page.

### Which browser?
Google Chrome 55.0.2883.87

### What is expected?
No errors are shown. Other controls are working.

### What is actually happening?
After pressing the previous page button, an error occurs and all of the controls don't work anymore.
[Imgur](http://i.imgur.com/jTCNXEG.png)

### Reproduction Link
https://vuematerial.github.io/#/components/table

**Comment by Phanu282003** [comment]
I have the same issue also

**Comment by marcosmoura** [comment]
Related to #399 #397 #192
