### ISSUE TITLE
[Feature Request] Prevent Auto-Collapse In Expansion Lists By Adding Collections

### ISSUE THREAD

**Issue by Cadienvan** [marcosmoura/vue-material#407]
Hi everyone,
as shown in your documentation here:
https://vuematerial.github.io/#/components/list
Vue Material gives you a chance to create expansion lists, which in fact is a great component to use for fancy md side menus.

What I think is missing is the possibility to define if, by clicking on an expandable item, other ones should close. I could easily find myself in a situation where I would allow my users to open two menus and right now I can't do that.

It could be nice to have some sort of `md-collection` which can define a set of expandable lists and group them together, making them close each other when one of the same collection needs to be opened.

This way, we could end up with something like this:
```
<md-list>
    <md-list-item md-collection="collection1">
       <!--List Item-->
      <md-list-expand>
        <md-list>
          <!--List Item-->
          <!--List Item-->
          <!--List Item-->
        </md-list>
      </md-list-expand>
    </md-list-item>
    <md-list-item md-collection="collection1">
       <!--List Item-->
      <md-list-expand>
        <md-list>
          <!--List Item-->
          <!--List Item-->
          <!--List Item-->
        </md-list>
      </md-list-expand>
    </md-list-item>
    <md-list-item md-collection="collection2">
       <!--List Item-->
      <md-list-expand>
        <md-list>
          <!--List Item-->
          <!--List Item-->
          <!--List Item-->
        </md-list>
      </md-list-expand>
    </md-list-item>
    <md-list-item md-collection="collection2">
       <!--List Item-->
      <md-list-expand>
        <md-list>
          <!--List Item-->
          <!--List Item-->
          <!--List Item-->
        </md-list>
      </md-list-expand>
    </md-list-item>
    <md-list-item md-collection="collection2">
       <!--List Item-->
      <md-list-expand>
        <md-list>
          <!--List Item-->
          <!--List Item-->
          <!--List Item-->
        </md-list>
      </md-list-expand>
    </md-list-item>
</md-list>
```

Which allows me to put first two items in a collection, last three in another one, and to open one element for every collection.

Thanks,
Michael.

**Comment by marcosmoura** [comment]
I have to think about that better. An md-collection is hard to reason about and can lead to some errors. I agree that an "accordion" like component should be developed, but the best component for this is the **Expansion Lists**.

https://material.io/guidelines/components/expansion-panels.html

**Comment by Cadienvan** [comment]
Yes, maybe you could separate "Expansion Lists" and "Accordions" so they could behave in a similar way, they can respect Material Design Guidelines and even give flexibility..
