### ISSUE TITLE
[Feature Request] Clickable md-list left-sided icon

### ISSUE THREAD

**Issue by Cadienvan** [marcosmoura/vue-material#408]
Hi everyone,
I was using list component (https://vuematerial.github.io/#/components/list), and found a missing feature it could be nice to have:
Right now we can apply click effects only on right-sided icons, but applying same classes and HTML to the left-side breaks the view.

I'm using a portion of sample code provided in your guide:
```
<md-list class="md-dense">
    <md-list-item>
        <md-button class="md-icon-button md-list-action">
            <md-icon>chat_bubble</md-icon>
        </md-button> <span>Inbox</span>
    </md-list-item>
    <md-list-item>
        <md-icon @click="alert('Hello World!');">move_to_inbox</md-icon> <span>Inbox</span>
    </md-list-item>

    <md-list-item>
        <md-icon>send</md-icon> <span>Sent Mail</span>
    </md-list-item>

    <md-list-item>
        <md-icon>delete</md-icon> <span>Trash</span>
    </md-list-item>

    <md-list-item>
        <md-icon>error</md-icon> <span>Spam</span>

        <md-divider class="md-inset"></md-divider>
    </md-list-item>
</md-list>
```

If you try to replicate this code, you'll notice first element (The one with an md-button) breaks layout.
![image](https://cloud.githubusercontent.com/assets/5492927/22328250/8539f532-e3bb-11e6-8645-0156246a7cf6.png)

I also tried packing it inside an md-avatar component, but it doesn't solve the issue.
As you can see, I put a click effect on an md-icon, but it doesn't trigger at all, so I can't use that.

It would be nice to have same appearance of an md-icon, but with an md-button applied to it, in order to benefit from javascript events attached to it.

Thanks,
Michael.

**Comment by marcosmoura** [comment]
Fair. I'm going to develop this too. Thank you!

**Comment by marcosmoura** [comment]
Due to the button size and the icon placement, the md-list-action, if placed as the first child, will be aligned as an md-avatar.
