### ISSUE TITLE
Type error on "route-navigate" by @click on md-button

### ISSUE THREAD

**Issue by delueg** [marcosmoura/vue-material#409]
Hello,

i get 

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined
    at VueComponent.getClickPosition

when i use an md-button to navigate to another route with vue-router

like

`<md-button @click="$router.push('/another_route')" md-theme="default" class="md-primary md-raised">navigate</md-button>`

i think it has something todo with the ripple effect wants to render on a button which is not there anymore.

**Comment by marcosmoura** [comment]
This is because of the new ripple component. I'm going to fix it.
