### ISSUE TITLE
href in md-menu-item

### ISSUE THREAD

**Issue by romangit** [marcosmoura/vue-material#418]
Hi Marcos,
I'm very grateful for your project.

You wrote
> The md-menu-item accepts the href property. The output will be the `<a>` tag.
https://github.com/marcosmoura/vue-material/issues/239

But, It's not working
http://codepen.io/anon/pen/XpVJBO

**Comment by marcosmoura** [comment]
Oh. That's bad. I found the problem. I will fix in the next version.
