### ISSUE TITLE
Grey inputs on all themes in md-primary card background

### ISSUE THREAD

**Issue by cve** [marcosmoura/vue-material#421]
Hi,

first of all, thank you for your work. I try to make simple login form which is in "card" with primary background, but the inputs are gray instead of white. If I've misunderstood themes guide, could you please show me an example of how to make these inputs white?

p.s. how to stretch the card such as 100% of it's parent width without inline style but with flexbox of vue-material?

### What is expected?
The inputs to be white

### What is actually happening?
The inputs are gray

### Reproduction Link
http://codepen.io/cve/pen/ZLryop

**Comment by marcosmoura** [comment]
This is an good improvement to do. I'm going to fix that.
To fix your second question: http://codepen.io/vue-material/pen/MJVgEz
