### ISSUE TITLE
May I know what components are included inside Vue Material Core

### ISSUE THREAD

**Issue by g0ld3lux** [marcosmoura/vue-material#423]
I know we can import components by piece 

but i wanna know what is the core components

what does it include?

does it include layout? typography themes?

thanks for the reply

**Comment by Blizzke** [comment]
You can simply open up the folder in your node_modules, you have the source code:
<img width="274" alt="screen shot 2017-02-01 at 09 21 11" src="https://cloud.githubusercontent.com/assets/231572/22499557/e0a5d514-e85f-11e6-872f-fd3cdefd0b7b.png">

**Comment by marcosmoura** [comment]
I'm going to write this on the documentation. On the future only the theme engine will be part of the core.
