### ISSUE TITLE
Md-layout not working with md-card-media-cover

### ISSUE THREAD

**Issue by fergardi** [marcosmoura/vue-material#424]
Hello.

I was trying to use md-layout with md-card md-card-media-cover, and it dissapears completely as soon as it gets under md-layout. I think it's something related to the recalculation of the image widht and height by javascript (console gives 0x0).

Working:
```pug
md-card(md-with-hover)
  md-card-media-cover(md-solid)
    md-card-media(md-ratio="16:9")
      md-image(md-src="image.png")
    md-card-area
      md-card-header
        .md-title Title
        .md-subhead Subtitle
```
Not working:
```pug
md-layout(md-gutter)
  md-layout(md-flex-xsmall="100", md-flex-small="50", md-flex-medium="33")
    md-card(md-with-hover)
      md-card-media-cover(md-solid)
        md-card-media(md-ratio="16:9")
          md-image(md-src="image.png")
        md-card-area
          md-card-header
            .md-title Title
            .md-subhead Subtitle
```

Tested with Chrome 55+.

**Comment by marcosmoura** [comment]
Can you try that:

``` pug
md-layout(md-gutter)
  md-layout(md-tag=md-card", "md-with-hover", "md-column", "md-flex-xsmall="100", md-flex-small="50", md-flex-medium="33")
    md-card-media-cover(md-solid)
      md-card-media(md-ratio="16:9")
        md-image(md-src="image.png")
      md-card-area
        md-card-header
          .md-title Title
          .md-subhead Subtitle
```

**Comment by fergardi** [comment]
Still no luck.

http://codepen.io/fergardi/pen/NdzoOd

Thanks.

**Comment by marcosmoura** [comment]
The problem is not related to md-layout, but the way that md-card-media-cover try to load the image. Right now only works for images inside the same domain, due to some cross domain requests. I will change this behaviour.

**Comment by Linzdigr** [comment]
Hi, same problem here, I switched on branch develop but still have the following when loading image from md-image with content located on a subdomain:

> Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
>     at HTMLImageElement.t.onload
