### ISSUE TITLE
md-select inside md-dialog does not close properly on escape or click outside

### ISSUE THREAD

**Issue by dohomi** [marcosmoura/vue-material#426]
### Steps to reproduce
open dialog, open md-select and then try to close the select without choosing a value

### Which browser?
Tested in current Chrome on Mac

### What is expected?
closing a `md-select` with click outside or escape key

### What is actually happening?
click outside does close the dialog but not the md-select

### Reproduction Link
http://codepen.io/anon/pen/PWRJZG

**Comment by marcosmoura** [comment]
I'm testing with Chrome and Mac too and I could close the select. Which other steps did you do?

**Comment by stbaer** [comment]
It's also not closing for me (Chrome/Mac). In  Codepen: Primary Button -> Select -> click outside => Options stay open, only dialog and backdrop are gone.

**Comment by marcosmoura** [comment]
@stbaer This was fixed and will be on 0.7.0

**Comment by dohomi** [comment]
Great!
