### ISSUE TITLE
md-textarea with maxlength not writable

### ISSUE THREAD

**Issue by deulos** [marcosmoura/vue-material#43]
Setting maxlength in md-textarea resets whatever it is typed when binded to non initialized data. Example:

`<md-textarea v-model="foo.description" maxlength="255"></md-textarea>`

```
data() {
  return {
    foo: {}
  }
}
```

Anything typed in the textarea is deleted within the next milliseconds, the problem dissapears when the attribute "maxlength" is removed.

On the other side, if you initialize the value it lets you write beyond the maxlength

**Comment by marcosmoura** [comment]
Oh. Sorry. I will take a look at this! Thank you for reporting that.

**Comment by marcosmoura** [comment]
Already implemented and will be shipped on the very next release (v0.3.0)
