### ISSUE TITLE
Any way to disable auto-change md-switch state

### ISSUE THREAD

**Issue by ivictbor** [marcosmoura/vue-material#433]
Hi. vue-material is awsome! 
But I faced with some task when I need to confirm changing `md-switch` state, for example using `yes`,`no` in `md-dialog`.
So I need to prevent automatic changing the state and then when user press `yes` in dialog set it programmably to `v-model` field.
I trued to use `$event.preventDefault()`, but in `$event` is boolean ( `0.6.3` version)

```html
<md-switch  @change="switchCheck($event)"></md-switch>
```
```js
methods: {
  switchCheck(event) {
    console.log(event) //true or false, so we can't prevent it
    // event.preventDeault()
  }
}
```
Is it bug? Have someone another ideas (even crazy workarounds ) how to implement confirmation?

**Comment by igor-ribeiro** [comment]
What happens is, the component has an internal state, so, even if you manually update the value and pass it via props, every time you click on the switch it will update its internal state and will notify you. For now I don't think it's possible to do what you want, but I can be wrong.

**Comment by igor-ribeiro** [comment]
The ugliest workaround:

```vue
<md-switch :value="checked" @change="switchCheck" ref="switch"></md-switch>
```

```js
methods: {
  switchCheck(value) {
    if (value === this.checked) return;

    if (confirm('Are you sure?')) {
      this.checked = value;
    } else {
      this.$refs.switch.$el.querySelector('.md-switch-container').click();
    }
  }
}
```

**Comment by ivictbor** [comment]
Issue was in `emit` call from mdSwitch.vue, 
```js
this.$emit('change', this.checked, $event);
``` - first argument passed as $event to onchange scope, but here first argument is bool `state`. Also there where no logic to preventDefault. 
Created pull-request with possible solution https://github.com/marcosmoura/vue-material/pull/435
