### ISSUE TITLE
md-total attribute of md-table-pagination not being reactive

### ISSUE THREAD

**Issue by deulos** [marcosmoura/vue-material#437]
### Steps to reproduce
Just create a `md-table-card` with a `md-table-pagination` and assign `:md-total` to a component var and initialize it to 0, then change it to whatever and the "next page" button will not be activated.

### Which browser?
Chrome browser, Vue 2.1.10, Vue Material 0.6.3 in Windows

### What is expected?
If initially I just set data and total items to 1 page and then update the :md-total var with a number that needs more pages, the "next page" button should be activated

### What is actually happening?
The "next page" button remains disabled

### Reproduction Code
    ...
    <md-table-pagination
        :md-size="params.limit"
        :md-total="totalUsers"
        :md-page="params.offset + 1"
        md-label="Rows"
        md-separator="of"
        :md-page-options="[5, 10, 25, 50]"
        @pagination="load">
    </md-table-pagination>
    ...

    export default {
        data() {
            return {
                users: [],
                totalUsers: 0,
                params: {
                    limit: 20,
                    offset: 0
                }
            }
        },

        created() {
            this.load();
        },

        methods: {
            load(pagination) {
                if (pagination) {
                    this.params.limit = pagination.size;
                    this.params.offset = (pagination.page - 1) * this.params.limit;
                }

                this.$http.get(baseUrl +'/users', {
                    params: this.params

                }).then((response) => {
                    this.users = response.data.users;
                    this.totalUsers = response.data.total_users;

                }, (response) => {
                    this.$alerts.addError(response.data.error);
                });
            }
        }
    }

**Comment by marcosmoura** [comment]
The md-table have a lot of problems. I will create a new one from scratch, and this issue will be fixed. I will close it for now, and when I release the new component I get back here with an feedback. Sorry about that. :(
