### ISSUE TITLE
Incorrect position of character counter for textarea

### ISSUE THREAD

**Issue by ikskoder** [marcosmoura/vue-material#438]
### Steps to reproduce
Just visit official demo page ([link](https://vuematerial.github.io/#/components/input)) and type some lines in the textarea with character counter.
Screenshot:
![1 2](https://cloud.githubusercontent.com/assets/25547100/22618049/e8c9e626-eadb-11e6-80db-c50cfbc7af2a.png)

### Which browser?
All of them are latest at the moment
- Google Chrome 56.0
- Mozilla Firefox 51.0
- Opera 42.0

### What is expected?
I think character counter should be under the textarea.
Something like this (I've set it manually with Chrome dev tools):
![1 2](https://cloud.githubusercontent.com/assets/25547100/22618071/6d4432c6-eadc-11e6-891b-32dbdaf4d34a.png)

**Comment by marcosmoura** [comment]
Duplicated #416
