### ISSUE TITLE
Incorrect position of validation message for input and textarea in Mozilla Firefox

### ISSUE THREAD

**Issue by ikskoder** [marcosmoura/vue-material#439]
### Steps to reproduce
Just visit official demo page ([link](https://vuematerial.github.io/#/components/input)) using Firefox browser.
Screenshot:
![395](https://cloud.githubusercontent.com/assets/25547100/22618204/67856e7e-eadf-11e6-8fa0-62bd314af7b3.png)

### Which browser?
Mozilla Forefox 51.0 (latest)

### What is expected?
It should work in Firefox like it works in Chrome/Opera:
![396](https://cloud.githubusercontent.com/assets/25547100/22618220/ad5fc0c0-eadf-11e6-8367-e63a94bd88ec.png)

**Comment by marcosmoura** [comment]
Duplicated #362
