### ISSUE TITLE
Themed custom styles

### ISSUE THREAD

**Issue by alphaelf** [marcosmoura/vue-material#444]
hi,
my question is about theme engine.
is possible to themed extra style in vue components?

like in `Example.vue` file:
```html
<template></template>
<script></script>
<style lang="scss">
.navbar{
    background-color: $backgroundColor; //this color followed by active theme!
}
</style>
```
> updated:

or better way add some helper class like: 
`md-primary-background` and `md-primary-color`  or `md-primary-theme` that have both color and background.

how about  this?

**Comment by marcosmoura** [comment]
Not right now. In the future the theme engine will support sass or post css.

**Comment by joshbodine21** [comment]
How far out (estimated) will it be before the theme engine is more advanced and will support sass?

**Comment by CharlesKumar** [comment]
custom styles would be a better option. i wasn't able to use colors.css as vue-material is overwriting the properties of the color.css css's rules
