### ISSUE TITLE
vue-material.js?ec92:6 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by xrr2016** [marcosmoura/vue-material#448]
my code
```
  <swiper :options="swiperOption" ref="mySwiperA">
          <swiper-slide v-for="story of topStories">
              <md-card>
                <md-card-media-cover md-text-scrim>
                  <md-card-media md-ratio="16:9">
                    <img :src="story.image | imageUrlPrefix">
                  </md-card-media>
                  <md-card-area>
                    <md-card-header>
                      <div class="md-title">{{ story.title }}</div>
                    </md-card-header>
                  </md-card-area>
                </md-card-media-cover>
              </md-card>
          </swiper-slide>
          <div class="swiper-pagination"  slot="pagination"></div>
        </swiper>
```
I dont understand why it happened,and swiper did not render.

**Comment by marcosmoura** [comment]
This is because your image is not on the same domain. The getImageData method rely on a Canvas solution, and, for security, the browser don't allow reading images from external sources. I will fix that. Related to #424

**Comment by Andkoo** [comment]
I am loading an image from my src/assets/images folder, yet I still get the same error. This is so frustrating.

**Comment by Samuell1** [comment]
Same error if i testing on localhost, Its fix on the way?

**Comment by johannkm** [comment]
Same error with an image from src/assets

**Comment by gonzaloplaza** [comment]
Same error, just when trying to put the card with image inside a <md-gutter> 

`<md-layout md-gutter>
                <md-layout md-flex-small="100" md-flex-medium="50" md-hide-xsmall>
                    <md-card>
                        <md-card-media-cover md-solid>
                            <md-card-media md-ratio="1:1">
                                <img src="/images/card-sky.jpg" alt="Skyscraper">
                            </md-card-media>

                            <md-card-area>
                                <md-card-header>
                                    <div class="md-title">Title goes here</div>
                                    <div class="md-subhead">Subtitle here</div>
                                </md-card-header>

                                <md-card-actions>
                                    <md-button>Action</md-button>
                                    <md-button>Action</md-button>
                                </md-card-actions>
                            </md-card-area>
                        </md-card-media-cover>
                    </md-card>
                </md-layout>
                <md-layout md-flex-small="100" md-flex-medium="50" md-hide-xsmall>
                    md-flex-medium="50" <br>
                    md-hide-xsmall
                </md-layout>
            </md-layout>`

However, Image and card are working outside the <md-gutter> layout

any idea?

**Comment by iboying** [comment]
The issue has fixed when I romove `md-ratio` paramete.
