### ISSUE TITLE
Is there parallax effect?

### ISSUE THREAD

**Issue by nucamoz** [marcosmoura/vue-material#451]
Hello guys. Thank you for awesome code. 

All is perfect but I can't see parallax effect. Is there is one? May be it's in plans? Thank you.

**Comment by marcosmoura** [comment]
Parallax effect?

**Comment by fergardi** [comment]
Would be a cool feature to add, such as there is a md-image-cover for images.

http://www.w3schools.com/howto/tryhow_css_parallax_demo.htm

**Comment by dohomi** [comment]
I think @nucamoz means somethink like this one: https://vuetifyjs.com/components/parallax

**Comment by marcosmoura** [comment]
Yeah. I know. I think that parallax is cool, but working with scroll events can be a performance issue. I think that, on the new structure templates (on #453) this can be achieve, but on the feature. I will close this issue for now and I will open it later.

**Comment by zcyzcy88** [comment]
Use pure CSS, avoid performance issue:
https://developers.google.com/web/updates/2016/12/performant-parallaxing
