### ISSUE TITLE
md-select not working with click on md-option since v0.7.0

### ISSUE THREAD

**Issue by dohomi** [marcosmoura/vue-material#454]
### Steps to reproduce
Select any option inside of `md-select`

### Which browser?
current Chrome on Mac OSX

### What is expected?
Md-Select should select an option if click on it
### What is actually happening?
Only click on multiselect on the checkbox itself. On single select the `md-select` component does not work any more

### Reproduction Link
https://vuematerial.github.io/#/components/select

I think this issue is affected through the change of `@click.native`

**Comment by alphaelf** [comment]
why router-link with md-button tag not working?

**Comment by simonl65** [comment]
Hmmm, was a breaking change in v0.7.0 :-(
