### ISSUE TITLE
Dialog buttons are no longer working in 0.7.0

### ISSUE THREAD

**Issue by adam-hanna** [marcosmoura/vue-material#455]
### Steps to reproduce
Insert a dialog modal. You can even view the ones in your [doc](https://vuematerial.github.io/#/components/dialog). Click on the modal to open it. Then, click on the ok or cancel buttons. Nothing happens and modal stays open. In you doc, the "custom" dialog is working, but none of the others are.

### Which browser?
Chrome Version 56.0.2924.87 (64-bit)
vue-material 0.7.0
vue 2.1.10

### What is expected?
The dialog to close.

### What is actually happening?
The dialog stays open. Rather, the only way to close the modal is to click outside of the modal.

### Reproduction Link
https://vuematerial.github.io/#/components/dialog

The "custom" dialog on your page is working, but none of the others are.

**Comment by VicarEscaped** [comment]
This is happend only on `md-dialog-alert`, `md-dialog-confirm`, `md-dialog-prompt`.
Custom dialog button works like a charm.

**Comment by mubaidr** [comment]
None of the buttons are working fine for me. Sidebar menu button, form submit button, speeddial buttons are broken for me after upgrading to 0.7.0. Reverting back to older build for now.

**Comment by VicarEscaped** [comment]
This is happens beacause firing a `@click`  event, if change event to `@click.native` it works

**Comment by VicarEscaped** [comment]
#454

**Comment by marcosmoura** [comment]
Already fixed. I will release a fix today... Sorry about that.
