### ISSUE TITLE
MdLayout md-flex-{size} not working after 0.7.0

### ISSUE THREAD

**Issue by fergardi** [marcosmoura/vue-material#456]
It broke my responsive layout after new css. Allways uses the md-flex-xsmall over others.

Go to https://vuematerial.github.io/#/ui-elements/layout to check.

Glad to hear commits again from you!

**Comment by mubaidr** [comment]
Confirmed! Md-layout tags are broken and buttons are also not working for me.

**Comment by jdheeter** [comment]
Confirmed, all layout elements revert to xsmall configuration.

**Comment by marcosmoura** [comment]
Confirmed too! :(
I already know what is wrong and I will fix and release it today.

**Comment by creeperyang** [comment]
Quick fix 👍
