### ISSUE TITLE
Example needed for md-list-item using router-link

### ISSUE THREAD

**Issue by fergardi** [marcosmoura/vue-material#457]
Hello.

When using vue-router router-link custom element and md-list-item from md-list component inside a sidenav component, how can achieve the best result?

http://codepen.io/fergardi/pen/rjZYYZ

**Comment by VicarEscaped** [comment]
hi, @fergardi 
```pug
md-sidenav.md-left
    md-toolbar
      div.md-toolbar-container
        h3.md-title Navigation
    md-list
      md-list-item
        router-link(exact to="/iwant") I want
      md-list-item
        router-link(exact to="/to") To
      md-list-item
        router-link(exact to="/go") Go
      md-list-item
        router-link(exact to="/home") Home
```
Is that you looking for?

**Comment by fergardi** [comment]
Perfect, thank you. Integration with vue-router should definitely be in the docs.

**Comment by marcosmoura** [comment]
It will. I will fix that on the website. :)
