### ISSUE TITLE
Examples page for v0.7.0 not working in IE11

### ISSUE THREAD

**Issue by thomasd** [marcosmoura/vue-material#459]
### Steps to reproduce
Open https://vuematerial.github.io/#/ in IE11

### Which browser?
IE11, vue-material v0.7.0 only

### What is actually happening?
It seems that Promise.js polyfill for IE is missing in build.

![grafik](https://cloud.githubusercontent.com/assets/23284/22737874/643fb55c-ee05-11e6-889b-4864f2037967.png)

**Comment by marcosmoura** [comment]
I will take a look. I think I missed some configurations when upgrading to Webpack 2.

**Comment by thomasd** [comment]
It is still the same problem after update to v0.7.1 on IE11. 
Altough I cannot verify that the examples page is really using the latest version of vue-material?!

**Comment by albanm** [comment]
Same error when running the development server on the latest develop branch.

**Comment by santagu** [comment]
Please help!!! Does it actually work in ie11? It does not work with version 0.7.1 and I have checked that the example page does not work either. I would have to redo a development right now if it is not. Thank you

**Comment by pablohpsilva** [comment]
Oh dear lord... I'll look into it ASAP.

**Comment by pablohpsilva** [comment]
@santagu @albanm and @thomasd,
could you please test the PR #791 ?

**Comment by santagu** [comment]
Infinite thanks for your answer, I'll try it, but I used the polyfill es6-promise and now it works. The deadline was yesterday. Ufff ... "saved by the bell" ... I think your solution will work better so I will try it soon. Thanks, thanks and thanks again.

**Comment by thomasd** [comment]
Hy @pablohpsilva. I had the chance to test PR #791 on a local server now. The docs site is working in IE11. The error message is gone. Great! Thanks!

**Comment by alansutherland** [comment]
this is most likely an issue with vue not vuematerial. It does not support IE11 by default. I went round in circles, trying babel polyfills etc until Linus from vue pointed out I was missing my .babelrc file which compiles es6 in to js that IE11 can understand. Check this link out for more info https://forum.vuejs.org/t/ie-11-still-not-working/11834/5
