### ISSUE TITLE
Not able to use select component on examples page for v0.7.0

### ISSUE THREAD

**Issue by qorsmond** [marcosmoura/vue-material#460]
### Steps to reproduce
Open https://vuematerial.github.io/#/components/select

### Which browser?
Chrome 56

### What is actually happening?
I am not able to select options in the select component.

When I click on an option it does nothing:

![image](https://cloud.githubusercontent.com/assets/4716711/22739361/f91b655a-ee13-11e6-85a7-4d969aacfb6b.png)

**Comment by marcosmoura** [comment]
Duplicated #454

**Comment by qorsmond** [comment]
Damn did not see that one. Tnx!

**Comment by marcosmoura** [comment]
Don't worry!
