### ISSUE TITLE
Ink ripple only works once on Firefox 51

### ISSUE THREAD

**Issue by waspinator** [marcosmoura/vue-material#461]
### Which browser?
Firefox 51 on macOS 10.12

### What is expected?
Ink ripples should work more than once

### What is actually happening?
After the first ink ripple, the element just flashes dark with no ripple.

### Reproduction Link
![example](http://g.recordit.co/5hePmKgUG2.gif)

**Comment by thomasd** [comment]
I see the same effect on IE11 in vue-material v0.6.3 also.

**Comment by Samuell1** [comment]
Samue issue. Firefox 51.0.1 Windows

**Comment by thomasd** [comment]
Now Ink-Ripple effect is not working anymore at all with Firefox 51.0.1 (Windows) on demo site  https://vuematerial.github.io/#/components/ink-ripple (v7.0.1)

It does however work on Chrome 56.0 as expected.

**Comment by Samuell1** [comment]
@thomasd for me is working

**Comment by thomasd** [comment]
@Samuell1 I cleared the cache several times, still the same.
I also tried it via this http://codepen.io/vue-material/pen/WGavBE 
But still not working.

![grafik](https://cloud.githubusercontent.com/assets/23284/22785625/6216990a-eed5-11e6-837a-7c5b5375cca5.png)

You can see that vue-material is indeed v0.7.1 (loaded via unpkg.com)
Very strange, but it seems it's only happening to me???

**Comment by Samuell1** [comment]
for me is fine
![2017-02-09_16-33-56](https://cloud.githubusercontent.com/assets/3110002/22790219/c422ae6c-eee5-11e6-9d36-7293bbd449bd.gif)

**Comment by Pixelrise** [comment]
In my Firefox 53.0.2 it doesn't work either. Cache is clean.

**Comment by pablohpsilva** [comment]
Do we have an issue here guys? I'm confused.

**Comment by alexstacey** [comment]
Ripple doesn't work for me Firefox 53.0.3 (64-bit) OSX

**Comment by waspinator** [comment]
works on macOS 10.12.3 Firefox 53.03 (64-bit)
