### ISSUE TITLE
regression on md-input with release of 0.7.0

### ISSUE THREAD

**Issue by dohomi** [marcosmoura/vue-material#462]
### Steps to reproduce
I have all `vue-material` `md-input-container` with `md-input` inside of custom components wrapped to display error messages based on `vuelidate`. After updating to `0.7.0` I receive an error on my custom components and Vue stops compiling.

### Which browser?
Every browser, newest Vue and vue-material 0.7.0

### What is expected?
Custom component should be able to wrap `md-input-container` and `md-input` and forward `v-model` or `:value` properties to the `md-input`

### What is actually happening?
```[Vue warn]: Error in watcher "value" 
(found in component <md-input>)
warn @ vue.runtime.common.js:521
run @ vue.runtime.common.js:3023
flushSchedulerQueue @ vue.runtime.common.js:2807
(anonymous) @ vue.runtime.common.js:473
nextTickHandler @ vue.runtime.common.js:422
vue.runtime.common.js:435 TypeError: Cannot read property 'setValue' of undefined
    at VueComponent.setParentValue (vue-material.js:6)
    at VueComponent.boundFn [as setParentValue] (vue.runtime.common.js:126)
    at VueComponent.value (vue-material.js:6)
    at Watcher.run (vue.runtime.common.js:3017)
    at flushSchedulerQueue (vue.runtime.common.js:2807)
    at Array.<anonymous> (vue.runtime.common.js:473)
    at nextTickHandler (vue.runtime.common.js:422)```

**Comment by marcosmoura** [comment]
Can you create an example on Codepen?

**Comment by dohomi** [comment]
I tried but unfortunately it seems to be nested inside of the `NUXT` framework additionally. The basic example worked but I will try to add some more complexity. The only thing I know for now is, that on `vue-material 0.6.3` the exact same code works without error.
http://codepen.io/anon/pen/wgEYBN

**Comment by dohomi** [comment]
I will close this issue for now.. I need to check again my code maybe I overlooked something.

**Comment by jonataswalker** [comment]
Same error here, to solve I've changed my initial setup from `mounted()` to `created()`.

**Comment by Andkoo** [comment]
@jonataswalker thanks, worked like a charm

**Comment by AaronMorgan** [comment]
@jonataswalker Changing `mounted ()` to `created ()` resolved the two errors I was seeing, Thank you.
