### ISSUE TITLE
Forked contribution

### ISSUE THREAD

**Issue by fergardi** [marcosmoura/vue-material#465]
Hello.

I would like to contribute to your project. Was thinking about adding one or two small components, but it's my first time contributing to an actual project and wanted to do it right. Planned to do the "mdStepper" and "mdSearch", for example, in order to know better about VueJS, VueMaterial, GitHub, Forks and Pull Requests.

I forked your repo, created a new branch called "components/mdNameOfComponent", and started working in /src and /docs folders. Hope you don't mind and please warn me if I do something incorrect.

Thanks for your effort.

**Comment by marcosmoura** [comment]
I would love to see contributions, of any type! This project is ours! \o/
If you want, there is an channel on Gitter that we can use to discuss some ideas for new components and/or improvements!

Thank you for the interest to help here!
