### ISSUE TITLE
router-link with "md-button" tag not work

### ISSUE THREAD

**Issue by despird-zh** [marcosmoura/vue-material#470]
vue-material version: 0.7.1

Reproduce it:
step1: following is a workable link.
`<router-link to="/components/button" class="md-raised md-primary">Router Link</router-link>`

step2: add tag="md-button" it won't work, but in version@0.6.3 it works fine.
`<router-link tag="md-button" to="/components/button" class="md-raised md-primary">Router Link</router-link>`

PS. thanks to marcos, great work done!

**Comment by d3radicated** [comment]
Also, click events don't work on "md-button". It can be fixed by using the native click event (`@click.native="fn"`).

**Comment by ralphchristianeclipse** [comment]
yes same with me using 
`js
<router-link tag="md-button" :to="{name: 'path'}">Doesnt Work</router-link>`

**Comment by marcosmoura** [comment]
I will take a look. Right now, as a workaround, you can use:
``` vue
<router-link tag="button" :to="/" class="md-button">Hello! <md-ink-ripple /></router-link>
```

**Comment by d3radicated** [comment]
According to Vue Router's [documentation](https://router.vuejs.org/en/api/router-link.html), the navigation triggers on the click event. Since it's been deprecated on the `md-button` component, it doesn't trigger anymore.

**Comment by d3radicated** [comment]
Temporary Workaround

```html
<md-button @click.native="$router.push('/components/button')>Router Link</md-button>"
```

**Comment by marcosmoura** [comment]
It's **fixed** on develop branch and will be delivered soon. 
It's important to notice that is not possible to use `md-button` as tag and expect `<a>` as output.
The best workaround for this (but still odd):
``` vue
<router-link to="/" class="md-button" :class="`md-theme-${$material.currentTheme}`">Hello! <md-ink-ripple /></router-link>
```
In this case the output will be: 
``` html
<a href="#/" class="md-button md-theme-default"> ... </a>
```

**Comment by ikbelkirasan** [comment]
I fixed it like this:

`
<md-menu class="pull-right" md-align-trigger md-direction="bottom left">
	<md-button md-menu-trigger><md-icon>account_circle</md-icon> Kira San</md-button>
    <md-menu-content>
      <md-list>
        <md-list-item>
        	<router-link exact to="/profile"><span>Profile</span></router-link>
        </md-list-item>
      </md-list>
    </md-menu-content>
</md-menu>
`
