### ISSUE TITLE
add "fullscreen" option on MdDialog for "xs" devices

### ISSUE THREAD

**Issue by dohomi** [marcosmoura/vue-material#471]
Hi @marcosmoura 

I think a `fullscreen` option on `MdDialog` would be very useful for smarthpone usage. This is the description from the `AngularMaterial` library:
`
fullscreen {boolean=}: An option to toggle whether the dialog should show in fullscreen or not. Defaults to false.
`

**Comment by marcosmoura** [comment]
This is planned. I will add this soon, after the changes related to #82
