### ISSUE TITLE
MdListItem not hoverable and clickable

### ISSUE THREAD

**Issue by VicarEscaped** [marcosmoura/vue-material#472]
### Steps to reproduce
Go to List section in docs.
### Which browser?

Firefox 51.0.1
Chrome 56.0.2924.87
### What is expected?
All mdListItem hoverable and clicable
### What is actually happening?

Only `Link`, `Button`, `Router View` items are clickable. And expandable.
### Reproduction Link

[Link](https://vuematerial.github.io/#/components/list)

**Comment by d3radicated** [comment]
I think it is intended that only `Link`, `Button`, and `Router View` items are clickable. Though, list items should all be hover-able. I also think that they should have mouseenter and mouseleave events (like in Google Inbox).

**Comment by fergardi** [comment]
I think this is intended too. The inkRipple in md-list-items that were informational-only with no actions attached was causing me some huge performance problems, and for no purpose. Only the actionablelist-items should be actually clickable.

**Comment by VicarEscaped** [comment]
@d3radicated @fergardi  that make sense. thx.
