### ISSUE TITLE
Ripple not working on desktop with touchscreen

### ISSUE THREAD

**Issue by vivescere** [marcosmoura/vue-material#477]
The latest version released is great, but a fix for the ripple effect (https://github.com/marcosmoura/vue-material/commit/d74b2ac0f1aa9ff671c2429d02ad0b4ec8ad1172) is not working as expected.

You determine which events to use with `const hasTouch = 'ontouchstart' in document;`, but it will return true if a computer has a touchscreen.

I think you could fix it, since a browser has to send a `TouchEvent` before a `MouseEvent`: ["If the browser fires both touch and mouse events because of a single user input, the browser must fire a touchstart before any mouse events."](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent).

Listen for both, and set a flag if a touch event is received. Then ignore the next mouse event. Be careful tough, if a user toggles the dev tools it could lead to an event not working once.

Thanks for your work!

**Comment by marcosmoura** [comment]
I will take a look at this. The problem is that I don't have a touchscreen monitor, so maybe this will be kinda hard to fix.

**Comment by vivescere** [comment]
I fixed it by storing whether the last two events are from the touchscreen or the mouse. I store two of them in case someone opens the dev tools.
