### ISSUE TITLE
Error: Vue.use(VueMaterial) 

### ISSUE THREAD

**Issue by andreujuanc** [marcosmoura/vue-material#48]
Hello, 

I'm evaluating framework alternatives, and wanted to test vue, and came across this repo which is the one I liked the most.

In the process of making a cordova app, I made a small test, just one page, referenced vue worked fine. Click on button and hello world, But when I tried to add vue-material like: Vue.use(VueMaterial) I got: `plugin.apply is not a function`

I'm not familiar with vue, so I have no idea what happened here.

Any ideas?

Cheers

**Comment by krisanalfa** [comment]
How about:


```js
Vue.use(VueMaterial.default)
```

**Comment by marcosmoura** [comment]
This fix worked for you?

**Comment by marcosmoura** [comment]
```Vue.use(VueMaterial.default)``` will no longer work on the next version. You should use ```Vue.use(VueMaterial)``` instead.
