### ISSUE TITLE
Vue Material components don't render inside Vue single file components

### ISSUE THREAD

**Issue by Akhawais** [marcosmoura/vue-material#481]
Whenever I try to use Vue Material components inside a .vue file, they seem to load fine (Checked via Vuejs Devtools) but they don't render anything in the DOM.

```JS
<template>
    <div>
        Test
    <md-layout md-gutter v-for="chunk in entries">
        <md-layout md-flex-xsmall="100" md-flex-small="33" md-flex-medium="33"  md-flex-large="33" v-for="entry in chunk">
            <md-card>
                <md-card-area>
                    <md-card-header>
                        <div class="md-title"><a href="">{{ entry.test }}</a></div>
                    </md-card-header>

                    <md-card-content>
                        Test
                    </md-card-content>
                </md-card-area>
            </md-card>
        </md-layout>
    </md-layout>
    </div>
</template>
<style>
</style>
<script>
    export default{
        data(){
            return{
                entries: app.entries,
            }
        }
    }
</script>
```
Test.vue

```JS
window.Vue = require('vue');
window.VueMaterial = require('vue-material');
Vue.use(VueMaterial);
...
import Test from './components/Test.vue';

var app = new Vue({
    el: '#app',
    data: {
         entries: []
    },

    components: {
        'test':     Test
    }
});
```
app.js

Using Laravel Mix to compile everything (which is basically a wrapper for Webpack)

Any help would be appreciated

**Comment by d3radicated** [comment]
You forgot to import Vue Material itself.

```javascript
import Vue from 'vue'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'
```

**Comment by Akhawais** [comment]
Hey, I'm already including Vue & Vue Material. I forgot to add in my includes at the top of the app.js file. I have done so now - sorry for the confusion.

The CSS is included in my sass file. I've also tried adding a <style> element that points to the vue-material CSS and that doesn't work either.

If I inspect the components in Vuejs Devtools, I can see that the components are loaded successfully with no errors in the console either - it just seems to not render anything in the DOM.

Thanks.

**Comment by marcosmoura** [comment]
Have you tried a simple `<md-button>` only? Maybe there is something wrong with your `v-for="chunk in entries"`

**Comment by Akhawais** [comment]
```JS
<template v-for="i in 5">
    <md-button class="md-raised md-accent">{{ i }}</md-button>
</template>
```
Using a button only, it seems to render fine.

---

It seems that if I hard-set the contents of `entries` directly in the Vue file, all the components seem to load fine. It's only when AJAX is used to load the contents of `entries` does this issue occur.

Since the AJAX successfully sets `entries`, and Vue creates the MD components based on that - is there a further step I need to do in order to get vue-material to re-render the DOM? (something similar to `vue.$forceUpdate();`)

**Comment by marcosmoura** [comment]
No. Instead of using `data`, try to use `computed` properties:
``` js
export default {
  computed: {
    entries() {
      return app.entries;
    }
  }
}
```

Please note that this is not related to Vue Material itself, but only the Vue Syntax.

**Comment by bisht-richa** [comment]
I dont want to include <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons"> in index.html manually. How to solve this issue ?

**Comment by pablohpsilva** [comment]
I replied to you @bisht-richa on issue #973
:D

**Comment by akash123456347** [comment]
@marcosmoura  ur solution also fails

**Comment by akash123456347** [comment]
any one have proper solution for this
