### ISSUE TITLE
Error on Snackbar when closed by timeout

### ISSUE THREAD

**Issue by mehyaa** [marcosmoura/vue-material#483]
Hi,

I'm using snackbar in a dinamically loaded component and when snackbar is closed by timeout it fires this error: 

> TypeError: Cannot read property 'removeEventListener' of undefined

![image](https://cloud.githubusercontent.com/assets/1491850/22819077/2482c812-ef79-11e6-911f-536ab1913eb9.png)

It does not fire any error when closing by clicking close button.

**Comment by marcosmoura** [comment]
I see. I will take a deep look at this. Can you upload some example to Codepen?
