### ISSUE TITLE
weird hover behaviour of speed dial on demo page

### ISSUE THREAD

**Issue by fiws** [marcosmoura/vue-material#484]
### Steps to reproduce
1. Go to https://vuematerial.github.io/#/components/speed-dial
2. Click any of the buttons appearing after hover
3. try to hover over them again

### Which browser?
Tested on Chrome and FF

### What is actually happening?

[this](https://gitlab.fiws.net/fiws/test-acdc/uploads/94ae2540c87e9cbe4118b5dda73e2e9c/vue-material-speed-dial.mp4)

**Comment by bruunoromero** [comment]
Created a PR #508
