### ISSUE TITLE
Transition Group Tagged with md-layout gives getBoundingClientRect error

### ISSUE THREAD

**Issue by ralphchristianeclipse** [marcosmoura/vue-material#489]
### Steps to reproduce
1. Create transition group 
2. Assign md-layout as tag
3. Put cards inside the transition group keyed by index

### Which browser?
Version 0.7.1 Google Chrome 56
### What is expected?
Works well without receiving bugs and stopping vue rendering
### What is actually happening?
Works but got errors and stops vue rendering and all components stopped working
and gives the error on the title above

**Comment by marcosmoura** [comment]
Can you create a example on Codepen?
