### ISSUE TITLE
Checkbox events only pass true/false

### ISSUE THREAD

**Issue by kristianmandrup** [marcosmoura/vue-material#49]
I've been trying pretty much everything I can think of in order to listen to checkbox change events and set my VueX store accordingly

https://github.com/vuejs/vue-rx/issues/20

Please play nice and send the original `$event` along as well. I only get `true` or `false`.
Otherwise my only option is to watch the entire checkbox value collection:

https://laracasts.com/discuss/channels/vue/checkbox-events

Or maybe I'm not binding correctly, it's a jungle trying to find the right way... most docs only show the templating, not how to bind to underlying models.

```html
    <md-checkbox 
      v-for="choice in prompt.choices" 
      :name="prompt.name"
      :id="prompt.name"
      @input="updateChoice(e, $event)"
      @change="updateChoice" 
      class="md-primary" 
      v-model="choice.value">{{ choice.label }}</md-checkbox>
```

Am I binding my v-model correctly here? `v-model="choice.value"`
If I try binding to an Array I'm told it must be a String or Boolean. So here I'm binding directly on the incoming Object of the form: `{label: 'xyc', value: false}`.

My only other option seems to be to watch on the entire `prompt.choices` object for changes!?

```js
export default {
  props: ['prompt'],
  data () {
    return {
    }
  },

methods: {
    // $event x is always just null :( 
    updateChoice (e, x) {
      console.log(e, x)
  }
}
}

**Comment by kristianmandrup** [comment]
I made this [PR](https://github.com/marcosmoura/vue-material/pull/50), but sadly I must have done sth wrong, cos I get `$event` to be undefined when I try to hook in to my custom fork functionality.

**Comment by kristianmandrup** [comment]
I also tried this but still no luck...

```
<template>
  <div>
    <md-checkbox 
      v-for="choice in prompt.choices" 
      :name="prompt.name"
      :id="prompt.name"
      class="md-primary" 
      v-model="choice.value">{{ choice.label }}</md-checkbox>
  </div> 
</template>
<script>
export default {
  props: ['prompt'],
  data () {
    return {
    }
  },
  mounted () {
    this.$watch('prompt.choices', (newChoices, old) => {
      console.log('newChoices', newChoices)
    })
  }
}
</script>
```

**Comment by kristianmandrup** [comment]
Please see https://github.com/vuejs/vue/issues/4167

**Comment by kristianmandrup** [comment]
Only way I was able to intercept checkbox change of value:

```js
  watch: {
    prompt: {
      handler: function (val, oldVal) {
        console.log('watched change', val)
      },
      deep: true
    }
  },
```

**Comment by kristianmandrup** [comment]
Well, this works:

`<input type="checkbox" @change="onChange($event)" v-model="myVal"/>`

```js
  methods: {
    onChange (event) {
      console.log(event)
    },
```

**Comment by marcosmoura** [comment]
Yep. This a Vue way to deal and pass ```$event```.
