### ISSUE TITLE
Unable to use 'ö' in Chips-Component

### ISSUE THREAD

**Issue by matthinc** [marcosmoura/vue-material#490]
It's impossible to use the Letter 'ö' in the Chips-View.
If 'ö' is the first letter of a word the view doesn't react. If 'ö' is in the middle of a word the view behaves like <return> was pressed. 'ä','ü' and 'ß' are working fine.

Tested with Chrome and Safari in MacOS 10.11

**Comment by marcosmoura** [comment]
I could make them work here. Can you upload your code to an repository or Codepen?

**Comment by matthinc** [comment]
The problem was this line

`@keydown.native.prevent.186="addChip"`

I think, it could be dangerous to use keycodes directly due the many different keyboards out there. I just created a pull request to remove that line, because it really makes the component unusable for the most people.
