### ISSUE TITLE
New property for md-table - empty-data-message

### ISSUE THREAD

**Issue by TRTHHRTS** [marcosmoura/vue-material#491]
Hey. It's an awesome library! Thank you for it.
I have a suggestion to improving md-table.
It would be greate if it is possible to add an empty data message when there is no data in the table, like `<md-table empty-data-message='There is no data'>...</md-table>`.

**Comment by fergardi** [comment]
You should handle this using basic VueJS. It will be more maintanable and legible.

```pug
md-table(md-sort='field', md-sort-type='desc', @select="onSelect", @sort="onSort")
  md-table-header
    md-table-row.center(v-if="loading")
      md-table-head
        span Loading data...
        md-icon.spin sync
    md-table-row.center(v-if="!loading")
      md-table-head
        span True data
        md-icon done
```

And change the "loading" state based on data load, when necessary.

**Comment by marcosmoura** [comment]
This is such an specific use case. Some other applications would need a different type of message, show a form if there is no data or redirect the user to the "create" page. The example from @fergardi will work for you.
