### ISSUE TITLE
md-snackbar not accessible through $refs

### ISSUE THREAD

**Issue by srodriki** [marcosmoura/vue-material#500]
### Steps to reproduce

1. Have a vue component that uses md-snackbar in its template, just as [shown in the documentation](https://vuematerial.github.io/#/components/snackbar).
2. Click on the "Open Snackbar" button

### Which browser?
Chrome (latest version) for MacOS, Firefox (latest) for Mac OS. Haven't tested on others

### What is expected?

The snackbar should open when the user clicks on the "Open Snackbar" button

### What is actually happening?

An error stating that the open() method can't be called for "undefined" is thrown. This happens because this.$refs.statusbar is undefined. This is happening with the latest release (0.7.1) on Vue 2.0.10. 

### Reproduction Link
http://codepen.io/srodriki/pen/KaJgBy?editors=1111

**Comment by marcosmoura** [comment]
You wrote the ref and the position wrongly:
```vue 
<md-snackbar :md-position="'top center'" ref="'statusbar'">
```
Should be:
```vue 
<md-snackbar md-position="top center" ref="statusbar">
```
:)

**Comment by srodriki** [comment]
Oh man.. so sorry. Looks like I suffered from tunnel vision there. Hope next issue (if ever) is a real problem. Thanks so much for enlightening me

**Comment by marcosmoura** [comment]
Don't worry! It happens! :D
