### ISSUE TITLE
md-theme-blue in sidenav not work

### ISSUE THREAD

**Issue by fortil** [marcosmoura/vue-material#502]
I have the next code in `main.js`

```
import Vue from 'vue'
import App from './App'
import router from './router'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'

Vue.use(VueMaterial)

new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
```

In `App.vue <template>`  and `<style>` I have exactly the example code of the [Documentation Web Page](https://vuematerial.github.io/#/components/toolbar) but when I open the SideNav this is transparent background and when I see the DevTools the components aren't assigned styles for themselves of vue-material.

You can to see the next picture.. I believe that is the scope of the App.vue, but I dont know how to fix.
![image](https://cloud.githubusercontent.com/assets/6068654/22917767/bdd4553e-f254-11e6-8e30-a2330d7310ae.png)

**Comment by fergardi** [comment]
You need to actually register the name of the theme you want to use in your main.js, [just like in the docs](https://vuematerial.github.io/#/themes/configuration).

```js
Vue.material.registerTheme({
  blue: {
    primary: 'blue',
    accent: 'pink',
    warn: 'whatever'
  }
});
```

**Comment by fortil** [comment]
You're right, I forgot to register the theme.
I'm sorry 👍 

I've an ask, do you know anything tutorial of vuematerial?
Thanks

**Comment by fortil** [comment]
Another question.

THe children components doesn't had attribute $ref of father component. Then, I thought to include vuex in the logic, but when I try to put state in father component not work.

Template App.vue (whe I put a model in ref not work, too)
´´´
<Toolbar></Toolbar>
<md-sidenav md-theme="blue" class="md-left" ref="$store.state.openSidenav" (or  ref="openSidenav")>
:
</md-sidenav>
´´´
<script> in App.vue
´´´
import Toolbar from './components/Toolbar'
export default {
  name: 'app',
  data () {
    return {
      openSidenav: this.$store.state.openSidenav
    }
  },
  components: {
    Toolbar
  }
}
´´´


Toolbar.vue
--------
Template
´´´
<md-button class="md-icon-button" @click.native="openSidenav">
        <md-icon>menu</md-icon>      
</md-button>
´´´´´
script
´´´´
export default {
  name: 'Tooolbar',
  data () {
    return {}
  },
  methods: {
    openSidenav () {
      this.$store.commit('toggleSidenav')
    }
  }
}
´´´

Now in main.js (vuex)
´´´´
const store = new Vuex.Store({
  state: {
    openSidenav: false
  },
  mutations: {
    toggleSidenav (state) {
      state.openSidenav = !state.openSidenav
    }
  }
})
´´´

The commit work, but sidenav not work, do you something idea?

**Comment by marcosmoura** [comment]
The ref property is not reactive. That's why is not working. Instead of using mutations, use actions.

**Comment by leopku** [comment]
I tried and it now worked with vuex in this way:

```js
// sidebar.vue
<template>
  <md-sidenav class="md-left" ref="sidenav">
    ...
  </md-sidenav>
</template>

<script>
export default {
  mounted() {
    this.$store.state.sidenav = this.$refs.sidenav; // save sidenav refs
  }
}
</script>
```

```js
// store.js

import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)
const state = {
  sidenav: {}
}

const mutations = {
  TOGGLE_SIDENAV (state) {
    state.sidenav.toggle()
  }
}

const actions = {}

const store = new Vuex.Store({
  state,
  mutations,
  actions
})

export default store
```

```js
// toolbar

<md-button class="md-icon-button" @click.native="$store.commit('TOGGLE_SIDENAV')">
  <md-icon>menu</md-icon>
</md-button>
```

click menu, sidenav will shown or hidden
