### ISSUE TITLE
How to acces to children refs?

### ISSUE THREAD

**Issue by fortil** [marcosmoura/vue-material#509]
Hi

The case is; I have **/App.vue**, **/components/sidenavbar.vue** and **/components/toolbar.vue**

When I cliked in some component in toolbar, I need that **sidenavbar.vue** workup. I resolved of this form:
In **toolbar.vue** trigger a `this.emit$('toggleSidenav')`  then in **/App.vue** I recive this event and make `this.$children[2].$refs.sidenav.toggle()`, that obviously it's a bad solution.

When I use `md-visible` in element `<md-sidenav>` **/components/sidenavbar.vue** pass as prop, not work.

Thanks

**Comment by VicarEscaped** [comment]
Hi, @fortil . If **sidenav** and **toolbar** components does not bound together, you can implement an EventBus or use [this](https://github.com/cklmercer/vue-events). That allow you to emit and receive events in any component of you app.

**Comment by fortil** [comment]
@VicarEscaped  Thanks

I use [v-on with Custom Events](https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events) but not work. 

I have the next code.
**App.vue**
```
<template>
<div class="mov-politic ">
  <Toolbar v-on:toggleSidenav="toggleSidenav"></Toolbar>
  <List></List>
  <Sidenavbar :toggleSidenav="openSidenav"></Sidenavbar>
</div>
</template>

<script>
:
export default {
  name: 'App',
  data () {
    return {
      openSidenavState: true
    }
  },
  methods: {
    toggleSidenav () {
      this.openSidenavState = !this.openSidenavState
    }
  },
  computed: {
    openSidenav () {
      return this.openSidenavState
    }
  },
  components: {
    :
  }
}
</script>
```
In **Toolbar.vue** 
```
:
export default {
  name: 'Tooolbar',
  data () {
    return {}
  },
  methods: {
    toggleSidenav () {
      this.$emit('toggleSidenav')
    }
  }
}
```
And in **Sidenavbar.vue**
```
<template>
  <md-sidenav md-theme="blue" class="md-left" ref="sidenav" md-visible="toggleSidenav">
:
</template>

<script>
export default {
  name: 'sidenavbar',
  props: ['toggleSidenav'],
  data () {
    return { }
  }
}
</script>
```

The comunication between Toolbar.vue -(click with $emit)-> App.vue work!, but the easy comunication (I thought) App.vue -(with properties doesn't work)-> Sidenavbar.vue

**Comment by fortil** [comment]
I solved!!

In **Sidenavbar.vue** I put 
`<md-sidenav md-theme="blue" class="md-left" ref="sidenav" :md-visible="open">`
And in js section
```
    toggle () {
      this.$refs.sidenav.open()
    }
```
But I don't know why do not work this.$refs.sidenav.toggle() in this context.

Thank you!!

**Comment by M-Hc0d3** [comment]
@fortil  Where exactly did you put the toggle function mate? Inside the same file as Sidebarnav.vue? Having the same problem right now, apparently using $ref is disliked since its not reactive but nothing else seems to be viable so far.
