### ISSUE TITLE
right sidenav always showing

### ISSUE THREAD

**Issue by nothinggift** [marcosmoura/vue-material#51]
[http://codepen.io/nothinggift/pen/BQovGZ](http://codepen.io/nothinggift/pen/BQovGZ)

you can scroll horizontally to see it

**Comment by marcosmoura** [comment]
I see. This is a problem that needs more time to fix. 
Why this happens:
Your container doesn't have an explicit ```overflow-x: hidden``` css rule. If you add this to your parent container (with id="app") the scroll will disappear. But this should be a Vue Material responsability. 
I will fix this in the very next release. Meanwhile you can stick with this workaround.

Please tell me if this works for you.
Thank you!

**Comment by nothinggift** [comment]
[http://codepen.io/nothinggift/pen/BQovGZ](http://codepen.io/nothinggift/pen/BQovGZ)

`overflow-x: hidden` not work

**Comment by ktquez** [comment]
@nothinggift 
Hey man, try in body
```css
body {
  overflow-x: hidden;
}
```

**Comment by nothinggift** [comment]
[http://codepen.io/nothinggift/pen/BQovGZ](http://codepen.io/nothinggift/pen/BQovGZ)
I have revised a little , it works well.

**Comment by marcosmoura** [comment]
Glad to know that this worked for you. I will close this thread and reopen when I start to develop this enhancement.

**Comment by Linzdigr** [comment]
Same problem here. The solution works in desktop but mobile can still see it when scrolling horizontally.
