### ISSUE TITLE
Use vue variable in md-select option

### ISSUE THREAD

**Issue by george-dragnea** [marcosmoura/vue-material#510]
Thanks for all your work on this project.

Here is the problem: http://codepen.io/georgedragnea/pen/egXgaB
When I change the "Currency", the text from select("Currency display") should update. It's get updated if I click on it, but not automatically.

**Comment by VicarEscaped** [comment]
Hi, @george-dragnea. Then first `mdSelect` change, you need to tell second `mdSelect` to change `selectedText`.
[Here](http://codepen.io/anon/pen/GrevjL) is some dummy example.

**Comment by george-dragnea** [comment]
@VicarEscaped thanks for your support. I thought that was a bug.
