### ISSUE TITLE
Question about mdSidenav

### ISSUE THREAD

**Issue by VicarEscaped** [marcosmoura/vue-material#514]
Hi, @marcosmoura!
I have a question about `mdSidenav`, especially about *md-right*.
If I use `mdSidenav` with *md-left* it works as expected: sidenav does not appear until i trigger it.
But if i use *md-right* it add extra space at right side.
I'm quite bad at css, so maybe i need some layout to display it properly?

**Comment by marcosmoura** [comment]
The only thing that you'll need is to have a parent element with an overflow-x: hidden. There is no other way for Vue Material to guarantee this behaviour under the hood.
