### ISSUE TITLE
v-on:click not working on md-button

### ISSUE THREAD

**Issue by alvarolemos** [marcosmoura/vue-material#519]
I'm trying to call a function after clicking a `<md-button>` with `v-on:click`, but it's not working. When I try the same thing with a ordinary `<button>`, it does work.

Here's a CodePen: http://codepen.io/anon/pen/WRWxzP

Thanks for the great work! :D

**Comment by jonataswalker** [comment]
Try `v-on:click.native`. See https://github.com/marcosmoura/vue-material/releases/tag/v0.7.0

**Comment by alvarolemos** [comment]
Thanks dude, worked like a charm!
