### ISSUE TITLE
Error TS7016: Could not find a declaration file for module 'vue-material'

### ISSUE THREAD

**Issue by diskman** [marcosmoura/vue-material#530]
Hi I try to use vue-material on project which use typescript.  When I try to register plugin 'vue-material' 

```
import 'es6-promise/auto'
import * as Vue from 'vue'
import  App from './App.vue'
import VueMaterial from 'vue-material'

Vue.use(VueMaterial)

// mount
new Vue({
  name: 'RootVue',
  el: '#app',
  render: h => h(App, {
    props: { propMessage: 'World' }
  })
})
```

the errors in shown

```
error TS7016: Could not find a declaration file for module 'vue-material'. 'C:\git\testing\webpack_simple\node_
modules\vue-material\dist\vue-material.js' implicitly has an 'any' type.
```

My tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "isolatedModules": false,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "removeComments": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
        
    ]
  },
  "include": [
    "./src/**/*.ts"
  ],
  "compileOnSave": false
}
```

**Comment by diskman** [comment]
it seems that problem was because of  "noImplicitAny": true, switching to false resolved problem

**Comment by dhruvdutt** [comment]
@diskman Thanks a ton! You saved my day.

**Comment by jrods** [comment]
Instead of setting `noImplicitAny`, I found that setting `allowSyntheticDefaultImports` to `true` allows `vue-material` to be imported correctly, i guess it's a case of `vue-material` bundle's import style? Microsoft/TypeScript#10895

**Comment by Devnagri** [comment]
Thanks

**Comment by saisk73** [comment]
> it seems that problem was because of "noImplicitAny": true, switching to false resolved problem

thanks i was getting this error in production finally resolved...

**Comment by avfirsov** [comment]
Hello guys! I am getting same error. When I just simply create new Vue project via vue-cli and follow [official installation guideline](https://vuematerial.io/getting-started/). I am not using typescript and did not check to support TS while creating Vue project.

Switching "noImplicitAny": true to false did not help me (although I am not sure I changed it in the right place, since there are several tsconfig.json in my node_modules, I used located in vue-template-compiler).

What am I doing wrong?

**Comment by afaqahmedkhan** [comment]
> Hello guys! I am getting same error, when I just simply create new Vue project via vue-cli and follow [official installation guideline](https://vuematerial.io/getting-started/). I am not using typescript and did not check to support TS while creating Vue project.
> 
> Switching "noImplicitAny": true to false did not help me (although I am not sure I changed it in the right place, since there are several tsconfig.json in my node_modules, I used located in vue-template-compiler).
> 
> What am I doing wrong?

Were you able to resolve it? I think it was to be done in tsconfig of your root?

**Comment by Cody-fleenor** [comment]
Getting the same error, with the addition of md-field etc all throwing improperly registered component errors. I can't seem to locate the above solution (ctrl+shift+p for noImplicitAny gives no results) so I'm at a loss

**Comment by Medicinal26** [comment]
https://lnkr.fun/7d65de4



I worked it out
