### ISSUE TITLE
md-button @click do not work

### ISSUE THREAD

**Issue by Leshgan** [marcosmoura/vue-material#532]
I'm trying this code
http://jsbin.com/hejulu/edit?html,js,output
What is wrong with my code?

**Comment by MarkSimUM** [comment]
@click.native will work

**Comment by cawa-93** [comment]
@marcosmoura, I noticed a lot about this issue. It may be necessary to add the solution in the documentation? As an example of one of?

**Comment by Samuell1** [comment]
@cawa-93 its not issue but on components needs to be click with native

**Comment by Leshgan** [comment]
Thanks!

**Comment by flamedenise** [comment]
In my case, `@click.native` did not work, but `v-on:click.native` did ;)

**Comment by enesunal** [comment]
Why it's not working? ".native" in Vue documentation explained as, "There may be times when you want to listen for a native event on the root element of a component. In these cases, you can use the .native modifier for v-on." However, vue-material using .native. It's a bit awkward though. Isn't it a vue- extension?

**Comment by Samuell1** [comment]
@flamedenise its weird because `@click.native` its shortcut of `v-on:click.native`

**Comment by Chusynuk** [comment]
Using **@click.native="$router.push**('/homescreen')" with **router-link** tag I cannot visualize the button on a sidenav, anyone had the same problem?

**Comment by Samuell1** [comment]
@Chusynuk use without router link

```
<md-list-item @click.native="$router.push('/homescreen')">...
```

**Comment by Chusynuk** [comment]
This is the complete tag 

 tag="md-button" :to="{  path:  './Requests' }"  class="md-primary"

if I add the **tag="md-button"**  I can visualize the button, but I doesn't work

**Comment by simonl65** [comment]
This appears to be a breaking change, as it used to work OK (see https://www.youtube.com/watch?v=1j8xTOmR8pw).

**Comment by mmieluch** [comment]
It's because of the [ink ripple](https://vuematerial.github.io/#/components/ink-ripple) component. The default behaviour comes back when you disable it:

```
Vue.material.inkRipple = false
```

**Comment by enesunal** [comment]
Then, there should be a fix for it, right?

**Comment by simonl65** [comment]
@enesunal That would be nice, but this was noted as a [breaking change in v0.7.0](https://vuematerial.github.io/releases/v0.7.0/#/changelog) 

> **To avoid issues and conflicts between multiple events on buttons and other "clickable" components** the internal @click event don't work anymore. Use **@click.native** instead.

**Comment by buzzingcookie** [comment]
Hello there!! im trying to put a @click listener on a md-checkbox but with @click.native it does not seem to work, does anyone has an idea about some other alternatives?

**Comment by buzzingcookie** [comment]
I recently started to use vue-material and i believe using @change should work fine, i used that on my md-checkbox and its cool, cheers!
