### ISSUE TITLE
Cursor pointer is missing on checkboxes and radio buttons

### ISSUE THREAD

**Issue by Samuell1** [marcosmoura/vue-material#539]
Examples:
https://vuematerial.github.io/#/components/checkbox
https://vuematerial.github.io/#/components/radio

**Comment by jtouzy** [comment]
Just submitted PR to fix this

**Comment by marcosmoura** [comment]
The native checkbox and radio doesn't have cursor pointer.

**Comment by Samuell1** [comment]
@marcosmoura on mobile? or desktop?

**Comment by cawa-93** [comment]
@Samuell1 for my on Desctop, cursor is Default

**Comment by Samuell1** [comment]
@cawa-93 yes but i mean in material design, in material design lite is cursor pointer https://getmdl.io/components/index.html#toggles-section, for UX is better to have cursor pointer
