### ISSUE TITLE
About material design guidelines

### ISSUE THREAD

**Issue by fergardi** [marcosmoura/vue-material#548]
Hello.

This is more a question than a issue.

While developing new components based on material design guidelines, I face the following information, for example:

```css
Headline: Type 24sp, Leading 32sp
Subhead 1: Type 15sp, Leading 24sp
32sp line height
56dp padding between the top of button and the center of copy (allowing room for 1-3 lines of text)
24dp vertical padding
```

How does SP/DP translates to CSS font-sizes, font-weight, etc properties? I want to maintain heterogeneity with the rest of the components' font sizes and I'm curious how to do so. Can you elaborate a simple guide in the CONTRIBUTING docs for me?

Thank you.

**Comment by rascoop** [comment]
Hi,
Please refer to this https://material.io/guidelines/layout/units-measurements.html#units-measurements-density-independent-pixels-dp
**When writing CSS, use px wherever dp or sp is stated. Dp only needs to be used in developing for Android.**

**Comment by fergardi** [comment]
Got it, thanks!
