### ISSUE TITLE
Ripple effect not working (even on your site)

### ISSUE THREAD

**Issue by fourpixels** [marcosmoura/vue-material#554]
For some reason it seems I cannot see the ripple effect AT ALL. Even on your own demo website here: https://vuematerial.github.io/#/components/ink-ripple

I have some memories I've seen it working, but I might be wrong. I also tried making it work on my local machine, importing the distributed js file, but still nothing. Do I have to make anything or use some specific code in order to do so? Is it working on your screen? :)

### Steps to reproduce
Click on anything here: https://vuematerial.github.io/#/components/ink-ripple

### Which browser?

Chrome Version 56.0.2924.87 (64-bit)

### What is expected?
Ripple effect

### What is actually happening?

Nothing

**Comment by marcosmoura** [comment]
I couldn't reproduce this issue. It's working fine.
Which machine do you have? SO? Touchscreen monitor?

**Comment by fergardi** [comment]
I tested it on latest Chrome and Firefox, both desktop and mobile, and works fine for me. Other browsers don't deserve my time :P

**Comment by fourpixels** [comment]
I'm very sorry guys, there seemed to be some problem with my Chrome, which totally died, but tested ni other browsers and everything was perfect (ashamed)
