### ISSUE TITLE
How set Default text color as White?

### ISSUE THREAD

**Issue by cawa-93** [marcosmoura/vue-material#557]
I want set primary theme color as `green` (`#4caf50`). And I want set primary TEXT color as white. But by default text color is black.
In you [About](https://vuematerial.github.io/#/about) page `md-toolbar.main-header` looks exactly as I need. In your case, you override the default color of the text in several CSS rules. But I use a lot of elements in my application. And change the color for everyone - lot of code.

In #531 I tryed add option to `md_theme`. But perhaps there is a better way?

**Comment by fergardi** [comment]
Your selected color by Google Material Specs (https://material.io/guidelines/style/color.html#color-color-palette) uses black as font color, so the theme uses it. If you want white color, I recommend to switch your default green hue color to 600. You could use some specific css to achieve that result, but I wouldn't do that, as it breaks the theming purposes.
