### ISSUE TITLE
double class md-gutter

### ISSUE THREAD

**Issue by Akiyamka** [marcosmoura/vue-material#576]
```
<md-layout md-gutter>
    <md-layout md-flex="50"> .... </md-layout>
    <md-layout md-flex="50"> .... </md-layout>
</md-layout>
```
render to

```
<div class="md-layout md-gutter-md-gutter">
    <div class="md-layout md-flex-50"> ... </div>
    <div class="md-layout md-flex-50"> ... </div>
</div>

```
Pay attention to the class `md-gutter-md-gutter`. 
Probably cause in this part of the code **mdLayout.vue** at line 83:
`classes['md-gutter-' + this.mdGutter] = true;`

**Comment by Akiyamka** [comment]
The reason for this effect was precompilation PUG
Boolean Attributes processed from `div.md-layout(md-gutter)` in <div class="md-layout" md-gutter="md-gutter"></div>`
https://pugjs.org/language/attributes.html#boolean-attributes

**Comment by Samuell1** [comment]
Yes on codepen its working fine, http://codepen.io/Samuellsk/pen/yMYabM

**Comment by Akiyamka** [comment]
The problem can be avoid by using `div.md-layout(md-gutter="")` instead `div.md-layout(md-gutter)` in pug template
