### ISSUE TITLE
sidenav open triggers page scroll to bottom unexpectly

### ISSUE THREAD

**Issue by vuel** [marcosmoura/vue-material#579]
See: https://codepen.io/wenris/pen/QpjPQE

This problem is caused by this code

`this.$el.focus()`

in **src/mdSlidenav/mdSlidenav.vue** line 45.

Simple remove that line and the following line `this.$el.blur()` will fix it, I don't know if I'm right?

**Comment by stramec** [comment]
Hi @vuel - there was a similar discussion on the angular repo a while back around the point of $el.focus(), the workaround was pining the position of the sidenav to fixed.
[https://github.com/angular/material/issues/1891](https://github.com/angular/material/issues/1891)

I just dropped 
```
.md-sidenav {
  position: fixed  !important;
}
```

into my sidenav component <style> block and all was good again.

**Comment by vuel** [comment]
Hi @stramec 
Thank you for your reply, but adding the css doesn't work for me, now I cannot open the sidenav when clicking the menu button.
Help me: https://codepen.io/anon/pen/MpeoPL

**Comment by stramec** [comment]
@vuel - just add md-fixed as a class to the md-sidenav component.

 <md-sidenav class="md-left md-fixed" ref="sidenav">
[http://codepen.io/stramec/pen/vxKRYE](http://codepen.io/stramec/pen/vxKRYE)

I haven't looked why this is required, but it works.

**Comment by dennishu001** [comment]
Adding md-fixed does make the sidenav work again, however it doesn't solve the program of scrolling to bottom.
