### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by 0xFireball** [marcosmoura/vue-material#58]
Vue Material is by far my favorite Material Design library for Vue.

Angular Material has a very nice modal/dialog system; is adding a similar component to vue material on the  future roadmap?

thanks!

**Comment by marcosmoura** [comment]
Yeah. Dialog will be present after release v0.4.0.

**Comment by 0xFireball** [comment]
Awesome! I'm looking forward to it!

Is there support for making a menubar with dropdowns that work somewhat similarly to this?https://material.angularjs.org/latest/demo/menuBar

**Comment by marcosmoura** [comment]
@0xFireball Please ask about only one component per issue. This way is easy to track the answers and it's better to not have multiple subsjects. 
But answering your question: Not right now. But will be developed in the next releases. :)
