### ISSUE TITLE
list items inline

### ISSUE THREAD

**Issue by RSamal** [marcosmoura/vue-material#582]
How to make md-list-item inline ?

**Comment by stramec** [comment]
@RSamal - I'm not sure you can easily, I just tried to do it, but you have to hack a whole heap of stuff apart it seems. Probably would be easier to just create your own CSS using:
`ul.something li { display: inline; }`
and extending the vue-material styling?

**Comment by marcosmoura** [comment]
Why do you need the inline list? Maybe this should be done with a grid?
