### ISSUE TITLE
mdDialog new auto-open attribute.

### ISSUE THREAD

**Issue by 3luyka** [marcosmoura/vue-material#587]
Hello there. 
How about provide new `auto-open` (`false` by default) attribute to the mdDialog component? I think it would be very useful. Also I'm wondering about plugin, which will provide methods like (open/close).

**Comment by Samuell1** [comment]
Hey, i think this is not needed, you can autoopen dialog by running open function in mounted `this.$refs.MODAL.open()`

**Comment by 3luyka** [comment]
Yeah, I know about `mounted`, but I gets a lot of duplicated code. And `auto-open` would be really cool stuff for me.

**Comment by marcosmoura** [comment]
I think this logic should be in your side. I can't manage this state as you can have a custom template, for example. I will provide in the future a new way to interact with the component, to expose a better API.

**Comment by cdc1671** [comment]
Tried Samuell1's idea but I get a "Failed to execute appendChild" error...
