### ISSUE TITLE
Event Handlers do not work on Vue Material Comps

### ISSUE THREAD

**Issue by diverted247** [marcosmoura/vue-material#589]
### Steps to reproduce
If you add an event handler directly on a material comp, it will not fire.
If you wrap the material comp in a DOM element, the events on the element fire.
```
<div @click="hitme"><md-button>THIS HANDER FIRES</md-button></div>
<md-button @click="hitme">THIS HANDER NEVER FIRES</md-button>

Vue.use(VueMaterial)

var App = new Vue({
  el: '#app',
  methods:{
    hitme:function(){
      console.log("hit me called")
    }
  }
})
```

### Which browser?
all

### What is expected?
click handlers work

### What is actually happening?
click handlers directly on Vue Material components do not work.

### Reproduction Link
http://codepen.io/__ted__/pen/PpGpaB

**Comment by Samuell1** [comment]
You needs use native handlers on every vue component `@click.native="hitme"`

**Comment by diverted247** [comment]
Thanks!

**Comment by lmj0011** [comment]
here it is buried in the Vue docs: https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components
