### ISSUE TITLE
listening change event on md-file 

### ISSUE THREAD

**Issue by manjuk41** [marcosmoura/vue-material#599]
how to listening for change event on md-file component for image or video upload.

**Comment by Samuell1** [comment]
You need to listen to `@selected`, Check https://github.com/marcosmoura/vue-material/issues/585

**Comment by manjuk41** [comment]
thank you very much! it worked @Samuell1

**Comment by Samuell1** [comment]
Then is okay? Can you please close issue?

**Comment by manjuk41** [comment]
sorry for that @Samuell1

**Comment by emalihin** [comment]
Interestingly, it seems that @selected event doesn't contain .files aka array of the list of files, only individual .file arrays for each file.
