### ISSUE TITLE
demo with tooltip doesn't work on Firefox ?

### ISSUE THREAD

**Issue by mdartic** [marcosmoura/vue-material#6]
Hello, and thank you for publishing your great work on material design !

I've tried your github.io, and I'm using Firefox 49.

When I go to https://marcosmoura.github.io/vue-material/#/components/tooltip , nothing really happens.

In fact, an error appear in the console : `i.classList.forEach is not a function` .

It works on Chromium.

Maybe it's not vue-material, maybe it's vuejs, I don't really know.

I'm sure you'll find it quicker than me !

**Comment by marcosmoura** [comment]
Oh. I see. It lacks some tests, but I already know what is happening. That's because classList doesn't return a ```Array``` but a ```nodeList```. And nodeList types don't have a forEach method. 
I'll fix this really soon.

Thank you for trying and report this.

**Comment by marcosmoura** [comment]
Fixed.
