### ISSUE TITLE
Theming : background hue not setted

### ISSUE THREAD

**Issue by mathieucivel** [marcosmoura/vue-material#603]
Setting a custom background hue seems to not work properly

See https://jsfiddle.net/bvfbdLhw/

I think this is not the same issue as #560

**Comment by Linzdigr** [comment]
I guess it's the same issue as https://github.com/marcosmoura/vue-material/issues/355

**Comment by mathieucivel** [comment]
Oh right, I missed it.

**Comment by Morgul** [comment]
@mathieucivel Can you close this issue, and comment on #355 instead? (Trying to keep the issue list trimmed down while @marcosmoura is on vacation. 😀 )

**Comment by mathieucivel** [comment]
Sure.
