### ISSUE TITLE
Speed Dial issue after click on child

### ISSUE THREAD

**Issue by pdipasqua** [marcosmoura/vue-material#604]
As title, when click on the child of speed dial this not disappear when lost focus, 
close it's possible only when click out.
Sorry for my english!

P

**Comment by Samuell1** [comment]
I think its fixed? https://github.com/marcosmoura/vue-material/pull/508

**Comment by pdipasqua** [comment]
Ok thanks, I installed the last 0.7.1 version whit npm but this commit does not appear? I tried to download an update with npm but nothing change.

**Comment by Samuell1** [comment]
Its in develop branch

**Comment by pdipasqua** [comment]
perfect, thank you !!! SOLVED
