### ISSUE TITLE
Tooltip trigger, is it possible?

### ISSUE THREAD

**Issue by fortil** [marcosmoura/vue-material#605]
Hi to all

I'm searching, how to launch a tooltip without the mouse hover the element?

Any idea?

Thanks

**Comment by VicarEscaped** [comment]
Just add **ref** on tooltip component and call `open()` method
[codepen](http://codepen.io/anon/pen/ZeJEqb)

**Comment by fortil** [comment]
great!! 
I didn't know that

thanks

**Comment by VicarEscaped** [comment]
@fortil just look at the source code.

**Comment by marcosmoura** [comment]
I will create a better trigger function later, but for now this is the best approach. Thank you @VicarEscaped !
