### ISSUE TITLE
Feature request: Swipeable tabs

### ISSUE THREAD

**Issue by blomdahldaniel** [marcosmoura/vue-material#606]
Hi!
This project is flat out awesome!!
But something I am missing is the ability to swipe between tabs.  I see that you have swipeable tab headers for when they are full but not swiping tabs for touch devices..?
Am I blind or is there no such feature yet?

**Comment by Samuell1** [comment]
https://github.com/marcosmoura/vue-material/pull/430

**Comment by blomdahldaniel** [comment]
But #430 only requests swipeable tab headers? That is why opened this issue. This request is about swiping between tab pages. So press your thumb at the middle of the content and drag it away to go to the next. A very intuitive feature. 

But I didn't see where #430 focused on other things than the header..?

**Comment by Samuell1** [comment]
@blomdahldaniel oh sorry i miss read

**Comment by fergardi** [comment]
#549

**Comment by blomdahldaniel** [comment]
@fergardi that is not the same thing as swipeable tabs. Sure it's nice and all but its not the same thing as TABS being swipeable.

**Comment by fergardi** [comment]
Actually, they are tabs. Modified and styled, but basic md-tabs. Maybe I can adjust my code to add md-swipeable property to the md-tabs. I'll work on that and make a PR.

**Comment by blomdahldaniel** [comment]
OoOoo! That would be awesome! 😃

**Comment by phil1996s** [comment]
@fergardi How is the status of implementation the swipe-functionality to md-tabs?
