### ISSUE TITLE
md-input-container -  [Vue warn]: Duplicate presence of slot "default" found in the same render tree

### ISSUE THREAD

**Issue by AndreiaMatiasSilva** [marcosmoura/vue-material#611]
[Vue warn]: Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors. 
(found in component <md-input-container>)

I'm having problems with nested vue materials components, as  md-input-container, md-avatar they don't work and there erros like "Vue warn]: Error when rendering component"

Although this components don't work simpler components as md-spinner works just fine.

The versions that I'm using are:
```
   "vue": "~2.0.1",
    "vue-material": "^0.7.1",
    "vue-template-compiler": "~2.0.0"
```

Thank you

**Comment by Samuell1** [comment]
Can you please provide reproduction example? (codepen, jsfiddle)

**Comment by marcosmoura** [comment]
Vue Material only works with Vue 2.1.
