### ISSUE TITLE
Radio button selection not working

### ISSUE THREAD

**Issue by brandonn1231** [marcosmoura/vue-material#612]
The radio buttons are showing up, and when I click on them the click animation shows up, but no selection is made - the radio button still remains unselected.

my main.js file:
```
  import Vue from 'vue';
  import VueMaterial from 'vue-material';
  Vue.use(VueMaterial);
```

my index.html:
  ...
 `<link rel="stylesheet" type="text/css" href="./node_modules/vue-material/dist/vue-material.css">`
  ...

My component file (which is called upon by main component file):
 ```
 <template>
    <div>
       <md-radio v-model="radio1" id="my-test1" name="my-test-group1" md-value="1">{{options[0].label}}</md-radio>{{radio1}}
     <md-radio v-model="radio1" id="my-test2" name="my-test-group1" md-value="2">{{options[1].label}}</md-radio>
    </div>
```

**Comment by Samuell1** [comment]
Can you please provide reproduction link to codepen / jsfiddle?

**Comment by brandonn1231** [comment]
How do I get vue-material to work on jsfiddle?

**Comment by Samuell1** [comment]
@brandonn1231 here is some start example http://codepen.io/vue-material/pen/VmMrYW

**Comment by brandonn1231** [comment]
http://codepen.io/anon/pen/MpONGY

When I try clicking on the radio button, it doesn't get selected.  Also, when I include v-model="radio1", the radio button disappears?  What am I doing wrong?
