### ISSUE TITLE
The  wave  effect Can be canceled?

### ISSUE THREAD

**Issue by youngchen1987** [marcosmoura/vue-material#616]
The  wave  effect Can be canceled?
I can set it when i do not use  it  on low-end device

**Comment by marcosmoura** [comment]
Yes. As you can look [here](https://vuematerial.github.io/#/components/ink-ripple), you can disable it globally:
https://vuematerial.github.io/#/components/ink-ripple

**Comment by richardaum** [comment]
Is there a way to do it globally?
