### ISSUE TITLE
 the  icons  settings

### ISSUE THREAD

**Issue by youngchen1987** [marcosmoura/vue-material#617]
![image](https://cloud.githubusercontent.com/assets/11566474/24129232/2c55cba4-0e1c-11e7-8e1c-b09cda535fd5.png)

we can  use :
1.
"material-design-icons": "^3.0.1"
![image](https://cloud.githubusercontent.com/assets/11566474/24129242/49b07410-0e1c-11e7-9533-9ff830c5d1db.png)
2.
import 'material-design-icons/iconfont/material-icons.css'

![image](https://cloud.githubusercontent.com/assets/11566474/24129252/5ba81542-0e1c-11e7-9de6-90f4394c38e3.png)

3. npm  install  --save material-design-icons
that‘s OK

**Comment by marcosmoura** [comment]
Yes. It's the same. And you can also use custom icons, like Font Awesome.

**Comment by Samuell1** [comment]
I too using packages for icons and fonts `roboto-fontface` and `material-design-icons-iconfont`
