### ISSUE TITLE
v-on:click doesn't work in 0.7.1, worked fine in 0.6.3

### ISSUE THREAD

**Issue by henkburgstra** [marcosmoura/vue-material#630]
I reverted back from 0.7.1 to 0.6.3 because v-on:click doesn't work in 0.7.1.

### Steps to reproduce
Create an element with an v-on:click attribute

### Which browser?

I tried Chrome, Firefox and IE on Windows, Chrome, Firefox and Safari on Mac OS

### What is expected?
the v-on:click event handler to be called

### What is actually happening?

nothing, also no error messages. 0.6.3 works fine. Other gui toolkits that I researched as possible alternatives to vue-material also work fine (but are not as good as vue-material imho).
I use vue-material by including vue-material.css and vue-material.js

**Comment by eduardo76** [comment]
[https://github.com/marcosmoura/vue-material/releases/tag/v0.7.0](https://github.com/marcosmoura/vue-material/releases/tag/v0.7.0)

It is on documentation.

## Breaking changes:

- To avoid issues and conflicts between multiple events on buttons and other "clickable" components the internal @click event don't work anymore. Use @click.native instead.

- Only for contributors: To build Vue Material is now needed to upgrade all dependencies. Vue Material uses Webpack 2 under the hood and all dependencies were bumped to the latest.

**Comment by henkburgstra** [comment]
I'm sorry, I didn't spot that. Thank you very much for your quick response!

**Comment by Morgul** [comment]
@henkburgstra can you close this issue?
