### ISSUE TITLE
Gender Neutral Language

### ISSUE THREAD

**Issue by CaptainAchilles** [marcosmoura/vue-material#633]
On the website, under the md-option section,
```
Disable the button and prevent his actions. Default false
```
The word `his` should be replaced with something more appropriate.

https://vuematerial.github.io/#/components/select

**Comment by Morgul** [comment]
I agree with this. As a native english speaker, it sounds strange. The more common way to refer to abstract/genderless items would be with "its" (not to be confused with the possessive "it's". Isn't English fun?)

@CaptainAchilles Would you mind checking for this across the documentation and putting together a pull request?

**Comment by Morgul** [comment]
@marcosmoura or @CaptainAchilles can you close this issue, now that the PR has been merged?
