### ISSUE TITLE
[md-tabs] Reactivity issue - md-tabs not displaying the correct amount of tabs when dynamically updating

### ISSUE THREAD

**Issue by driesrobeyns** [marcosmoura/vue-material#638]
### Steps to reproduce
When dynamically adding a `md-tab`, the `md-tabs` is not updated immediately, only at the next value update.

### Which browser & packages?
Latest `vue-material`, `vue 2.2.5`

### Reproduction Link
The example below shows that the tabs are not immediately updated when using the select input on top, however the div's above are.

When you use the select input twice you will see that the tabs will update to the previous number selected and not the current number. They are always lagging behind one selection.

Selecting a number than clicking on an non-active tab will also trigger the md-tabs to update to the correct number of tabs.

http://codepen.io/anon/pen/WpyKGB

### Conclusion

Is this working as expected? Should we call a updateTabData() manually in this case? Or is there another solution?

**Comment by bolerodan** [comment]
I believe this issue is already fixed for the next release.

**Comment by driesrobeyns** [comment]
Yeah just found it. Pull request #545. Thanks for the heads up.
