### ISSUE TITLE
md-input-container issue (v0.3.0)

### ISSUE THREAD

**Issue by fat4lix** [marcosmoura/vue-material#64]
Hello, i've installed new 0.3.0 version. I use default 'select' template from demo, and i get errors in console: 

> vue.js:2643 [Vue warn]: Error when rendering component md-input-container:
> vue.js:2264 TypeError: Cannot read property 'constructor' of null(…)

All other components still works fine.

Any idea?

**Comment by marcosmoura** [comment]
Are you using the full build or the standalone component?

**Comment by fat4lix** [comment]
I use full build, and other components such as md-input, md-card, md-list working correctly.

Vue version 2.0.5

```
import VueMaterial from 'vue-material'
Vue.use(import VueMaterial from 'vue-material')
```

**Comment by marcosmoura** [comment]
Gotcha! If your v-model is invalid, doesn't exists or is null/undefined this error would come up. It's already fixed and will be delivered on the very next minor release.

Right now you can change your model value to an empty string to avoid this problem, but I will release the next version really soon.

Thanks!
