### ISSUE TITLE
md-input fails to render the input appropriately.

### ISSUE THREAD

**Issue by bbuck** [marcosmoura/vue-material#663]
### Steps to reproduce
Create a basic `md-input` inside and `md-input-container`. Adding a placeholder seems to force it to render correctly (for whatever reason), but as-is without a placeholder it fails to render.

### Which browser?
Vue: 2.2.6
VueMaterial: 0.7.1
OS: macOS Sierra 10.12
Chrome: 56

### What is expected?
md-input should render an input with floating label as expected and demonstrated on the vue-material demo site.

### What is actually happening?
The label is squished and the input is rendering at 1 px wide.

### Reproduction Link
CodePen link: http://codepen.io/bbuck/pen/VpNprL

**Comment by fergardi** [comment]
It's weird, but as soon as you put that components outside the md-layouts, they works as expected.

**Comment by d3radicated** [comment]
Adding `width: 100%` to the form fixes it.

**Comment by bbuck** [comment]
Interesting. That seems like odd behavior, but I suppose it makes sense.

**Comment by pablohpsilva** [comment]
```html
<template id="todo-form-template">
  <form novalidate @submit.prevent="addTodo" style="width:100%">
    <md-input-container>
      <label>What do you need to do?</label>
      <md-input v-model="todoText" />
    </md-input-container>
  </form>
</template>
```
