### ISSUE TITLE
[md-select] Not rendering correctly with numeric values

### ISSUE THREAD

**Issue by jaydubyasee** [marcosmoura/vue-material#672]
I have a numeric data item which I wish to use to control a dropdown list. However Vue Material is not rendering the dropdown correctly.

### Steps to reproduce
Create an md-select element with a v-model. Use md-options with a string or numeric value.
Set the data element of the v-model to one of the options in the md-select element.
If the data element is numeric the md-select will not show the selected option when rendered.

### Which browser?
MacOS Sierra 10.12.3
Chrome 57.0.2987.133 (64-bit)
Safari 10.0.3 (12602.4.8)
Vue 2.2.4
Vue Material 0.7.1

### What is expected?
Expecting dropdown to display correct day of week

### What is actually happening?
Although the correct option is selected (as can be seen when clicking on the dropdown) the selected option is not displayed when the dropdown is rendered.

### Reproduction Link
See [codepen](http://codepen.io/jaydubyasee/pen/qrzNNr)

**Comment by pablohpsilva** [comment]
@jaydubyasee hi!

This issue **ain't** a real issue. You just forgot to add the `<md-input-container>` to wrap around your `md-select`.

```html
<md-input-container>
  <md-select name="wrong" id="" v-model="day1" placeholder="(day...)">
    <md-option :value="1">Sunday</md-option>
    <md-option :value="2">Monday</md-option>
    <md-option :value="3">Tuesday</md-option>
    <md-option :value="4">Wednesday</md-option>
    <md-option :value="5">Thursday</md-option>
    <md-option :value="6">Friday</md-option>
    <md-option :value="7">Saturday</md-option>
  </md-select>
</md-input-container>
```

Remember: `:value="3"` and `value="3"` in Vue.js are different!

One last thing: please, remove the CSS rule or, at least, be specific:
```
* {
  padding-left: 20px;
}
```

**Comment by jaydubyasee** [comment]
Thanks @pablohpsilva . My mistake.

btw the css rule was only for the fiddle.

**Comment by pablohpsilva** [comment]
You're welcome bro @jaydubyasee :D
