### ISSUE TITLE
Feature Request: Multi Column sort for Table

### ISSUE THREAD

**Issue by miseeger** [marcosmoura/vue-material#68]
Hi, just came across and thought that multi column sort would be the icing on your Table cake :wink:

**Comment by marcosmoura** [comment]
@miseeger Well. This is not documented on the Material Design specs. I can develop something like that on the future. We must think in some aspects of the component:
* How can we fire an event to the parent component? With both sort options?
* If the user change the order to be 'desc' and the other column is in 'asc' order. Should we change both? Should be opt-in? Or we can let them separated?

What do you think?

**Comment by miseeger** [comment]
@marcosmoura This suddenly came into my mind :wink: And you see: I don't know the MD specs, either ... But to answser your points:

- Do you mean how to implement this technically or just on which event is to be listened? (if for listening: I'd do it on CRTL-Click)
- 'desc' and 'asc' changing should imho only affect the clicked column. But with multiple the states should be: 'asc','desc',off (off in order to switch off column sort in a 'multiple-sort' scenario)

Cheers.

**Comment by marcosmoura** [comment]
I see. I will think about that. Maybe on after the next release! :wink:

**Comment by miseeger** [comment]
That'd be just great 😎 👍
