### ISSUE TITLE
router-link to named route

### ISSUE THREAD

**Issue by emalihin** [marcosmoura/vue-material#682]
Hi! First of all, thank you for building such a quality big project, it helped me get into the Vue.js world so quickly! 

Now that I am finally onto bigger and more interesting project I found that I cannot create a router-link to a named route. Example route:

```
{ path: '/user',
      component: UserSpace,
      children: [
        {
          path: 'contracts',
          component: Contracts,
          name: 'user-contracts'
        },
        ....
    ]
}
```

When I use md-button I set it up like this and it works:
`<md-button @click.native="$router.push({ name: 'user-contracts' })" class="md-raised md-primary">Contracts</md-button>`

However I am now integrating the Sidenav component, and inserting the button there looks strange, so I checked the docs/src/App.vue of this project and saw that the router-link is used on this site. 
The issue seems to be that the to="" only accepts routes by path, and doing something like to="{ name: 'user-contracts' }" results in such a path: http://localhost:8080/#/user/{ name: 'user-contracts' }.

I tried using div instead, applying the classes that router-link component gets, however none of it seemed to work - the button doesn't seem to be clickable/nothing happens on click, also the width of the button is not full sidenav width. I have a feeling that I'm missing something small to make it look/behave like on this site, but using the name route.

Any help is appreciated!

**Comment by d3radicated** [comment]
It treats the value as a string because it is not binded to the prop. Try using `v-bind` or its shorthand syntax:

`v-bind:to="{ name: 'user-contracts' }"` or `:to="{ name: 'user-contracts' }"`

**Comment by emalihin** [comment]
This explains it and it works! Thank's a lot for your response, I guess this will help me with few other things as I go :)
