### ISSUE TITLE
Theme configuration should accept hex codes

### ISSUE THREAD

**Issue by alansutherland** [marcosmoura/vue-material#688]
When I tried to use a custom hex code or it's string equivalent I got the error:
Uncaught TypeError: Cannot read property '500' of undefined

this was my code:

Vue.material.registerTheme({
  default: {
    primary: 'crimson',
    accent: '#ed143d'
  }
}) 

I realised it's because the palette is limited to the colors listed here https://vuematerial.github.io/#/themes/configuration

It would be great if hex codes were recognised.

**Comment by alansutherland** [comment]
I see that I can change the hue of each color but would custom hex codes be a huge issue to add?

**Comment by alansutherland** [comment]
closing as I've now read this https://material.io/guidelines/style/color.html#color-color-palette

**Comment by patrixd** [comment]
I have my brand colors and I can't change them, is there any way to specify the rgb color?

**Comment by tfsimondouglas** [comment]
For those googling hard-out for a solution see here: https://github.com/vuematerial/vue-material/issues/250
