### ISSUE TITLE
md-list issue (v0.3.0)

### ISSUE THREAD

**Issue by javaday** [marcosmoura/vue-material#70]
The md-list component is not updating when the value of computed data changes. We have the following in a component template:

<md-list v-if="user">
...
</md-list>
<md-list v-else>
...
</md-list>

"user" is a computed value configured as follows:

computed: {
   ...mapGetters({
      user: 'currentUser'
   })
}

When "currentUser" is updated from null to an object the md-list is not re-rendered. We have the same scenario in another component with the v-if on a div and it works fine.

Also, the md-list works as expected in version 0.2.0. We rolled back to confirm that.

**Comment by 0xFireball** [comment]
@javaday I have noticed this issue as well.

**Comment by marcosmoura** [comment]
Sorry about that. Was a problem with v-once. You can see the root cause here: #69

**Comment by 0xFireball** [comment]
@marcosmoura Unfortunately I'm still noticing a similar issue:

This is my code:

```html

          <!--SEE THE NOTE BELOW THE CODE!!!-->
          <div v-for="ufile in uploadingFiles">
          </div>

          <md-list class="custom-list md-triple-line" v-md-theme="uploadingTheme">
            <md-subheader>{{ progressHeader }}</md-subheader>
            <!-- In-progress Files -->
            <div v-for="ufile in uploadingFiles">
              <md-list-item>
                <md-avatar>
                  <md-icon class="md-primary">file_upload</md-icon>
                </md-avatar>

                <div class="md-list-text-container">
                  <span>{{ ufile.name }}</span>
                  <span>{{ ufile.kind }}</span>
                  <p>{{ ufile.progress }}% uploaded</p>
                </div>

                <md-button class="md-icon-button md-list-action">
                  <md-icon class="md-primary">star</md-icon>
                </md-button>

                <md-divider class="md-inset"></md-divider>
              </md-list-item>
            </div>
          </md-list>
```

See the div with the comment above it that says to look at this note?

When that div is included, everything works as expected, `md-list` updates reactively, etc. When it's not, the `md-list` does NOT update reactively.

I have confirmed this issue by inspecting the DOM; without that extra div binding to the vm's property, DOM updates for `md-list` aren't being triggered.

There likely is some kind of issue with `md-list` causing this.

**Comment by marcosmoura** [comment]
Did you update to the new 0.3.1?

**Comment by 0xFireball** [comment]
Sorry, I hadn't updated. I have confirmed that it is fixed.

Thanks for your quick help!



On Tue, Nov 15, 2016 at 10:07 PM -0800, "Marcos Moura" <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you update to the new 0.3.1?

-

**Comment by marcosmoura** [comment]
Oh. Great. Was a silly misuse of v-once. Thank you!
