### ISSUE TITLE
Form Validator?

### ISSUE THREAD

**Issue by thearabbit** [marcosmoura/vue-material#700]
I base on `Meteor`, and use `Bootstrap + AutoForm of Blaze` [AutoForm](https://github.com/aldeed/meteor-autoform)
But now I would to try `Meteor + Vue-Material`, but have problem with `Form Validator`.
Please help me.

**Comment by Samuell1** [comment]
How we can help you, if you dont provide example, error report ?

**Comment by thearabbit** [comment]
It mean that I would like to ask:
have any `vue-material form validator` to manage the `form`?
Example: 
- [AutoForm](https://github.com/aldeed/meteor-autoform) for `Blaze in Meteor`
- [Uniforms](https://github.com/vazco/uniforms) for `React`

**Comment by Samuell1** [comment]
Vue-material is only UI components, you need do yourself your logic stuff or find other plugins

https://github.com/logaretm/vee-validate
https://github.com/fergaldoyle/vue-form
more... https://github.com/search?utf8=%E2%9C%93&q=vue+form+validator

**Comment by thearabbit** [comment]
Thanks for your reply.
