### ISSUE TITLE
md-row within md-column

### ISSUE THREAD

**Issue by meta0102** [marcosmoura/vue-material#709]
Hi,
please see https://jsfiddle.net/31Lkxupv/2/
what i want to achieve is that start and end appear in the same row
i've already tried a lot of md-layout nested combinations....

thanks

**Comment by zapping** [comment]
Is this what you are looking for https://jsfiddle.net/2bs7xa3d/2/
There are different ways to go about this. I tried this layout with the similar grouping of inputs that you have in your pen.

**Comment by meta0102** [comment]
Perfect, thanks @zapping
