### ISSUE TITLE
Flexbox Grid System

### ISSUE THREAD

**Issue by marcosmoura** [marcosmoura/vue-material#78]
Responsive layouts in material design adapt to any possible screen size. This UI guidance includes a flexible grid that ensures consistency across layouts, breakpoint details about how content reflows on different screens, and a description of how an app can scale from small to extra-large screens.

Specs for [Flexbox Grid System](https://material.google.com/layout/responsive-ui.html)

![Flexbox Grid System](https://material-design.storage.googleapis.com/publish/material_v_9/0B8olV15J7abPSGFxemFiQVRtb1k/layout_adaptive_breakpoints_01.png)

**Comment by jtouzy** [comment]
Maybe you can look at http://flexboxgrid.com/ : Grid system based on flexbox grids (classes names are bootstrap-like, but it's very lightweight).
Just a suggestion :-)

**Comment by marcosmoura** [comment]
Hi @jtouzy 

I like the idea. I will get some inspirations on [http://flexboxgrid.com](FlexboxGrid) and on [Structure](http://kenwheeler.github.io/structure/)
But the API that I want to develop will be something like that:

``` vue
<md-layout md-row md-sm-column>
  <md-layout md-row>
    <md-layout md-flex></md-layout>
  </md-layout>

  <md-layout md-column>
    <md-layout md-flex></md-layout>
  </md-layout>
</md-layout>
```

**Comment by jtouzy** [comment]
@marcosmoura 
Do you want to have a fixed number of columns in a single row ? I think it could be better than a automatic columns division system by default, even if it could be great in some cases...

Something like :

```vue
<!-- Fixed columns number divided (maybe 12 or something by default) -->
<md-layout md-row md-sm-columns>
  <md-layout md-column="3"></md-layout>
  <md-layout md-column="9"></md-layout>
</md-layout>
<!-- Auto sized columns 50%/50% -->
<md-layout md-row md-sm-columns>
  <md-layout md-column></md-layout>
  <md-layout md-column></md-layout>
</md-layout>
```

**Comment by sombriks** [comment]
Hi, 

why not https://material.angularjs.org/HEAD/layout/options

**Comment by marcosmoura** [comment]
Yeah. Will have a way to specify the size, but I like the idea to pass the percentage. WIll be close to the Angular Material "flex" attribute.

**Comment by marcosmoura** [comment]
**Already in progress**

The API will be "simple", I think. The following options will be available:

* md-tag
* md-row 
* md-row-xsmall 
* md-row-small 
* md-row-medium 
* md-row-large 
* md-row-xlarge 
* md-column 
* md-column-xsmall 
* md-column-small 
* md-column-medium 
* md-column-large 
* md-column-xlarge 
* md-flex / md-flex="33" - Layout size
* md-gutter / md-gutter="8" - Layout 'padding' between layouts

Examples:
``` vue
<md-layout :md-gutter="16">
  <md-layout> ... </md-layout>
  <md-layout :md-flex="66"> ... </md-layout>
</md-layout>

<md-layout :md-gutter="16">
  <md-layout :md-flex="75"> ... </md-layout>
  <md-layout> ... </md-layout>
</md-layout>
```

``` vue
<md-layout :md-gutter="16">
  <md-layout md-column :md-gutter="16">
     <md-layout :md-flex="20"> ... </md-layout>
     <md-layout> ... </md-layout>
  </md-layout>

  <md-layout md-column :md-gutter="16">
     <md-layout :md-flex="50"> ... </md-layout>
     <md-layout> ... </md-layout>
     <md-layout> ... </md-layout>
  </md-layout>
</md-layout>
```

**Comment by jtouzy** [comment]
Maybe you can add some directives like md-hide-xsmall, md-visible-xsmall... ?
It's not directly related to the GridSystem but rather to the Responsive mechanism.

**Comment by marcosmoura** [comment]
Yeah. Will be present as well. Thanks to remind me about that.

**Comment by piotrgulbis** [comment]
Looking forward to this! Great stuff!

**Comment by marcosmoura** [comment]
First part done in the [components/mdLayout](https://github.com/marcosmoura/vue-material/tree/components/mdLayout) branch.
Now I will develop the "responsive" part.

**Comment by marcosmoura** [comment]
Already available! Enjoy!

**Comment by huhk-sysu** [comment]
How about adding a helper property to set the element's `justify-content` like `space around`
