### ISSUE TITLE
[request] Menu bar to be implemented next

### ISSUE THREAD

**Issue by mygnu** [marcosmoura/vue-material#8]
Can I please suggest that Menu bar to be the next in pipeline as it is required on almost all websites.

**Comment by marcosmoura** [comment]
Menu bar? Like cascading menus? Or you mean the dropdown menu?
https://material.google.com/components/menus.html#menus-usage

**Comment by mygnu** [comment]
I was just looking at the new components in projects. Did I miss something

**Comment by marcosmoura** [comment]
Well. Both components ```md-menu``` and ```md-menu-bar``` are on my roadmap.
The first one will have a higher priority and will look like a ```md-select``` and the second have a behaviour like the Google Docs toolbar.

**Comment by mygnu** [comment]
Awesome

**Comment by metamet** [comment]
Do you have the roadmap published anywhere? Unfortunately, the applicability of this is limited to me until [data tables](https://material.google.com/components/data-tables.html) are implemented.

**Comment by marcosmoura** [comment]
Not yet. But I will publish the milestones this week. Just need to fix some bugs and then I will focus on this new components.

**Comment by marcosmoura** [comment]
The md-menu component it's already being implemented. Keep track on #19
