### ISSUE TITLE
Select Position Issue

### ISSUE THREAD

**Issue by DomenicRoti** [marcosmoura/vue-material#81]
Currenlty if open a select box (or a menu) it doesn't stay in position in relation to the page.

For example, you can open a select and scroll up or down the page but the the select box doesn't move with it.

**Comment by marcosmoura** [comment]
This is a enhancement. I will address this to the next minor version but I'm already fixing it! Thank you for reporting this.

**Comment by DomenicRoti** [comment]
Great, thank you.

**Comment by marcosmoura** [comment]
Will be fixed along with Dialogs :)

**Comment by marcosmoura** [comment]
Fixed <a href="https://github.com/marcosmoura/vue-material/commit/e065ad65ac8556b41e4649d97daf9090e006f13d">e065ad6</a>
