### ISSUE TITLE
Button type not rendering properly

### ISSUE THREAD

**Issue by ryanmagoon** [marcosmoura/vue-material#86]
When I have
`<md-button type="submit">Button</md-button`

The type on the rendered button is `button` instead of `submit`

This is a bug right? My workaround was this:
`<button type="submit" class="md-button md-raised md-accent">Login</button>`

**Comment by marcosmoura** [comment]
Which version are you using? I'm testing with the latest and everything is working. 
Codepen: http://codepen.io/vue-material/pen/WGavBE
