### ISSUE TITLE
The blur method of 'md-input' not work

### ISSUE THREAD

**Issue by qurioust** [marcosmoura/vue-material#87]
Try to add a blur method to 'md-input' component, but it seems not work. 
`<md-input type="email" v-model="email" @blur="fieldValidation"></md-input>`
Does not it support this usage?

**Comment by marcosmoura** [comment]
Oh. Should support, right. I can confirm that the blur, focus, input, and keyup events aren't working. I will fix this ASAP.

**Comment by marcosmoura** [comment]
Well. As you can see on the <a href="https://vuejs.org/v2/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on-changed">Vue.js migration guide</a> all the "native" browser events on custom components (like md-input) should be used with ```.native``` modifier:
``` html
<md-input @focus.native="handler"></md-input>
```

**Comment by qurioust** [comment]
@marcosmoura Thanks a lot. 👍
