### ISSUE TITLE
Issue with md-table-pagination on an Electron app

### ISSUE THREAD

**Issue by pauloramires** [marcosmoura/vue-material#88]
Hi,
while using the md-table-pagination component on an electron app I got the following error:
<img width="540" alt="electron-table-issue" src="https://cloud.githubusercontent.com/assets/1428629/20382744/563ef966-ac94-11e6-9f76-d5c782fdcf7c.png">
I have identified that this error is thrown by src/utils/getClosestVueParent.js, and that if the $parent argument is initialised as an empty object then it goes away, and the component works perfectly.
This is working for me:
```javascript
let getClosestVueParent = ($parent = {}, cssClass) => { ... }
```
I am using [electron-vue](https://github.com/SimulatedGREG/electron-vue) by **@SimulatedGREG**.
Could you have a look at it? 
PS: it would be useful if you could also include a non-uglyfied version of vue-material.js in the module package (e.g. vue-material.debug.js) so that we could more easily contribute to the resolution of this kind of issues without having to compile the module from source.

Many thanks!
Paulo

**Comment by javaday** [comment]
I just ran into this myself.

**Comment by javaday** [comment]
After seeing the fix suggested by @pauloramires, I figured out that the root Vue component has an undefined $parent property. So I added "this.$parent = {};" to the root component's mounted handler and I don't get the error anymore.

So, this seems to be a viable work around until the Paulo's pull request is merged.

**Comment by marcosmoura** [comment]
Oh yeah. I will take a look at this. This will be fixed on the very next fix version.

**Comment by pauloramires** [comment]
Hi Marcos,
after updating to v0.3.3 I still get the 'Cannot read property '$el' of undefined' error.
I noticed that the culprit is the **md-table-pagination** component. If I remove it from the view, then the error is gone.
