### ISSUE TITLE
Please provide better access to event originator on event handlers and improve docs

### ISSUE THREAD

**Issue by kristianmandrup** [marcosmoura/vue-material#89]
I'm pleased to see a lot of improvement since last time I checked (0.2.0)

However I still have trouble using event handlers efficiently such as for [mdCheckbox](https://github.com/marcosmoura/vue-material/blob/master/src/components/mdCheckbox/mdCheckbox.vue) 

I also wish your code examples would better demonstrate this usage

```js
      toggleCheck($event) {
        if (!this.disabled) {
          this.checked = !this.checked;
          this.$emit('change', this.checked, $event);
          this.$emit('input', this.checked, $event);
        }
```

You currently trigger the usual checkbox event `change` and `input` which is great...

```html
    <md-checkbox
      v-for="choice in prompt.choices"
      :name="prompt.name"
      :id="prompt.name"
      class="md-primary"
      @change="chosen"
      v-model="choice.value">{{ choice.label }}</md-checkbox>
```

VM

```js
  methods: {
    chosen (value, $event) {
      console.log('checkbox value', value, $event)
      this.$store.dispatch('choice', value)
    }
  }
```

However all we get access to is the new value `true` and a `MouseEvent` which is sadly not very useful. What is needed is a reference to the checkbox element that originated the event, not the container.

From the `$event` (ie `MouseEvent`) we can access the `srcElement` which provides the container `class="md-checkbox-container"` and from there we can get the checkbox as the first child of the container. This is very brittle, based on deep diving into the internal DOM structure of the component and also rather cumbersome...

Would be more sensible if the checkbox `el` was passed as an argument so we would have direct access/reference to the checkbox for which the click was made.
Cheers!

```js
  methods: {
    chosen (value, $event, el) {
      console.log('checkbox value', value, el.name)
      this.$store.dispatch('choice', el.name, value)
    }
  }
```

However the vue `changed` handler doesn't take a third argument. What is hence needed is perhaps for the `$event` to be transformed so that the `srcElement` is the checkbox element and not the container?

**Comment by kristianmandrup** [comment]
Currently I have to do the following (rather ugly!)

```js
    chosen (value, $event) {
      let el = $event.srcElement.querySelector('input[type="checkbox"]')
      console.log('checkbox value', value, el)
      this.$store.dispatch('choice', value, el)
    }
```

**Comment by marcosmoura** [comment]
I will take a look at this. Maybe I need to pass the event in a different way. I scheduled this to the next minor version.

**Comment by kristianmandrup** [comment]
Maybe just add an extra property on the `$event` like `srcInputElement`
