### ISSUE TITLE
suggestion for Getting Started page

### ISSUE THREAD

**Issue by logol** [marcosmoura/vue-material#92]
Hey,

just a small suggestion for the [Getting Started](https://marcosmoura.github.io/vue-material/#/getting-started) page.

For people who want to try vue-material without using node.js or where _import_ is not available, it might be nice to know that besides

```
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="path/to/vue-material.css">
<script src="path/to/vue-material.js"></script>
```

and

```
Vue.material.theme.register('default', {
  primary: 'cyan',
  accent: 'pink'
})
```

The following is needed to load vue-material to vue

```
Vue.use(VueMaterial.default)
```

Maybe you can add an additional section below the "_ES6 AMD_"  tabs in the **Usage** part like you did for "_Or download from Github and reference the script and the stylesheet in your HTML_" in the **Installation** part.

PS: Thanks for the great work :)

**Comment by marcosmoura** [comment]
Hi @logol. I liked the idea, but this VueMaterial.default is not ideal. I will change this to VueMaterial only, with no default. This is definitely a bug on the build scripts (webpack setup). I will fix this ASAP. Sorry about that. :|

**Comment by logol** [comment]
okay good point, I think without ".default" it would be a bit more self explanatory

**Comment by marcosmoura** [comment]
```Vue.use(VueMaterial.default)``` will no longer work. You should use ```Vue.use(VueMaterial)``` instead.
