### ISSUE TITLE
Question : grid system

### ISSUE THREAD

**Issue by rwatts3** [marcosmoura/vue-material#93]
Is there currently a grid system for this project? 

For example in Materializecss you can add a class of col s-6 ...

-V/R

Ryan

**Comment by mygnu** [comment]
its in the pipeline please see #78

**Comment by marcosmoura** [comment]
Yep. Will be done by the end of this month. :)

**Comment by rwatts3** [comment]
I see this was closed and a new release for version `0.4.0` Just wondering if a grid system was implemented within this release ?

**Comment by marcosmoura** [comment]
Not. Will be in v0.5.0. Check out the [Milestones](https://github.com/marcosmoura/vue-material/milestones) Thanks!
