### ISSUE TITLE
Question/Enhancement: Tab with dynamic data

### ISSUE THREAD

**Issue by Stabzs** [marcosmoura/vue-material#94]
All of the documentation examples illustrate static content.  In these situations, the resizing works perfectly..

However, I would like the ability to dynamically load data for a tab and then have the resize kickoff for the content.  My scenario is roughly as follows:

```
 <md-tabs>
     <md-tab id="Inventory" md-label="Inventory">
         <inventory-tab :items="currentInventory"></inventory-tab>
```

In this example, on render the custom inventory-tab component is instantiated and the property is bound.  Once user selection kicks off filters, an ajax call would populate `this.currentInventory`, pushing the data to the custom component.

However, on initial render, the resize doesn't kick in.  However, after tabbing away and returning, the tab content properly resizes. 

I would like the content to resize when the data is loaded.

Could you please provide an example of how this can be done?

**Comment by mygnu** [comment]
I have also noticed this behavior, I was populating data using apollo-graphql, and you have to come back to the tab before it displays for the first time. I was thinking it was graphql issue

**Comment by Stabzs** [comment]
@mygnu thanks for the additional confirmation.  In my case it is a simple $.ajax call, so the retrieval method doesn't seem to be related.

Also, manually triggering the event via: `window.dispatchEvent( new Event('resize') );` seems to have no impact.

**Comment by Stabzs** [comment]
After a lot of painful and unsuccessful experimentation, the best solution/hack I found is to add a `ref` to the tab you want to watch.  This allows you to expose the `updateTabData` method for that tab.

```
// ajax call.then(() => 
this.$refs.tab1.updateTabData(this.$refs.tab1.$data);
```

This feels pretty hacky and it would be nice if there was a more formal API for this.  However, it does properly resize the tab area with animations, which is great.

On a somewhat related note, I also had quite a bit of trouble loading data for a tab on tab change, which I suspect would go hand in hand with people needing to resize based on dynamic data.

Thanks to ref, you can also override the click handler to reload your data.  This isn't optimal either, but it does do the trick.  Once again, it would be wonderful to have an API hook that enables actions on click.

**Comment by marcosmoura** [comment]
Oops! The ```md-tabs``` will be improved on the very next minor version. There is some performance issues, some animation problems that will be fixed too. Sorry to make you wait a little bit.

**Comment by Stabzs** [comment]
No need to apologize!  You've done fantastic work and I appreciate it, thank you!  I just wanted to make certain I wasn't missing something and if not, bring it to your attention. Looking forward to the next minor version.

**Comment by marcosmoura** [comment]
No. This is on Vue Material side. The ```md-tabs``` is a problematic component. Some concepts that were developed in others components will be used to make the tabs better. :)

**Comment by Stabzs** [comment]
Fair enough :)  Looking forward to the improvements. If I can help, please let me know.
