### ISSUE TITLE
docs components input -> type is Password Reveal second click eye display error

### ISSUE THREAD

**Issue by stevieyu** [marcosmoura/vue-material#95]
![kapture 2016-11-18 at 16 14 25](https://cloud.githubusercontent.com/assets/8325201/20423230/24a615da-adaa-11e6-86b7-6ea7e415a9a3.gif)

**Comment by marcosmoura** [comment]
Yep. I can confirm that. I will change this ASAP. Sorry about that.

**Comment by marcosmoura** [comment]
Already fixed. Will be released on the very next fix version.

PS.: Thanks for this gif. Helped me a lot! :)
