### ISSUE TITLE
md-input-container doesn't set the value

### ISSUE THREAD

**Issue by Cabbaggio** [marcosmoura/vue-material#96]
Hello,
if you set the initial value of an md-input to null or undefined and then overrides it (asynchronous like an ajax) than the value of the md-input-container will not be set to the new value

example:

```
<md-input-container>
  <label>test</label>
  <md-input v-model='initValue'></md-input>
</md-input-container>

data () {
  return {initValue: undefined}
}

created () {
  setTimeout(() => {
    this.initValue = '123';
  }, 1000);
}
```

**Comment by stefanpkc** [comment]
I've reproduced it and you're partially right. The value is set. It's just not visible. On update of the input it should emit an event with the new value so the parent container gets notified. Then it can add the class md-has-value.

If you open your developer tools and do this: ```<div class="md-input-container md-has-value">```
you will see the value is visible.

**Comment by marcosmoura** [comment]
See #100

**Comment by abhimanusharma** [comment]
@stefanpkc Can you show an example to how to emit an event with new values so that these values will be visible as I am facing similar issue.
