### ISSUE TITLE
How to set focus on md-input?

### ISSUE THREAD

**Issue by v0y** [marcosmoura/vue-material#98]
Hello,

Thank you for great work!

My question is: How to set focus on `md-input`?
I tried something like:

```javascript
this.$refs.myref.$el.focus()
```

But it doesn't work

Any ideas? thanks!

**Comment by stefanpkc** [comment]
in console: ```$vm.$refs.myref.$el.focus();```

I tried this in the mounted method: ```this.$refs.myref.$el.focus();```

On the component itself: ```<md-input ref="myref" v-model="initialValue"></md-input>```

Works for me.

**Comment by marcosmoura** [comment]
If you want to set this when some button is clicked you can have something like that:
``` html
<md-button @click.native="$refs.focusable.$el.focus()">Set Focus</md-button>
<md-input-container>
  <md-input ref="focusable"></md-input>
</md-input-container>
```

If you want this programatically this should be on the ```mounted``` function.

**Comment by tsunamilx** [comment]
Didn't work for me.
I have to set timeout in order to make it work:
```javascript
setTimeout(() => {this.$refs.focusable.$el.focus();}, 500);
```
```html
<md-input ref="focusable"></md-input>
```

**Comment by Matt-Dionis** [comment]
I'm noticing the need for `setTimeout` as well. In my case I want to autofocus an md-input when an md-dialog is opened:

```html
<md-input placeholder="Name" v-model="newLocation.name" `ref="nameInput"></md-input>
```
```javascript
openDialog (ref) {
  this.$refs[ref].open();
  setTimeout(() => {
    this.$refs.nameInput.$el.focus();
  });
}
```
The above works, but I'm not sure why I need the `setTimeout`. I tried replacing `setTimeout` with `this.$nextTick`, but that does not work.

**Comment by daewooLeeNy** [comment]
In my case, the nextTick() did not work for focus styles.

https://jsfiddle.net/lsinji/cxfrxjg1/5/
