### ISSUE TITLE
svg support for Icons

### ISSUE THREAD

**Issue by stefanpkc** [marcosmoura/vue-material#99]
Would be awesome if svg could be possible with mdButton somehow.

Also, where can we find a list of icons that can be used right now?

**Comment by Cabbaggio** [comment]
i think all of these icons are available https://material.io/icons/

**Comment by stefanpkc** [comment]
Thanks!

Still missing some icons though ;-) would be better if we can choose ourselves by using svg so we are not limited. Would it be as simple as putting it in the slot?

**Comment by marcosmoura** [comment]
Well. Right now the Vue Material doesn't support SVG icons inside ```md-icon```. But will soon. I will prioritize this. Thanks! :)

**Comment by stefanpkc** [comment]
Great!
btw, really great job on vue-material. It's so easy to import just the components you need. Thank you 😄 👍

**Comment by marcosmoura** [comment]
In progress...
